hmrc/vat-registration-frontend

- app/controllers/VatRegistrationController.scala
- app/controllers/feedback/FeedbackController.scala
- app/controllers/userJourney/SignInOutController.scala
- app/controllers/userJourney/TaxableTurnoverController.scala
- app/controllers/userJourney/WelcomeController.scala
- test/controllers/VatRegistrationControllerSpec.scala
- test/controllers/feedback/FeedbackControllerSpec.scala
- test/controllers/userJourney/SignInOutControllerSpec.scala
- test/controllers/userJourney/TaxableTurnoverControllerSpec.scala
- test/controllers/userJourney/WelcomeControllerSpec.scala
- test/helpers/VatRegSpec.scala
This reverts commit 0b98af806e07739cb11c28d71da468f38d0b5019.
It is not a good idea to reference the app.injector in controllers (while here it worked, later we'd be in trouble)
> Revert "simplified DI (implicitly passing Application obj)"

- app/controllers/test/TestSetupController.scala
- app/forms/vatDetails/test/TestSetupForm.scala
- app/models/view/test/SicAndComplianceTestSetup.scala
- app/models/view/test/VatChoiceTestSetup.scala
- app/models/view/test/VatFinancialsTestSetup.scala
- app/models/view/test/VatTradingDetailsTestSetup.scala
- app/views/pages/test_setup.scala.html
Test setup form also split out into logical group mappings, to fix the issue of reaching the limit of 22 fields per form.
> SCRS-5799 Updated test setup page for sic and compliance

- app/models/api/ScrsAddress.scala
- test/models/api/ScrsAddressTest.scala
- test/models/external/CoHoRegisteredOfficeAddressSpec.scala
Improve ScrsAddress equals method to match on case insensitively.
THIS DOES BREAK equality/hashcode contract!!!!
Added equality unit tests
> improve ScrsAddress equality check

- app/controllers/SummaryController.scala
- app/controllers/builders/SummaryFinancialComplianceSectionBuilder.scala
- app/controllers/builders/SummaryLabourComplianceSectionBuilder.scala
- app/controllers/builders/SummaryServiceEligibilitySectionBuilder.scala
- app/models/view/Summary.scala
- app/views/pages/summary.scala.html
- test/controllers/SummaryControllerSpec.scala
the user can get through the whole flow without answering any
compliance questions, if their SIC code selection doesn't fall into any
of the "buckets"
> fixes to summary page

- app/common/ErrorUtil.scala
- app/models/S4LModels.scala
- app/services/VatRegistrationService.scala
- test/fixtures/VatRegistrationFixture.scala
- test/models/S4LModelsSpec.scala
- test/services/VatRegistrationServiceSpec.scala
phase 1 - modify S4LApiTransformer.toApi  to not require a VatLogicalGroup parameter (which is main use-case for model empty vals)
> Refactor remove all model empty vals

- app/views/pages/application_submission_confirmation.scala.html
- conf/application.conf
The confirmation page fails accessibility. This PR updates the markup to conform with GOV.UK standards and bumps to the latest version of HMRC AF to fix this issue.
Note: the AF version bump also introduces many other updates, such as latest phase banner colours (seen in screenshot), among other updates.
> Updating confirmation page to pass accessibility and bumping AF version

- app/views/helpers/templates/summaryRow.scala.html
- app/views/pages/summary.scala.html
- conf/application.conf
This PR updates the check your answers page to use dl's moving away
from tables.
Changes made:
- update to dl from table
- reduce heading size using .heading-large
Note: Visually this page hasn't changed that much.
> Update check your answers page inline with GDS recommendations

- app/views/helpers/mainContentHeader.scala.html
- conf/application.conf
- public/stylesheets/main.css
- public/stylesheets/taas.css
A move to uplift to AF v3, which is a slow move towards eventually
moving away from AF all together.
As part of the work running through the app to see how AF v3 affects
the service layout I updated and fixed a couple of features like the
back button, spacing and font sizing around the continue button and
spacing on summary page continue button.
> Uplift HMRC AF to v3 and uplift styles

- app/features/officer/models/view/LodgingOfficer.scala
- test/features/officer/services/LodgingOfficerServiceSpec.scala
**Bug fix**
Changed the reads for email in digital contact view from required to optional
> [SCRS-10890] fixed email required bug in lodging officer contact details

- app/features/officer/forms/OfficerForms.scala
- test/features/officer/forms/OfficerFormsSpec.scala
**Bug fix**
Add the check on officer former name to be case insensitive.
> [SCRS-11082]: fix to check case insensitive for officer former name

- conf/application.conf
**Bug fix**
Revert ASSETS FRONTEND back to 3.0.2 to not break the current timeout dialog.
> revert assets frontend to 3.0.2 to no break existing timeout dialog

- app/config/FrontendAppConfig.scala
- app/controllers/registration/applicant/IncorpIdController.scala
- app/controllers/registration/applicant/IndividualIdentificationController.scala
- app/controllers/registration/applicant/MinorEntityIdController.scala
- app/controllers/registration/applicant/PartnershipIdController.scala
- app/controllers/registration/applicant/SoleTraderIdentificationController.scala
- app/controllers/registration/transactor/TransactorIdentificationController.scala
- app/models/external/incorporatedentityid/IncorpIdJourneyConfig.scala
- app/models/external/minorentityid/MinorEntityIdJourneyConfig.scala
- app/models/external/partnershipid/PartnershipIdJourneyConfig.scala
- app/models/external/soletraderid/SoleTraderIdJourneyConfig.scala
- it/connectors/IncorpIdConnectorISpec.scala
- it/connectors/MinorEntityIdConnectorISpec.scala
- it/connectors/PartnershipIdConnectorISpec.scala
- it/connectors/SoleTraderIdentificationConnectorISpec.scala
- test/connectors/PartnershipIDConnectorSpec.scala
- test/connectors/SoleTraderIdentificationConnectorSpec.scala
- test/controllers/registration/applicant/IncorpIdControllerSpec.scala
- test/controllers/registration/applicant/SoleTraderIdentificationControllerSpec.scala
- test/services/SoleTraderIdentificationServiceSpec.scala
SAR-8722 Pass regime id in GRS request body
GRS require a regime to be passed over as part of the request body, this will be needed for their final Registration call.
* [√] I've included appropriate tests with any code I've added
* [√] I've executed the acceptance test pack locally to ensure there are no regressions
* [√] I've added my code using logical, atomic commits, squashing as appropriate - including the Jira issue number in the commit message
> SAR-8722 pass regime id in GRS request body

- app/forms/BankAccountDetailsForms.scala
- app/models/BankAccountDetails.scala
- app/models/api/BankAccountDetailsStatus.scala
- app/services/BankAccountDetailsService.scala
- app/services/BankAccountReputationService.scala
- test/services/BankAccountReputationServiceSpec.scala
SAR-8439/SAR-8750
Allow users who are indeterminate to proceed and update BankAccountDetails model to store the state returned from BARS
* [√] I've included appropriate tests with any code I've added
* [√] I've executed the acceptance test pack locally to ensure there are no regressions
* [√] I've added my code using logical, atomic commits, squashing as appropriate - including the Jira issue number in the commit message
> SAR-8439/SAR-8750 store validation status in BankAccountDetails

- app/controllers/test/PartnershipIdentificationStubController.scala
SAR-8780: Update stub to handle extra party types
Partnership ID controller stub updated to handle Limited Partnership, Scottish Partnership, Scottish Limited Partnership and Limited Liability Partnership in addition to General Partnership.
> SAR-8735/SAR-8780 update partnership ID stub to handle all the partnership types

- app/featureswitch/core/config/FeatureSwitchingModule.scala
- app/services/ReturnsService.scala
- test/services/ReturnsServiceSpec.scala
> SAR-9200: AAS feature switch removed

- app/connectors/UpscanConnector.scala
- app/services/UpscanService.scala
- app/views/fileUpload/file_upload.scala.html
- it/connectors/UpscanConnectorISpec.scala
- test/connectors/mocks/MockUpscanConnector.scala
- test/services/UpscanServiceSpec.scala
SAR-9234 [VRS-FE] Update Upscan test page to allow only supported file types
- restrict file types upload in Upscan 
- remove redundant parameter in Upscan call
> SAR-9234 restrict file types upload in Upscan

- app/common/validators/AddressFormResultsHandler.scala
- app/controllers/applicant/InternationalHomeAddressController.scala
- app/controllers/applicant/InternationalPreviousAddressController.scala
- app/controllers/business/InternationalPpobAddressController.scala
- conf/countries-en.json
- conf/messages
- it/controllers/applicant/InternationalHomeAddressControllerISpec.scala
- it/controllers/applicant/InternationalPreviousAddressControllerISpec.scala
- it/controllers/business/InternationalPpobAddressControllerISpec.scala
- test/common/validators/AddressFormResultsHandlerSpec.scala
[SAR-9491](https://jira.tools.tax.service.gov.uk/browse/SAR-9491) - Allow overseas traders to input JE, Guernsey or IOM addresses
> SAR-9491| Add new countries and validate mandatory postcode

- app/common/validators/AddressFormResultsHandler.scala
- conf/countries-en.json
- test/common/validators/AddressFormResultsHandlerSpec.scala
Update postcode missing error message to include country name instead of country code.
**Bug fix**
[SAR-9532](https://jira.tools.tax.service.gov.uk/browse/SAR-9532)
> SAR-9532| Update missing postcode error handling to use country name instead of code

- app/viewmodels/UploadDocumentHintBuilder.scala
- conf/messages
- test/viewmodels/UploadDocumentHintBuilderSpec.scala
> SAR-9560|Add support for additional attachment types

- app/forms/InternationalAddressForm.scala
- test/forms/InternationalAddressFormSpec.scala
[SAR-9785](https://jira.tools.tax.service.gov.uk/browse/SAR-9785)
Fix line1/line2 fields of international form validation, check for empty values.
**Bug fix**
> SAR-9785 | Fix line1/line2 empty field validation

- app/views/CaptureInternationalAddress.scala.html
- conf/messages
- test/views/CaptureInternationalAddressViewSpec.scala
[SAR-10037](https://jira.tools.tax.service.gov.uk/browse/SAR-10037)
**Bug fix**
Change submit button on international address pages to "Save and continue"
> SAR-10037 | Change submit button to 'Save and continue' for international address pages

- project/AppDependencies.scala
[SAR-10070](https://jira.tools.tax.service.gov.uk/browse/SAR-10070)
Upgrade hmrc-mongo-play library to latest version (0.68.0)
> SAR-10070 | Upgrade hmrc-mongo-play-28 to latest version

- app/connectors/AttachmentsConnector.scala
- app/controllers/ApplicationSubmissionController.scala
- app/controllers/attachments/AttachmentMethodController.scala
- app/controllers/attachments/DocumentsRequiredController.scala
- app/controllers/attachments/EmailCoverSheetController.scala
- app/controllers/attachments/MultipleDocumentsRequiredController.scala
- app/controllers/attachments/PostalCoverSheetController.scala
- app/models/api/Attachments.scala
- app/services/AttachmentsService.scala
- it/connectors/AttachmentsConnectorISpec.scala
- it/controllers/attachments/AttachmentMethodControllerISpec.scala
- it/controllers/attachments/DocumentsRequiredControllerISpec.scala
- it/controllers/attachments/EmailCoverSheetControllerISpec.scala
- it/controllers/attachments/MultipleDocumentsRequiredControllerISpec.scala
- it/controllers/attachments/PostalCoverSheetControllerISpec.scala
- test/connectors/AttachmentsConnectorSpec.scala
- test/connectors/mocks/MockAttachmentsConnector.scala
- test/controllers/ApplicationSubmissionControllerSpec.scala
- test/models/api/AttachmentsSpec.scala
- test/services/AttachmentsServiceSpec.scala
[SAR-10084](https://jira.tools.tax.service.gov.uk/browse/SAR-10084)
- Separate attachments list from attachments model, and keep model matching to backend for just attachmentMethod
- Update attachment service to use registration api sections for attachment method
- Keep existing backend usage of attachment list for all and incomplete attachments.
> SAR-10084 | Attachments service tidup and migration to use registration api connector

- app/viewmodels/tasklist/TaskListRowBuilder.scala
- test/viewmodels/tasklist/AboutTheBusinessTaskListSpec.scala
- test/viewmodels/tasklist/AboutYouTaskListSpec.scala
- test/viewmodels/tasklist/RegistrationReasonTaskListSpec.scala
- test/viewmodels/tasklist/TaskListRowBuilderSpec.scala
- test/viewmodels/tasklist/VerifyBusinessTaskListSpec.scala
**Bug fix**
Update prerequisite check logic to chain prerequisites from rows, this way any page hop model updates will stop the following sections to be in wrong state (for ex, below screenshot shows page hop to bank details being complete and the next section, **Registration date**, shows as **Not Started** instead of **Cannot Start Yet**)
> SAR-XXXX | Update tasklist builder prerequisite check to chain prerequisites from tasklist rows

- app/views/attachments/ChooseAttachmentMethod.scala.html
- test/views/attachments/ChooseAttachmentMethodViewSpec.scala
[SAR-10195](https://jira.tools.tax.service.gov.uk/browse/SAR-10195)
Toggle email/upload documents options on attachment method form based on `UploadDocument` FS.
> SAR-10195 | Toggle email/upload attachments based on UploadDocuments FS

- app/controllers/vatapplication/TaxRepController.scala
- it/controllers/vatapplication/TaxRepControllerISpec.scala
[SAR-10218](https://jira.tools.tax.service.gov.uk/browse/SAR-10218)
**Bug fix**
Fix pre population of has-tax-representative answer when editing journey, and user has previously selected `false` as initial answer, from summary page.
> SAR-10218 | Fix tax-rep answer pre population

- app/viewmodels/tasklist/AboutYouTaskList.scala
- test/viewmodels/tasklist/AboutYouTaskListSpec.scala
[SAR-10338](https://jira.tools.tax.service.gov.uk/browse/SAR-10338)
**Bug fix**
Restrict `roleInTheBusiness` model check for non-partnership entity types when running task completion checks for `PersonalInformation` tasklist row.
> SAR-10338 | Restrict roleInTheBusiness check for only certain business entity types

- app/config/FrontendAppConfig.scala
- app/viewmodels/tasklist/VatRegistrationTaskList.scala
- it/itutil/WiremockHelper.scala
- it/support/StubUtils.scala
- test/connectors/BankAccountReputationConnectorSpec.scala
- test/viewmodels/tasklist/VatRegistrationTaskListSpec.scala
[SAR-10337](https://jira.tools.tax.service.gov.uk/browse/SAR-10337)
**Bug fix**
- Add `SuppliesOutsideUk` to list of supported registration reasons for `RegistrationDate` tasklist row
- Fix bank details validation endpoint to remove `v3` prefix
> SAR-10337 | Add additional registration reason that is eligible for showing registration date tasklist row

- app/viewmodels/tasklist/AttachmentsTaskList.scala
- app/viewmodels/tasklist/VatRegistrationTaskList.scala
- test/viewmodels/tasklist/AttachmentsTaskListSpec.scala
- test/viewmodels/tasklist/VatRegistrationTaskListSpec.scala
[SAR-10339](https://jira.tools.tax.service.gov.uk/browse/SAR-10339)
**Bug fix**
For journeys that are not eligible for FRS, attachment tasklist row now uses the previous known state (of vat-returns) as prerequisite.
> SAR-10339 | Attachments tasklist to treat FRS as optional

- app/viewmodels/tasklist/VatRegistrationTaskList.scala
- test/viewmodels/tasklist/VatRegistrationTaskListSpec.scala
[SAR-10343](https://jira.tools.tax.service.gov.uk/browse/SAR-10343)
Update registration date TL status to check for `currentlyTrading` status when in voluntary journey.
> SAR-10343 | Update registration date TL status

- app/forms/FlatRateForms.scala
- app/forms/ReceiveGoodsNipForm.scala
- app/forms/SellOrMoveNipForm.scala
- app/forms/TurnoverEstimateForm.scala
- app/forms/ZeroRatedSuppliesForm.scala
- app/models/FlatRateModel.scala
- conf/messages
- it/controllers/vatapplication/TurnoverEstimateControllerISpec.scala
- it/controllers/vatapplication/ZeroRatedSuppliesControllerISpec.scala
- test/forms/ReceiveGoodsNipFormSpec.scala
- test/forms/SellOrMoveNipFormSpec.scala
- test/forms/TurnoverEstimateFormSpec.scala
- test/forms/ZeroRatedSuppliesFormSpec.scala
SAR-10340 add validation to restrict input value to two decimal points for turnover, zero rated turnover, NIP
> SAR-10340 add validation to restrict input value to two decimal points

- app/config/FrontendAppConfig.scala
- app/viewmodels/tasklist/AttachmentsTaskList.scala
- app/views/attachments/EmailCoverSheet.scala.html
- app/views/attachments/MultipleDocumentsRequired.scala.html
- app/views/attachments/PostalCoverSheet.scala.html
- app/views/attachments/Vat5LRequired.scala.html
- conf/messages
- conf/messages.cy
- test/viewmodels/tasklist/AttachmentsTaskListSpec.scala
- test/views/attachments/EmailCoverSheetViewSpec.scala
- test/views/attachments/MultipleDocumentsRequiredViewSpec.scala
- test/views/attachments/PostalCoverSheetViewSpec.scala
- test/views/attachments/Vat5LRequiredViewSpec.scala
SAR-10426 update document required pages for Option to Tax
- update document required pages for Option to Tax
- update welsh message file with the corresponding new entries
- fix a bug where TaskList link for attachments redirects to a wrong page
> SAR-10426 update document required pages for Option to Tax

- app/viewmodels/tasklist/AboutTheBusinessTaskList.scala
- app/viewmodels/tasklist/VatRegistrationTaskList.scala
- it/controllers/TaskListControllerISpec.scala
[SAR-10449](https://jira.tools.tax.service.gov.uk/browse/SAR-10449)
**Bug fix**
TaskList journeys weren't handling other feature flags as done when the journeys are run with TaskList FS switched off.
Though all the features will be enabled in future, making this change now to keep it consistent with TaskList On/Off.
> SAR-10449 | Update task list rows to check for relevant FS

- app/views/applicant/FormerName.scala.html
- test/views/applicant/FormerNameViewSpec.scala
[SAR-10498](https://jira.tools.tax.service.gov.uk/browse/SAR-10498)
**Bug fix**
As identified in accessibility report, add the missing legend to fieldset on former name page
> SAR-10498 | Add missing legend to fieldset on FormerName page

- app/views/components/DocumentUploadSummaryTable.scala.html
- app/views/components/ObiSummaryTable.scala.html
- test/views/fileupload/DocumentUploadSummaryViewSpec.scala
- test/views/otherbusinessinvolvements/ObiSummaryViewSpec.scala
SAR-10531 add table headers for screen readers WCAG
**Bug fix**
> SAR-10531 add table headers for screen readers WCAG

- app/views/applicant/BusinessPartnerEntityType.scala.html
- app/views/applicant/PartnerEntityType.scala.html
- conf/messages
- conf/messages.cy
- test/views/BaseSelectors.scala
- test/views/applicant/BusinessPartnerEntityTypeViewSpec.scala
- test/views/applicant/PartnerEntityTypeViewSpec.scala
[SAR-10720](https://jira.tools.tax.service.gov.uk/browse/SAR-10720)
**Bug fix**
Added hint text to partner entity selection and business entity pages.
> SAR-10720 | Add missing hint texts to partner entity pages

- app/views/applicant/BusinessPartnerEntityType.scala.html
- conf/messages
- conf/messages.cy
- test/views/applicant/BusinessPartnerEntityTypeViewSpec.scala
Remove sub-heading from business selection page as we don't support sub-headings
**Bug fix**
> Remove subheading for business entity selection page

- app/views/business/VatCorrespondence.scala.html
SAR-10822 Remove unnecessary h1 from the page
**Bug fix**
> SAR-10822 Remove unnecessary h1 from the page
