hmrc/vat-registration-frontend

- app/config/frontendWiring.scala
- app/connectors/KeystoreConnector.scala
- app/connectors/S4LConnector.scala
- app/controllers/VatRegistrationController.scala
- app/controllers/userJourney/StartDateController.scala
- app/forms/vatDetails/StartDateForm.scala
- app/models/view/StartDate.scala
- app/views/pages/start_date.scala.html
- project/FrontendBuild.scala
- test/connectors/KeystoreConnectorSpec.scala
- test/connectors/S4LConnectorSpec.scala
- test/controllers/userJourney/StartDateControllerSpec.scala
- test/controllers/userJourney/WelcomeControllerSpec.scala
- test/forms/StartDateFormSpec.scala
- test/helpers/VatRegSpec.scala
- test/mocks/KeystoreMock.scala
- test/mocks/SaveForLaterMock.scala
- test/mocks/VatMocks.scala
- test/mocks/WSHTTPMock.scala
- test/testHelpers/VatRegSpec.scala
This is stage 1 of the S4L and Keystore implementation. Actually storing of the start date details in S4L will be implemented in stage 2 of task SCRS-4555.
> [SCRS-4555|EL] - introducing S4L and Keystore

- app/views/pages/company_bank_account_details.scala.html
- public/javascripts/main.js
> disabling non-numeric user input in numeric fields on the bank account

- app/controllers/userJourney/StartDateController.scala
- app/controllers/userJourney/SummaryController.scala
- app/models/api/VatAccountingPeriod.scala
- app/models/api/VatFinancials.scala
- app/models/view/BusinessActivityDescription.scala
- app/services/VatRegistrationService.scala
- test/connectors/VatRegistrationConnectorSpec.scala
- test/fixtures/VatRegistrationFixture.scala
> Scrs 5413 refactoring

- app/controllers/VatRegistrationController.scala
- test/controllers/VatRegistrationControllerSpec.scala
- test/forms/vatContact/BusinessContactDetailsFormSpec.scala
- test/models/view/vatContact/BusinessContactDetailsSpec.scala
- test/testHelpers/FormInspectors.scala
removing coverage-off toggle by adding tests
> removing coverage-off toggle by adding tests

- app/forms/vatContact/BusinessContactDetailsForm.scala
- app/models/view/sicAndCompliance/financial/ActAsIntermediary.scala
- public/javascripts/main.js
- test/helpers/VatRegSpec.scala
also some minor tweaks following an IntelliJ code inspection
> making email validation regex consistent with updated regex on backend

- test/mocks/VatMocks.scala
- test/services/VatRegistrationServiceSpec.scala
managed to cut out 120 lines from the VatRegistrationServiceSpec
really couldn't tolerate all the copy-pasted stuff. there's more to be cleaned up but one step at a time
> cleaning up the VatRegistrationServiceSpec

- app/controllers/sicAndCompliance/cultural/NotForProfitController.scala
- app/controllers/sicAndCompliance/financial/ActAsIntermediaryController.scala
- app/controllers/sicAndCompliance/financial/DiscretionaryInvestmentManagementServicesController.scala
- app/controllers/vatFinancials/vatBankAccount/CompanyBankAccountController.scala
- app/models/ElementPath.scala
> changes to ElementPath to reflect BE updates

- app/views/pages/vatEligibility/eligible.scala.html
- app/views/pages/vatEligibility/ineligible.scala.html
- test/controllers/vatTradingDetails/vatChoice/StartDateControllerSpec.scala
added CSRF tokens to forms on success/failure pages
> Scrs 3310 service criteria questions

- app/auth/VatExternalUrls.scala
- app/connectors/AddressLookupConnector.scala
- conf/application.conf
- test/connectors/AddressLookupConnectorSpec.scala
- test/connectors/VatRegistrationConnectorSpec.scala
- test/controllers/VatRegistrationControllerSpec.scala
- test/controllers/feedback/FeedbackControllerSpec.scala
- test/controllers/vatLodgingOfficer/OfficerDateOfBirthControllerSpec.scala
- test/controllers/vatLodgingOfficer/OfficerNinoControllerSpec.scala
also aligning some more test cases with how other tests have been structured as of recently
> deduplicating configuration

- app/models/view/vatLodgingOfficer/OfficerView.scala
- app/services/PrePopulationService.scala
- test/models/view/vatLodgingOfficer/OfficerViewSpec.scala
- test/services/PrePopulationServiceSpec.scala
> SCRS-6922 tech debt

- test/controllers/ppob/PpobControllerSpec.scala
- test/controllers/vatEligibility/ServiceCriteriaQuestionsControllerSpec.scala
- test/controllers/vatLodgingOfficer/CompletionCapacityControllerSpec.scala
- test/controllers/vatLodgingOfficer/FormerNameControllerSpec.scala
- test/controllers/vatLodgingOfficer/OfficerHomeAddressControllerSpec.scala
- test/controllers/vatLodgingOfficer/PreviousAddressControllerSpec.scala
- test/controllers/vatTradingDetails/vatChoice/StartDateControllerSpec.scala
- test/helpers/VatRegSpec.scala
- test/mocks/VatMocks.scala
- test/services/S4LServiceSpec.scala
- test/services/VatRegistrationServiceSpec.scala
reset all mocks
move local mocks to VatMocks
minor refactorings
> SCRS-7365: reset all mocks

- app/controllers/VatRegistrationController.scala
- app/services/S4LService.scala
- test/controllers/ppob/PpobControllerSpec.scala
- test/controllers/vatLodgingOfficer/OfficerHomeAddressControllerSpec.scala
- test/controllers/vatLodgingOfficer/PreviousAddressControllerSpec.scala
- test/helpers/S4LMockSugar.scala
- test/services/S4LServiceSpec.scala
> SCRS-7985-rework-handling-of-none-in-upserts

- app/models/api/CompletionCapacity.scala
- app/models/api/DateOfBirth.scala
- app/models/api/OfficerContactDetails.scala
- app/models/api/OfficerName.scala
- app/models/api/VatContact.scala
- app/models/api/VatDigitalContact.scala
- app/models/api/VatFinancials.scala
- app/models/api/VatLodgingOfficer.scala
- app/models/api/VatSicAndCompliance.scala
- app/models/api/VatTradingDetails.scala
- app/models/external/OfficerList.scala
- test/connectors/VatRegistrationConnectorSpec.scala
- test/fixtures/VatRegistrationFixture.scala
- test/models/view/vatLodgingOfficer/CompletionCapacityViewSpec.scala
- test/models/view/vatLodgingOfficer/FormerNameDateViewSpec.scala
- test/models/view/vatLodgingOfficer/FormerNameViewSpec.scala
- test/models/view/vatLodgingOfficer/OfficerContactDetailsViewSpec.scala
- test/models/view/vatLodgingOfficer/OfficerHomeAddressViewSpec.scala
- test/models/view/vatLodgingOfficer/OfficerSecurityQuestionsViewSpec.scala
- test/models/view/vatLodgingOfficer/OfficerViewSpec.scala
- test/models/view/vatLodgingOfficer/PreviousAddressViewSpec.scala
- test/services/PrePopulationServiceSpec.scala
last step: actually remove the model.empty vals
> remove all api model 'empty' vals

- README.md
- app/controllers/SummaryController.scala
- app/controllers/TwirlViewController.scala
- app/controllers/VatRegistrationController.scala
- app/controllers/WelcomeController.scala
- app/controllers/builders/SummaryServiceEligibilitySectionBuilder.scala
- app/controllers/builders/SummaryVatDetailsSectionBuilder.scala
- app/controllers/builders/SummaryVatThresholdBuilder.scala
- app/controllers/test/FeatureSwitchController.scala
- app/utils/BooleanFeatureSwitch.scala
- conf/application.conf
- conf/test.routes
- test/controllers/SummaryControllerSpec.scala
- test/controllers/TwirlViewControllerSpec.scala
- test/controllers/builders/SummaryServiceEligibilitySectionBuilderSpec.scala
- test/controllers/builders/SummaryVatDetailsSectionBuilderSpec.scala
- test/controllers/test/FeatureSwitchControllerSpec.scala
- test/helpers/VatRegSpec.scala
Added feature switch to change point to VREFE by default it points to VRFE
> Updated links to point to VREFE from welcome and summary pages

- app/controllers/SummaryController.scala
- app/controllers/builders/SummaryVatDetailsSectionBuilder.scala
- app/features/financials/controllers/vatAccountingPeriod/AccountingPeriodController.scala
- app/features/financials/controllers/vatAccountingPeriod/VatReturnFrequencyController.scala
- app/features/tradingDetails/controllers/vatChoice/MandatoryStartDateController.scala
- app/features/tradingDetails/controllers/vatChoice/StartDateController.scala
- app/features/tradingDetails/forms/MandatoryStartDateForm.scala
- app/features/tradingDetails/views/vatChoice/mandatory_start_date_incorp.scala.html
- app/features/tradingDetails/views/vatChoice/start_date_incorp.scala.html
- app/models/MonthYearModel.scala
- conf/messages
- test/controllers/builders/SummaryVatDetailsSectionBuilderSpec.scala
- test/features/financials/controllers/vatAccountingPeriod/AccountingPeriodControllerSpec.scala
- test/features/financials/controllers/vatAccountingPeriod/VatReturnFrequencyControllerSpec.scala
- test/features/trading-details/controllers/vatChoice/MandatoryStartDateControllerSpec.scala
- test/features/trading-details/controllers/vatChoice/StartDateControllerSpec.scala
- test/features/trading-details/models/view/vatChoice/StartDateViewSpec.scala
- test/helpers/VatRegSpec.scala
Acceptance Tests PR - https://github.tools.tax.service.gov.uk/HMRC/vat-registration-acceptance-tests/pull/128
> SCRS-5321 Added post incorp vat start datepages for mandatory/voluntary

- app/features/financials/views/estimate_zero_rated_sales.scala.html
- app/features/financials/views/zero_rated_sales.scala.html
- app/features/frs/views/frs_confirm_business_sector.scala.html
- app/features/frs/views/frs_join.scala.html
- app/features/frs/views/frs_register_for.scala.html
- app/features/frs/views/frs_start_date.scala.html
- app/features/frs/views/frs_your_flat_rate.scala.html
- app/features/officer/views/completion_capacity.scala.html
- app/features/officer/views/former_name.scala.html
- app/features/officer/views/officer_contact_details.scala.html
- app/features/officer/views/officer_security_questions.scala.html
- app/features/returns/views/mandatory_start_date_confirmation.scala.html
- app/features/returns/views/mandatory_start_date_incorp_view.scala.html
- app/features/returns/views/start_date_incorp_view.scala.html
- app/features/returns/views/start_date_view.scala.html
- app/features/sicAndCompliance/views/business_activity_description.scala.html
- app/features/sicAndCompliance/views/labour/workers.scala.html
- app/features/tradingDetails/views/eori_apply.scala.html
- app/features/tradingDetails/views/trading_name.scala.html
- app/features/turnoverEstimates/views/estimate_vat_turnover.scala.html
- app/views/pages/summary.scala.html
... and correcting heading hierarchy where noticed
Below are a few examples of changes:
> Improving vertical spacing and standardising panel borders

- app/features/frs/views/frs_start_date.scala.html
Which is failing accessibility check through WAVE
> Removing overlooked redundant label and empty span

- app/features/returns/views/mandatory_start_date_confirmation.scala.html
- app/features/sicAndCompliance/views/compliance_introduction.scala.html
- app/views/pages/summary.scala.html
Before and after screenshots below
> Updating button classes to remove unnecessary 'start' arrow

- app/connectors/VatRegistrationConnector.scala
- app/controllers/SummaryController.scala
- app/controllers/WelcomeController.scala
- app/controllers/builders/SummaryVatDetailsSectionBuilder.scala
- app/models/TaxableThreshold.scala
- app/services/VatRegistrationService.scala
- app/views/pages/welcome.scala.html
- conf/messages
- it/controllers/SummaryControllerISpec.scala
- it/controllers/WelcomeControllerISpec.scala
- it/support/StubUtils.scala
- test/connectors/VatRegistrationConnectorSpec.scala
- test/controllers/SummaryControllerSpec.scala
- test/controllers/WelcomeControllerSpec.scala
- test/controllers/builders/SummaryVatDetailsSectionBuilderSpec.scala
- test/fixtures/VatRegistrationFixture.scala
- test/models/TaxableTresholdSpec.scala
- test/services/VatRegistrationServiceSpec.scala
Replaced static values of the current threshold with dynamic value retrieved from VR
> Retrieval of threshold from VR

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
New feature
Added a PR template to try to improve the quality of the PRs raised. Also added Contributing.md and Issue template at the same time.
> SCRS-11594 Added Github templates as a trial to improve PRs

- .github/PULL_REQUEST_TEMPLATE.md
Added TLS for Mongo and updated template
> [SCRS-11592] updated pr templated to add dependency check

- README.md
> dummy release for app-config-base

- app/config/frontendAppConfig.scala
- app/connectors/ICLConnectorImpl.scala
- app/connectors/IncorporationInformationConnector.scala
- app/features/sicAndCompliance/controllers/SicAndComplianceController.scala
- app/features/sicAndCompliance/services/ICLService.scala
- app/services/IncorporationInformationService.scala
- conf/application.conf
- conf/messages
- it/features/sicAndCompliance/controllers/SicAndComplianceControllerISpec.scala
- it/support/StubUtils.scala
- test/connectors/ICLConnectorSpec.scala
- test/connectors/IncorporationInformationConnectorSpec.scala
- test/features/sicAndCompliance/controllers/SicAndComplianceControllerSpec.scala
- test/features/sicAndCompliance/services/ICLServiceSpec.scala
- test/services/IncorporationInformationServiceSpec.scala
New feature
Passes SIC codes to pre-pop ICL
> SCRS-11003 Passing SIC Codes to ICL

- project/plugins.sbt
SCRS-12086 update dependencies and protocol change
> SCRS-12086 update dependencies and protocol change

- conf/application.conf
> SCRS-11820 OTRS URL change

- app/connectors/BusinessRegistrationConnectorImpl.scala
- app/controllers/WelcomeController.scala
- app/controllers/builders/SummaryVatDetailsSectionBuilder.scala
- app/models/view/Summary.scala
- app/services/SummaryService.scala
- conf/application.conf
- it/controllers/SummaryControllerISpec.scala
- it/support/AppAndStubs.scala
- project/AppDependencies.scala
- test/fixtures/VatRegistrationFixture.scala
- test/models/view/SummaryFromQuestionAnswerJsonSpec.scala
- test/services/SummaryServiceSpec.scala
Squash and wait for app configs to be completed before merging, changed summary urls and fixed non base url usage of vat el fe
> Scrs 11819

- app/controllers/WelcomeController.scala
- app/services/SummaryService.scala
- conf/application.conf
- it/support/AppAndStubs.scala
- test/services/SummaryServiceSpec.scala
> SCRS-11819- removal of base url code where applicable

- build.sbt
- project/AppDependencies.scala
- project/plugins.sbt
SCRS-12012 new build changes and uplifts
> SCRS-12012 new build changes and uplifts

- conf/app.routes
- conf/messages
- it/controllers/SummaryControllerISpec.scala
- it/features/sicAndCompliance/controllers/SicAndComplianceControllerISpec.scala
- project/AppDependencies.scala
- project/plugins.sbt
- test/features/frs/controllers/FlatRateControllerSpec.scala
- test/features/returns/controllers/ReturnsControllerSpec.scala
- test/features/sicAndCompliance/controllers/SicAndComplianceControllerSpec.scala
- test/features/tradingDetails/controllers/TradingDetailsControllerSpec.scala
SCRS-10853  Vat url and dependency update
> SCRS-10853 Vat url and dependency update

- conf/application.conf
- project/AppDependencies.scala
- public/stylesheets/timeout-dialog.css
Changed assets to 3.7.0, put in the fix for timeout box and updated dependencies.
> Scrs 12334

- app/services/VatRegistrationService.scala
- app/views/pages/error/submissionTimeout.scala.html
- project/AppDependencies.scala
- project/plugins.sbt
SCRS-12154 - amended resend functionality for a 429 response from DES
> SCRS-12154 - amended resend functionality for a 429 response from DES

- app/controllers/HonestyDeclarationController.scala
- app/views/honesty_declaration.scala.html
- app/views/layouts/layout.scala.html
- conf/app.routes
- conf/messages
- it/controllers/HonestyDeclarationControllerISpec.scala
- test/controllers/HonestyDeclarationControllerSpec.scala
- test/services/BusinessContactServiceSpec.scala
- test/views/BaseSelectors.scala
- test/views/HonestyDeclarationViewSpec.scala
- test/views/VatRegViewSpec.scala
> SAR-6120 Created Honesty Declaration Page

- it/controllers/IncorpIdControllerISpec.scala
> SAR-6126 Fix incorp id IT tests

- app/config/FrontendAppConfig.scala
- app/connectors/RequestEmailVerificationPasscodeConnector.scala
- app/connectors/VerifyEmailVerificationPasscodeConnector.scala
- app/controllers/test/EmailVerificationStubController.scala
- app/featureswitch/core/config/FeatureSwitchingModule.scala
- app/models/external/EmailVerificationResult.scala
- app/services/EmailVerificationService.scala
- conf/application.conf
- conf/test.routes
- it/connectors/RequestEmailVerificationPasscodeConnectorISpec.scala
- it/connectors/VerifyEmailVerificationPasscodeConnectorISpec.scala
- it/support/AppAndStubs.scala
- test/mocks/EmailVerificationServiceMock.scala
> SAR-6207: Integrate with email verification

- app/config/AddressLookupConfiguration.scala
- app/controllers/ReturnsController.scala
- app/models/api/Threshold.scala
- app/models/external/addresslookup/AddressLookupConfigurationModel.scala
- app/models/external/addresslookup/AddressLookupLanguageModel.scala
- build.sbt
- conf/app.routes
- it/controllers/ReturnsControllerISpec.scala
- it/helpers/FakeTimeService.scala
- test/controllers/ReturnsControllerSpec.scala
- test/fixtures/AddressLookupConstants.scala
- test/models/api/ThresholdSpec.scala
- test/models/external/addresslookup/AddressLookupInitializationModelSpec.scala
> SAR-6200: Update threshold model

- app/config/FrontendAppConfig.scala
- app/connectors/PersonalDetailsValidationConnector.scala
- app/controllers/PersonalDetailsValidationController.scala
- app/controllers/test/PersonalDetailsValidationStubController.scala
- app/featureswitch/core/config/FeatureSwitchingModule.scala
- app/models/TransactorDetails.scala
- app/services/PersonalDetailsValidationService.scala
- conf/app.routes
- conf/application.conf
- conf/test.routes
- it/connectors/IncorpIdConnectorISpec.scala
- it/connectors/PersonalDetailsValidationConnectorISpec.scala
- it/controllers/PersonalDetailsValidationControllerISpec.scala
- it/support/AppAndStubs.scala
- test/controllers/PersonalDetailsValidationControllerSpec.scala
- test/mocks/PersonalDetailsValidationServiceMock.scala
- test/mocks/VatMocks.scala
> SAR-6205 - Integrate with personal details validation

- app/forms/EmailAddressForm.scala
- app/forms/EmailPasscodeForm.scala
- app/forms/constraints/EmailAddressConstraints.scala
- app/forms/constraints/EmailPasscodeConstraints.scala
- conf/messages
- test/forms/EmailAddressFormSpec.scala
- test/forms/EmailPasscodeFormSpec.scala
> SAR-6291: Update email address and passcode validation

- app/models/api/CustomerStatus.scala
- app/models/api/EligibilitySubmissionData.scala
- app/models/api/VatScheme.scala
- app/models/view/ApplicantDetails.scala
- app/services/SummaryService.scala
- it/fixtures/ITRegistrationFixtures.scala
- test/fixtures/TradingDetailsFixtures.scala
- test/fixtures/VatRegistrationFixture.scala
- test/services/SummaryServiceSpec.scala
> SAR-6283 Updated models to match backend

- app/config/FrontendAppConfig.scala
- app/connectors/IncorpIdConnector.scala
- app/controllers/HonestyDeclarationController.scala
- app/controllers/registration/applicant/IncorpIdController.scala
- app/featureswitch/frontend/config/FeatureSwitchProviderConfig.scala
- app/models/IncorporationDetails.scala
- app/models/view/ApplicantDetails.scala
- app/services/ApplicantDetailsService.scala
- app/services/IncorpIdService.scala
- build.sbt
- conf/app.routes
- it/connectors/IncorpIdConnectorISpec.scala
- it/controllers/HonestyDeclarationControllerISpec.scala
- it/controllers/registration/applicant/FormerNameControllerISpec.scala
- it/controllers/registration/applicant/HomeAddressControllerISpec.scala
- it/controllers/registration/applicant/IncorpIdControllerISpec.scala
- it/controllers/registration/applicant/PersonalDetailsValidationControllerISpec.scala
- it/controllers/registration/applicant/PreviousAddressControllerISpec.scala
- it/fixtures/ITRegistrationFixtures.scala
- it/itutil/IntegrationSpecBase.scala
- it/support/AppAndStubs.scala
- test/controllers/HonestyDeclarationControllerSpec.scala
- test/controllers/registration/applicant/IncorpIdControllerSpec.scala
- test/fixtures/ApplicantDetailsFixtures.scala
- test/mocks/IncorpIdServiceMock.scala
- test/models/view/ApplicantDetailsSpec.scala
- test/services/ApplicantDetailsServiceSpec.scala
> SAR-6317: Integrate Incorp ID journey

- app/connectors/IncorpIdConnector.scala
- app/models/IncorporationDetails.scala
- it/connectors/IncorpIdConnectorISpec.scala
> SAR-6353: Update incorp id reads

- app/config/FrontendAppConfig.scala
- conf/application.conf
- it/support/AppAndStubs.scala
> Fix environment config

- app/config/FrontendAppConfig.scala
- conf/application.conf
- it/support/AppAndStubs.scala
> Remove duplicate hosts

- app/config/FrontendAppConfig.scala
> fixed host url

- app/config/FrontendAppConfig.scala
> undid the host url change

- app/config/AddressLookupConfiguration.scala
- app/config/FrontendAppConfig.scala
> SAR-6406 environment fixes

- app/config/FrontendAppConfig.scala
> SAR-6408 fix PDV in environments

- app/models/TransactorDetails.scala
- app/services/ApplicantDetailsService.scala
- it/connectors/PersonalDetailsValidationConnectorISpec.scala
- it/controllers/registration/applicant/FormerNameControllerISpec.scala
- it/fixtures/ApplicantDetailsFixture.scala
- test/fixtures/ApplicantDetailsFixtures.scala
- test/models/view/ApplicantDetailsSpec.scala
> SAR-6370: Hard-code applicant role

- app/config/FrontendAppConfig.scala
- it/support/AppAndStubs.scala
> SAR-6408 Fix pdv callback

- app/connectors/IncorpIdConnector.scala
- app/controllers/test/IncorpIdApiStubController.scala
- conf/test.routes
> Fix Incorp ID stub

- app/controllers/builders/SummaryDirectorDetailsSectionBuilder.scala
> SAR-6355: Remove trailing comman

- app/connectors/VatRegistrationConnector.scala
- app/controllers/BusinessContactDetailsController.scala
- app/controllers/ContactPreferenceController.scala
- app/forms/ContactPreferenceForm.scala
- app/models/BusinessContact.scala
- app/models/CompanyContactDetails.scala
- app/models/ContactPreference.scala
- app/services/BusinessContactService.scala
- app/views/contact_preference.scala.html
- conf/app.routes
- conf/messages
- it/controllers/BusinessContactDetailsControllerISpec.scala
- it/fixtures/ITRegistrationFixtures.scala
- test/connectors/VatRegistrationConnectorSpec.scala
- test/controllers/BusinessContactControllerSpec.scala
- test/controllers/ContactPreferenceControllerSpec.scala
- test/fixtures/VatRegistrationFixture.scala
- test/forms/ContactPreferenceFormSpec.scala
- test/models/BusinessContactSpec.scala
- test/services/BusinessContactServiceSpec.scala
- test/views/ContactPreferencePageSpec.scala
> SAR-6358 Added Contact Preference Page

- app/controllers/ContactPreferenceController.scala
- app/views/contact_preference.scala.html
- test/controllers/ContactPreferenceControllerSpec.scala
- test/views/ContactPreferencePageSpec.scala
> SAR-6416: Update to new components

- app/views/capture_telephone_number.scala.html
- app/views/zero_rated_supplies.scala.html
- conf/messages
- test/views/CaptureTelephoneNumberPageSpec.scala
> SAR-6420 fixed label/hint visibility issue

- app/controllers/ZeroRatedSuppliesController.scala
> SAR-6435 fixed exception on zero rated supplies controller

- app/controllers/registration/applicant/CaptureEmailAddressController.scala
- it/controllers/registration/applicant/CaptureEmailAddressControllerISpec.scala
> SAR-6489: Email verified flag when already verified

- app/controllers/ReturnsController.scala
- app/services/ApplicantDetailsService.scala
- app/services/TimeService.scala
- app/views/start_date_view.scala.html
- conf/messages
- it/controllers/ReturnsControllerISpec.scala
- test/controllers/ReturnsControllerSpec.scala
- test/mocks/TimeServiceMock.scala
> SAR-6399 - Update Earlier Registration page - Mandatory/Voluntary page

- app/services/ReturnsService.scala
- test/services/ReturnsServiceSpec.scala
> SAR-6506 fixed start date calc to use all 3 dates

- app/connectors/RequestEmailVerificationPasscodeConnector.scala
> SAR-6464 Lang added to Email Verification json

- app/controllers/registration/applicant/IncorpIdController.scala
- app/models/external/incorporatedentityid/IncorpIdJourneyConfig.scala
- app/services/IncorpIdService.scala
- it/connectors/IncorpIdConnectorISpec.scala
- test/controllers/registration/applicant/IncorpIdControllerSpec.scala
- test/mocks/IncorpIdServiceMock.scala
> SAR-6482 Add sign out link to Incorp ID journey config

- app/views/govuk_wrapper.scala.html
- app/views/layouts/layout.scala.html
- conf/application.conf
- project/AppDependencies.scala
> SAR-6462 Added Accessibility links to both layouts

- app/viewmodels/SummaryCheckYourAnswersBuilder.scala
- test/viewmodels/checkyouranswers/SummaryCheckYourAnswersBuilderSpec.scala
> SAR-6535 Fixed CYA Content

- app/controllers/feedback/FeedbackController.scala
- app/views/components/phaseBanner.scala.html
- app/views/layouts/layout.scala.html
- test/controllers/feedback/FeedbackControllerSpec.scala
> SAR-6591 - Update the phase banner and add feedback link

- app/config/AddressLookupConfiguration.scala
- app/config/FrontendAppConfig.scala
- app/controllers/ApplicationSubmissionController.scala
- app/controllers/ErrorController.scala
- app/controllers/callbacks/SignInOutController.scala
- app/models/external/addresslookup/AddressLookupOptionsModel.scala
- app/views/components/siteHeader.scala.html
- app/views/layouts/layout.scala.html
- conf/app.routes
- conf/application.conf
- test/controllers/ApplicationSubmissionControllerSpec.scala
- test/controllers/DeleteSessionItemsControllerSpec.scala
- test/controllers/ErrorControllerSpec.scala
- test/controllers/SignInOutControllerSpec.scala
- test/fixtures/AddressLookupConstants.scala
- test/models/external/addresslookup/AddressLookupInitializationModelSpec.scala
> SAR-6592 Updated the feedback url and added sign out links to all pages

- app/views/govuk_wrapper.scala.html
- app/views/layouts/layout.scala.html
- conf/messages
> SAR-6595: Updated Get help with this page link and content

- app/config/FrontendAppConfig.scala
- app/featureswitch/frontend/config/FeatureSwitchProviderConfig.scala
> SAR-6565: Add eligibility to FS page

- app/controllers/BaseController.scala
- app/featureswitch/frontend/config/FeatureSwitchProviderConfig.scala
> SAR-6629: Allow agents to access journey

- app/models/FlatRateModel.scala
- app/services/FlatRateService.scala
- test/fixtures/FlatRateFixtures.scala
- test/models/FlatRateSchemeSpec.scala
- test/services/FlatRateServiceSpec.scala
> SAR-6599 - Update flat Rate Scheme submission to send correct data

- app/services/FlatRateService.scala
- test/services/FlatRateServiceSpec.scala
> SAR-6653 updated the FRS block to not submit category for limited cost traders

- app/controllers/FlatRateController.scala
- app/controllers/ReturnsController.scala
- app/controllers/callbacks/SignInOutController.scala
- app/services/ReturnsService.scala
- app/views/start_date_incorp_view.scala.html
- conf/app.routes
- it/controllers/ReturnsControllerISpec.scala
- test/controllers/FlatRateControllerSpec.scala
- test/controllers/ReturnsControllerSpec.scala
- test/controllers/SignInOutControllerSpec.scala
- test/services/ReturnsServiceSpec.scala
> SAR-6661 Updated voluntary start date page

- app/controllers/ReturnsController.scala
- test/controllers/ReturnsControllerSpec.scala
> SAR-6660 fixed not checking date of incorporation for validation

- app/controllers/ReturnsController.scala
- app/views/start_date_incorp_view.scala.html
> SAR-6705 Fix Voluntary Validation on vat start page

- app/config/FrontendAppConfig.scala
- app/controllers/ContactPreferenceController.scala
- app/controllers/SicAndComplianceController.scala
- app/controllers/registration/sicandcompliance/BusinessActivityDescriptionController.scala
- app/viewmodels/SummaryCheckYourAnswersBuilder.scala
- app/views/business_activity_description.scala.html
- app/views/components/inputTextarea.scala.html
- conf/app.routes
- conf/application.conf
- it/controllers/SicAndComplianceControllerISpec.scala
- it/controllers/registration/sicandcompliance/BusinessActivityDescriptionControllerISpec.scala
- test/controllers/ContactPreferenceControllerSpec.scala
- test/controllers/SicAndComplianceControllerSpec.scala
- test/controllers/registration/sicandcompliance/BusinessActivityDescriptionControllerSpec.scala
- test/viewmodels/checkyouranswers/SummaryCheckYourAnswersBuilderSpec.scala
- test/views/BusinessActivityDescriptionPageSpec.scala
- test/views/VatRegViewSpec.scala
SAR-6690   [VAT-REG-FE] Add for attribute to the label
Bug fix 
> SAR-6690: Add for attribute to the label

- app/views/annual_costs_inclusive.scala.html
- app/views/annual_costs_limited.scala.html
- app/views/business_contact_details.scala.html
- app/views/chooseBusinessType.scala.html
- app/views/enter_company_bank_account_details.scala.html
- app/views/estimate_total_sales.scala.html
- app/views/eu_goods.scala.html
- app/views/former_name.scala.html
- app/views/former_name_date.scala.html
- app/views/frs_register_for.scala.html
- app/views/frs_start_date.scala.html
- app/views/frs_your_flat_rate.scala.html
- app/views/has_company_bank_account.scala.html
- app/views/helpers/templates/errorSummary.scala.html
- app/views/helpers/templates/vatTextArea.scala.html
- app/views/labour/company_provide_workers.scala.html
- app/views/labour/skilled_workers.scala.html
- app/views/labour/temporary_contracts.scala.html
- app/views/labour/workers.scala.html
- app/views/main_business_activity.scala.html
- app/views/mandatory_start_date_incorp_view.scala.html
- app/views/previous_address.scala.html
- app/views/start_date_incorp_view.scala.html
- app/views/start_date_view.scala.html
- app/views/vatAccountingPeriod/accounting_period_view.scala.html
- app/views/vatAccountingPeriod/return_frequency_view.scala.html
- project/AppDependencies.scala
**Bug fix**
Fix applied to the following views:
- Business activity description (highlighted in DAC report)
- Former name change date
- FRS start date
- Bank Account sort code
- Voluntary start date
- Mandatory start date
> SAR-6687 - Fixed programmatic focus issues

- app/controllers/SicAndComplianceController.scala
- app/models/SicAndCompliance.scala
- app/models/SicAndComplianceViews.scala
- app/services/ICLService.scala
- app/services/SicAndComplianceService.scala
- app/viewmodels/SummaryCheckYourAnswersBuilder.scala
- conf/messages
- it/controllers/SicAndComplianceControllerISpec.scala
- it/fixtures/ITRegistrationFixtures.scala
- test/connectors/VatRegistrationConnectorSpec.scala
- test/controllers/SicAndComplianceControllerSpec.scala
- test/models/SicAndComplianceSpec.scala
- test/services/ICLServiceSpec.scala
- test/services/SicAndComplianceServiceSpec.scala
> SAR-6700/SAR-6733 Fixed icl routing and compliance logic

- app/config/AddressLookupConfiguration.scala
> SAR-6741 Fix build fail due to trailing comma

- app/forms/FormValidation.scala
- conf/messages
- test/forms/CompanyContactDetailsFormSpec.scala
> SAR-6764 Updated Validation for capture phone number

- app/forms/FormValidation.scala
- app/forms/TradingDetailsForms.scala
- test/forms/TradingNameFormSpec.scala
> SAR-6770 Validation added to Trading Name

- conf/app.routes
- it/controllers/SicAndComplianceControllerISpec.scala
- it/controllers/registration/sicandcompliance/SupplyWorkersControllerISpec.scala
- it/controllers/registration/sicandcompliance/SupplyWorkersIntermediaryControllerISpec.scala
- it/controllers/registration/sicandcompliance/WorkersControllerISpec.scala
> SAR-6820: Updated URLs for compliance pages

- app/views/layouts/layout.scala.html
> SAR-6828 Updated HMRC Footer to fix missing footer links

- app/connectors/RequestEmailVerificationPasscodeConnector.scala
- app/connectors/VerifyEmailVerificationPasscodeConnector.scala
- app/controllers/registration/applicant/CaptureEmailPasscodeController.scala
- app/controllers/test/EmailVerificationStubController.scala
- app/models/external/VerifyEmailPasscodeResult.scala
- it/connectors/VerifyEmailVerificationPasscodeConnectorISpec.scala
- it/controllers/registration/applicant/CaptureEmailPasscodeControllerISpec.scala
* [y] I've included appropriate tests with any code I've added
* [y] I've executed the acceptance test pack locally to ensure there are no regressions
* [y] I've added my code using logical, atomic commits, squashing as appropriate - including the Jira issue number in the commit message
> SAR-6843 Email Verification code updated

- app/forms/SicAndComplianceForms.scala
- conf/app.routes
- conf/messages
- test/forms/SicAndComplianceFormsSpec.scala
> SAR-6841 Updated Regex for Business activity description

- app/controllers/registration/applicant/CaptureEmailPasscodeController.scala
- app/views/pages/error/error_template.scala.html
- app/views/pages/error/passcodeNotFound.scala.html
- conf/messages
- it/controllers/registration/applicant/CaptureEmailPasscodeControllerISpec.scala
> SAR-6844 Create new error pages and update navigation logic

- app/views/business_activity_description.scala.html
- test/views/BusinessActivityDescriptionPageSpec.scala
> SAR-6866 Updated content to match prototype

- app/views/business_activity_description.scala.html
- test/views/BusinessActivityDescriptionPageSpec.scala
Reverts hmrc/vat-registration-frontend#549
> Revert "SAR-6866 Updated content to match prototype"

- app/connectors/VatRegistrationConnector.scala
- app/controllers/HonestyDeclarationController.scala
- app/services/VatRegistrationService.scala
- it/connectors/VatRegistrationConnectorISpec.scala
- it/support/StubUtils.scala
- test/controllers/HonestyDeclarationControllerSpec.scala
- test/fixtures/VatRegistrationFixture.scala
- test/services/VatRegistrationServiceSpec.scala
[VAT-REG-FE] Update service to submit honesty declaration answer to the BE
> Update service to submit honesty declaration

- app/views/enter_company_bank_account_details.scala.html
- app/views/former_name_date.scala.html
- app/views/test/sic_stub.scala.html
> SAR-6786 - Updates to facilitate ATs' revamp

- app/controllers/BankAccountDetailsController.scala
- app/controllers/NoUKBankAccountController.scala
- app/forms/NoUKBankAccountForm.scala
- app/models/BankAccountDetails.scala
- app/models/NoUKBankAccount.scala
- app/services/BankAccountDetailsService.scala
- app/utils/JsonUtilities.scala
- app/views/no_uk_bank_account.scala.html
- conf/app.routes
- conf/messages
- it/client/BankAccountClientSpec.scala
- it/fixtures/ITRegistrationFixtures.scala
- test/fixtures/VatRegistrationFixture.scala
- test/models/BankAccountDetailsSpec.scala
- test/services/BankAccountDetailsServiceSpec.scala
- test/viewmodels/checkyouranswers/SummaryCheckYourAnswersBuilderSpec.scala
* [aye] I've included appropriate tests with any code I've added
* [yep] I've executed the acceptance test pack locally to ensure there are no regressions
* [sí] I've added my code using logical, atomic commits, squashing as appropriate - including the Jira issue number in the commit message
* [] I've run a dependency check to ensure all dependencies are up to date
> SAR-6851 Tests updated for new No UK Bank Account Page

- app/config/FrontendAppConfig.scala
- app/connectors/VerifyEmailVerificationPasscodeConnector.scala
- app/controllers/registration/applicant/CaptureEmailPasscodeController.scala
- app/controllers/registration/applicant/errors/EmailPasscodesMaxAttemptsExceededController.scala
- app/views/pages/error/maxPasscodeAttemptsExceeded.scala.html
- conf/app.routes
- conf/messages
- it/controllers/registration/applicant/CaptureEmailPasscodeControllerISpec.scala
- it/controllers/registration/applicant/EmailPasscodesMaxAttemptsExceededControllerISpec.scala
- test/views/MaxPasscodeAttemptsExceededPageSpec.scala
> create new error page for 403

- app/controllers/registration/applicant/errors/EmailPasscodesMaxAttemptsExceededController.scala
> removed extra comma

- app/controllers/registration/applicant/CaptureRoleInTheBusinessController.scala
- app/controllers/registration/applicant/PersonalDetailsValidationController.scala
- app/forms/RoleInTheBusinessForm.scala
- app/models/RoleInTheBusinessModel.scala
- app/models/TransactorDetails.scala
- app/models/view/ApplicantDetails.scala
- app/models/view/ApplicantDetailsView.scala
- app/services/ApplicantDetailsService.scala
- app/views/role_in_the_business.scala.html
- conf/app.routes
- conf/messages
- it/connectors/PersonalDetailsValidationConnectorISpec.scala
- it/controllers/registration/applicant/CaptureRoleInTheBusinessControllerISpec.scala
- it/controllers/registration/applicant/FormerNameControllerISpec.scala
- it/controllers/registration/applicant/HomeAddressControllerISpec.scala
- it/controllers/registration/applicant/PersonalDetailsValidationControllerISpec.scala
- it/controllers/registration/applicant/PreviousAddressControllerISpec.scala
- it/fixtures/ApplicantDetailsFixture.scala
- test/controllers/registration/applicant/CaptureRoleInTheBusinessSpec.scala
- test/controllers/registration/applicant/PersonalDetailsValidationControllerSpec.scala
- test/fixtures/ApplicantDetailsFixtures.scala
- test/models/view/ApplicantDetailsSpec.scala
> SAR-6850: Create Controller,Form,View for the new page

- app/controllers/registration/applicant/CaptureRoleInTheBusinessController.scala
- app/views/role_in_the_business.scala.html
- it/controllers/registration/applicant/CaptureRoleInTheBusinessControllerISpec.scala
> SAR-6850 Create Controller,Form,View for the new page

- app/controllers/test/EmailVerificationStubController.scala
> added stub for error page

- conf/application.conf
- project/AppDependencies.scala
- project/plugins.sbt
> Dependecy updates

- app/viewmodels/SummaryCheckYourAnswersBuilder.scala
- app/views/role_in_the_business.scala.html
- conf/messages
- test/viewmodels/checkyouranswers/SummaryCheckYourAnswersBuilderSpec.scala
> SAR-6850:Create Controller,Form,View for the new page

- app/forms/RoleInTheBusinessForm.scala
> Error message fix

- app/viewmodels/SummaryCheckYourAnswersBuilder.scala
- app/views/no_uk_bank_account.scala.html
- conf/messages
SAR-6918 spacing issue on cya fix
**Bug fix 
no bank account now uses message in cya
> spacing on cya fix

- app/config/FrontendAppConfig.scala
- app/controllers/BaseController.scala
- app/controllers/IndividualAffinityKickOutController.scala
- app/views/pages/error/individualAffinityKickOut.scala.html
- conf/app.routes
- conf/messages
- test/controllers/BaseControllerSpec.scala
- test/controllers/IndividualAffinityKickOutControllerSpec.scala
- test/views/IndividualAffinityKickOutViewSpec.scala
> SAR-6931 Added new error page for individual affinity

- app/assets/javascripts/gtm.js
- app/views/govuk_wrapper.scala.html
- app/views/layouts/layout.scala.html
- conf/application.conf
> SAR-6945 removed gtm and ga

- app/controllers/BankAccountDetailsController.scala
- app/controllers/registration/applicant/CaptureEmailPasscodeController.scala
> SAR-7118: Fix match error in BankAccountDetailsController

- app/controllers/FlatRateController.scala
- app/views/frs_your_flat_rate.scala.html
- test/controllers/FlatRateControllerSpec.scala
- test/views/FrsYourFlatRatePageSpec.scala
> SAR-7167 Fix bug on Confirm flat rate page

- app/connectors/VerifyEmailVerificationPasscodeConnector.scala
- app/controllers/test/EmailVerificationStubController.scala
- it/controllers/registration/applicant/CaptureEmailPasscodeControllerISpec.scala
> fixed passcode connector and stub

- app/views/layouts/layout.scala.html
> SAR-7235 Add div to fix error page layout

- app/config/FrontendAppConfig.scala
- app/controllers/test/SoleTraderIdentificationStubController.scala
- conf/test.routes
> SAR-7245 Added stub for sole trader identification

- app/config/AddressLookupConfiguration.scala
- app/config/FrontendAppConfig.scala
- conf/application.conf
- test/models/external/addresslookup/AddressLookupInitializationModelSpec.scala
> SAR-7311: Updated a11y statement link for ALF

- app/connectors/VatRegistrationConnector.scala
- app/controllers/SaveAndRetrieveController.scala
- app/services/SaveAndRetrieveService.scala
- app/services/VatRegistrationService.scala
- conf/app.routes
- it/controllers/SaveAndRetrieveControllerISpec.scala
- test/connectors/VatRegistrationConnectorSpec.scala
- test/services/SaveAndRetrieveServiceSpec.scala
- test/services/mocks/MockVatRegistrationService.scala
> SAR-7314 Get full scheme from S4L and store in backend

- app/assets/javascripts/backLink.js
- app/controllers/ApplicationProgressSavedController.scala
- app/views/pages/application_progress_saved.scala.html
- conf/app.routes
- conf/messages
- test/controllers/ApplicationProgressSavedControllerSpec.scala
- test/views/ApplicationProgressSavedViewSpec.scala
> SAR-7375 added progress saved page

- app/config/FrontendAppConfig.scala
- app/controllers/BaseController.scala
- app/controllers/WelcomeController.scala
- app/models/api/trafficmanagement/RegistrationInformation.scala
- app/services/SaveAndRetrieveService.scala
- app/services/SessionProfile.scala
- app/services/TrafficManagementService.scala
- app/services/VatRegistrationService.scala
- test/controllers/WelcomeControllerSpec.scala
- test/services/TrafficManagementServiceSpec.scala
- test/testHelpers/VatMocks.scala
- test/views/CaptureTelephoneNumberPageSpec.scala
> SAR-7372 Check TM at the start of journey for draft

- app/controllers/registration/annualaccountingscheme/AASPaymentMethodController.scala
- app/forms/AASPaymentMethodForm.scala
- app/models/AASPaymentMethod.scala
- app/views/annualaccountingscheme/aas_payment_method.scala.html
- app/views/components/inputRadio.scala.html
- app/views/role_in_the_business.scala.html
- conf/app.routes
- conf/messages
- it/controllers/registration/annualaccountingscheme/AASPaymentMethodControllerISpec.scala
- test/forms/AASPaymentMethodFormSpec.scala
- test/views/ApplyForEoriViewSpec.scala
- test/views/BusinessActivityDescriptionPageSpec.scala
- test/views/CaptureEmailAddressViewSpec.scala
- test/views/CaptureEmailPasscodeViewSpec.scala
- test/views/CaptureTelephoneNumberPageSpec.scala
- test/views/ClaimRefundsViewSpec.scala
- test/views/ContactPreferencePageSpec.scala
- test/views/EmailVerifiedViewSpec.scala
- test/views/FrsYourFlatRatePageSpec.scala
- test/views/IntermediarySupplyPageSpec.scala
- test/views/JoinFrsViewSpec.scala
- test/views/NoUKBankAccountPageSpec.scala
- test/views/SupplyWorkersViewSpec.scala
- test/views/TradingNameViewSpec.scala
- test/views/VatRegViewSpec.scala
- test/views/WorkersPageSpec.scala
- test/views/ZeroRatedSuppliesViewSpec.scala
- test/views/annualaccountingscheme/AASPaymentMethodViewSpec.scala
- test/views/annualaccountingscheme/LastMonthOfAccountingYearViewSpec.scala
> SAR-7525b: Added AAS How Do You Want To Pay page view, form, controller and tests

- app/controllers/registration/annualaccountingscheme/PaymentFrequencyController.scala
- app/forms/PaymentFrequencyForm.scala
- app/models/PaymentFrequency.scala
- app/views/annualaccountingscheme/payment_frequency.scala.html
- conf/app.routes
- conf/messages
- it/controllers/registration/annualaccountingscheme/PaymentFrequencyControllerISpec.scala
- test/forms/PaymentFrequencyFormSpec.scala
- test/views/annualaccountingscheme/PaymentFrequencyPageSpec.scala
> SAR-7524 View and Controller How often do you want to make payments page

- app/controllers/registration/returns/LastMonthOfAccountingYearController.scala
- app/controllers/registration/returns/PaymentFrequencyController.scala
- app/controllers/registration/returns/PaymentMethodController.scala
- app/forms/AnnualStaggerForm.scala
- app/models/api/returns/Returns.scala
- app/services/ReturnsService.scala
- app/views/returns/last_month_of_accounting_year.scala.html
- it/controllers/registration/returns/LastMonthOfAccountingYearControllerISpec.scala
- it/controllers/registration/returns/PaymentFrequencyControllerISpec.scala
- it/controllers/registration/returns/PaymentMethodControllerISpec.scala
- it/support/StubUtils.scala
- test/models/ReturnsSpec.scala
- test/services/ReturnsServiceSpec.scala
> SAR-7527 Updated the new pages to prepop and submit data

- app/services/FlatRateService.scala
- test/services/FlatRateServiceSpec.scala
> SAR-7615 updated frs calculation

- app/viewmodels/SummaryCheckYourAnswersBuilder.scala
- conf/messages
- test/viewmodels/checkyouranswers/SummaryCheckYourAnswersBuilderSpec.scala
> SAR-7530 updated the CYA to display AAS answers

- app/controllers/ContactPreferenceController.scala
- app/controllers/NoUKBankAccountController.scala
- app/views/components/inputTextarea.scala.html
- app/views/contact_preference.scala.html
- app/views/no_uk_bank_account.scala.html
- it/controllers/NoUKBankAccountControllerISpec.scala
> SAR-7622 updated prepop on no uk bank account page

- app/views/returns/aas_payment_method.scala.html
- conf/messages
- test/views/returns/PaymentMethodViewSpec.scala
> Update AAS Content

- app/controllers/registration/applicant/CaptureEmailAddressController.scala
- app/controllers/registration/applicant/CaptureRoleInTheBusinessController.scala
- app/controllers/registration/applicant/CaptureTelephoneNumberController.scala
- app/controllers/registration/applicant/FormerNameController.scala
- app/views/role_in_the_business.scala.html
- it/controllers/registration/applicant/CaptureEmailAddressControllerISpec.scala
- it/controllers/registration/applicant/CaptureRoleInTheBusinessControllerISpec.scala
- it/controllers/registration/applicant/CaptureTelephoneNumberControllerISpec.scala
- it/controllers/registration/applicant/FormerNameControllerISpec.scala
> SAR-7621: Applicant details prepop added

- app/config/FrontendAppConfig.scala
- app/views/returns/aas_payment_method.scala.html
- conf/messages
- test/views/returns/PaymentMethodViewSpec.scala
> SAR-7665 Added Hidden BACS Content to radio

- app/controllers/test/SoleTraderIdentificationStubController.scala
> SAR-7669: Sole Trader Identification Stub updated

- app/config/FrontendAppConfig.scala
- app/connectors/TrafficManagementConnector.scala
- app/controllers/StartNewApplicationController.scala
- app/models/api/trafficmanagement/ClearTrafficManagementResponse.scala
- app/services/TrafficManagementService.scala
- it/controllers/StartNewApplicationControllerISpec.scala
- it/support/StubUtils.scala
- test/connectors/mocks/MockTrafficManagementConnector.scala
- test/services/TrafficManagementServiceSpec.scala
> SAR-7667: Clear traffic management for new journeys

- app/models/RoleInTheBusinessModel.scala
- app/services/ApplicantDetailsService.scala
- it/controllers/registration/applicant/FormerNameControllerISpec.scala
- test/controllers/registration/applicant/IncorpIdControllerSpec.scala
- test/fixtures/ApplicantDetailsFixtures.scala
- test/models/external/incorporatedentityid/LimitedCompanySpec.scala
- test/models/view/ApplicantDetailsSpec.scala
- test/services/ApplicantDetailsServiceSpec.scala
> SAR-7723 updated applicant details service to store business role for sole traders

- app/services/FlatRateService.scala
- app/viewmodels/SummaryCheckYourAnswersBuilder.scala
- test/services/FlatRateServiceSpec.scala
> SAR-7689 updated FRS to store and submit category and percent even for limited cost traders

- app/controllers/FlatRateController.scala
- app/forms/FlatRateForms.scala
- app/views/annual_costs_limited.scala.html
- app/views/pages/start_new_application.scala.html
- conf/messages
- test/controllers/FlatRateControllerSpec.scala
- test/views/AnnualCostsInclusiveViewSpec.scala
- test/views/AnnualCostsLimitedViewSpec.scala
- test/views/ApplicationSubmissionConfirmationViewSpec.scala
- test/views/BusinessActivityDescriptionViewSpec.scala
- test/views/CaptureTelephoneNumberViewSpec.scala
- test/views/ContactPreferenceViewSpec.scala
- test/views/FormerNameDateViewSpec.scala
- test/views/FormerNameViewSpec.scala
- test/views/FrsYourFlatRateViewSpec.scala
- test/views/IntermediarySupplyViewSpec.scala
- test/views/MainBusinessActivityViewSpec.scala
- test/views/MaxPasscodeAttemptsExceededViewSpec.scala
- test/views/NoUKBankAccountViewSpec.scala
- test/views/PreviousAddressViewSpec.scala
- test/views/WorkersViewSpec.scala
> SAR-7764: Updated Annual Costs Limited view and added view spec

- app/controllers/SicAndComplianceController.scala
- app/controllers/registration/applicant/SoleTraderIdentificationController.scala
- app/controllers/registration/applicant/SoleTraderNameController.scala
- app/controllers/registration/sicandcompliance/SupplyWorkersIntermediaryController.scala
- app/controllers/registration/sicandcompliance/WorkersController.scala
- app/controllers/test/SicStubController.scala
- app/forms/SoleTraderNameForm.scala
- app/services/VatRegistrationService.scala
- app/viewmodels/SummaryCheckYourAnswersBuilder.scala
- app/views/soletrader_name.scala.html
- conf/app.routes
- conf/messages
- it/controllers/SicAndComplianceControllerISpec.scala
- it/controllers/registration/sicandcompliance/SupplyWorkersIntermediaryControllerISpec.scala
- it/controllers/registration/sicandcompliance/WorkersControllerISpec.scala
- test/controllers/SicAndComplianceControllerSpec.scala
- test/controllers/registration/applicant/SoleTraderIdentificationControllerSpec.scala
- test/controllers/registration/applicant/SoleTraderNameControllerSpec.scala
- test/controllers/registration/sicandcompliance/SupplyWorkersIntermediaryControllerSpec.scala
- test/controllers/registration/sicandcompliance/WorkersControllerSpec.scala
- test/controllers/test/SicStubControllerSpec.scala
- test/forms/SoleTraderNameFormSpec.scala
- test/services/mocks/MockVatRegistrationService.scala
- test/views/SoleTraderNameViewSpec.scala
> SAR 7673: Sole Trader Name Page

- app/controllers/registration/applicant/FormerNameController.scala
- app/controllers/registration/applicant/FormerNameDateController.scala
- app/forms/OfficerForms.scala
- app/views/components/h1.scala.html
- app/views/former_name.scala.html
- app/views/former_name_date.scala.html
- conf/messages
- it/controllers/registration/applicant/FormerNameControllerISpec.scala
- test/controllers/registration/applicant/FormerNameControllerSpec.scala
- test/controllers/registration/applicant/FormerNameDateControllerSpec.scala
- test/forms/ApplicantFormsSpec.scala
- test/views/FormerNameDateViewSpec.scala
- test/views/FormerNameViewSpec.scala
- test/views/VatRegViewSpec.scala
> SAR-7778 Updated former name pages to use new assets

- app/controllers/FlatRateController.scala
- app/controllers/registration/flatratescheme/ChooseBusinessTypeController.scala
- app/forms/FlatRateForms.scala
- app/viewmodels/SummaryCheckYourAnswersBuilder.scala
- app/views/chooseBusinessType.scala.html
- app/views/frs_confirm_business_sector.scala.html
- conf/app.routes
- test/controllers/FlatRateControllerSpec.scala
- test/controllers/registration/flatratescheme/ChooseBusinessTypeControllerSpec.scala
- test/fixtures/FlatRateFixtures.scala
- test/views/ChooseBusinessTypeViewSpec.scala
> SAR-7796: Migrate chooseBusinessType to new components

- app/controllers/ComplianceIntroductionController.scala
- app/controllers/SicAndComplianceController.scala
- app/controllers/test/SicStubController.scala
- app/views/compliance_introduction.scala.html
- conf/app.routes
- it/controllers/SicAndComplianceControllerISpec.scala
- test/controllers/ComplianceIntroductionControllerSpec.scala
- test/controllers/SicAndComplianceControllerSpec.scala
- test/controllers/test/SicStubControllerSpec.scala
- test/views/ComplianceIntroductionViewSpec.scala
- test/views/SoleTraderNameViewSpec.scala
> SAR-7798 Compliance Introduction page

- app/controllers/FlatRateController.scala
- app/controllers/registration/flatratescheme/ConfirmBusinessTypeController.scala
- app/views/frs_confirm_business_sector.scala.html
- conf/app.routes
- test/controllers/FlatRateControllerSpec.scala
- test/controllers/registration/flatratescheme/ConfirmBusinessTypeControllerSpec.scala
- test/fixtures/FlatRateFixtures.scala
- test/views/ConfirmBusinessTypeViewSpec.scala
- test/views/VatRegViewSpec.scala
> SAR-7812: Migrate confirm business type page

- app/controllers/SicAndComplianceController.scala
- app/controllers/registration/flatratescheme/ChooseBusinessTypeController.scala
- app/forms/SicAndComplianceForms.scala
- app/views/choose_business_type.scala.html
- app/views/main_business_activity.scala.html
- it/controllers/SicAndComplianceControllerISpec.scala
- test/controllers/SicAndComplianceControllerSpec.scala
- test/controllers/registration/flatratescheme/ChooseBusinessTypeControllerSpec.scala
- test/views/ChooseBusinessTypeViewSpec.scala
- test/views/MainBusinessActivityViewSpec.scala
> SAR-7789: Updated Main Business Activity page to use new components

- app/controllers/SicAndComplianceController.scala
> Removed trailing comma

- app/connectors/SoleTraderIdentificationConnector.scala
- app/controllers/registration/applicant/SoleTraderIdentificationController.scala
- app/controllers/test/SoleTraderIdentificationStubController.scala
- app/models/external/incorporatedentityid/BusinessEntity.scala
- app/services/ApplicantDetailsService.scala
- app/services/SoleTraderIdentificationService.scala
- app/viewmodels/SummaryCheckYourAnswersBuilder.scala
- it/connectors/SoleTraderIdentificationConnectorISpec.scala
- it/controllers/registration/applicant/SoleTraderIdentificationControllerISpec.scala
- test/connectors/SoleTraderIdentificationConnectorSpec.scala
- test/connectors/mocks/MockSoleTraderIdConnector.scala
- test/controllers/registration/applicant/SoleTraderIdentificationControllerSpec.scala
- test/fixtures/ApplicantDetailsFixtures.scala
- test/services/SoleTraderIdentificationServiceSpec.scala
- test/services/mocks/MockSoleTraderIdService.scala
> SAR-7855 Updated sole trader model to avoid conflict with partnerships

- app/controllers/SicAndComplianceController.scala
- app/controllers/TradingNameResolverController.scala
- app/controllers/registration/sicandcompliance/SupplyWorkersIntermediaryController.scala
- app/controllers/registration/sicandcompliance/WorkersController.scala
- app/controllers/test/SicStubController.scala
- conf/app.routes
- it/controllers/SicAndComplianceControllerISpec.scala
- it/controllers/TradingNameResolverControllerISpec.scala
- it/controllers/registration/sicandcompliance/SupplyWorkersIntermediaryControllerISpec.scala
- it/controllers/registration/sicandcompliance/WorkersControllerISpec.scala
- test/controllers/SicAndComplianceControllerSpec.scala
- test/controllers/TradingNameResolverControllerSpec.scala
- test/controllers/registration/sicandcompliance/SupplyWorkersIntermediaryControllerSpec.scala
- test/controllers/registration/sicandcompliance/WorkersControllerSpec.scala
- test/controllers/test/SicStubControllerSpec.scala
> SAR-7877: Trading name page resolver

- app/controllers/TradingNameResolverController.scala
- it/controllers/TradingNameResolverControllerISpec.scala
- test/controllers/TradingNameResolverControllerSpec.scala
> SAR-7885: Partnership type added to resolver

- app/controllers/registration/applicant/PreviousAddressController.scala
- app/views/previous_address.scala.html
- app/views/role_in_the_business.scala.html
- test/controllers/registration/applicant/PreviousAddressControllerSpec.scala
- test/views/PreviousAddressViewSpec.scala
> SAR-7888 Updated previous_address.scala.html to use DI

- app/controllers/ErrorController.scala
- app/views/pages/error/submissionFailed.scala.html
- test/controllers/ErrorControllerSpec.scala
- test/views/pages/error/SubmissionFailedViewSpec.scala
> SAR-7892: Updated SubmissionFailed view to use DI/Components

- app/controllers/registration/applicant/CaptureEmailPasscodeController.scala
- app/views/annual_costs_limited.scala.html
- app/views/main_business_activity.scala.html
- app/views/pages/error/maxPasscodeAttemptsExceeded.scala.html
- app/views/pages/error/passcode_not_found.scala.html
- conf/messages
- test/views/PasscodeNotFoundViewSpec.scala
> SAR-7890: Updated Passcode Not Found view to new components and tests

- app/config/FrontendAppConfig.scala
- app/connectors/PartnersConnector.scala
- app/controllers/registration/applicant/LeadPartnerEntityController.scala
- app/controllers/registration/applicant/PartnershipIdController.scala
- app/controllers/registration/applicant/SoleTraderIdentificationController.scala
- app/controllers/test/SoleTraderIdentificationStubController.scala
- app/models/PartnerEntity.scala
- app/models/api/VatScheme.scala
- app/services/ApplicantDetailsService.scala
- app/services/PartnersService.scala
- app/viewmodels/SummaryCheckYourAnswersBuilder.scala
- app/views/lead_partner_entity_type.scala.html
- conf/app.routes
- it/connectors/PartnershipIdConnectorISpec.scala
- it/connectors/SoleTraderIdentificationConnectorISpec.scala
- it/controllers/registration/applicant/LeadPartnerEntityControllerISpec.scala
- it/controllers/registration/applicant/PartnershipIdControllerISpec.scala
- it/controllers/registration/applicant/SoleTraderIdentificationControllerISpec.scala
- it/fixtures/ITRegistrationFixtures.scala
- it/support/StubUtils.scala
- test/connectors/PartnersConnectorSpec.scala
- test/connectors/mocks/MockPartnersConnector.scala
- test/controllers/registration/applicant/LeadPartnerEntityControllerSpec.scala
- test/controllers/registration/applicant/SoleTraderIdentificationControllerSpec.scala
- test/services/PartnersServiceSpec.scala
- test/services/mocks/MockPartnersService.scala
> SAR-7876 Updated the flow for general partnerships

- conf/messages
- test/views/AboutToConfirmSicViewSpec.scala
- test/views/BusinessContactDetailsViewSpec.scala
- test/views/ComplianceIntroductionViewSpec.scala
> SAR-7911: Changed company word to business

- app/config/FrontendAppConfig.scala
- app/connectors/IncorpIdConnector.scala
- app/controllers/HonestyDeclarationController.scala
- app/controllers/TradingNameResolverController.scala
- app/controllers/registration/applicant/IncorpIdController.scala
- app/controllers/registration/applicant/SoleTraderIdentificationController.scala
- app/controllers/test/IncorpIdApiStubController.scala
- app/models/external/BusinessEntity.scala
- app/models/view/Summary.scala
- app/services/IncorpIdService.scala
- app/viewmodels/SummaryCheckYourAnswersBuilder.scala
- conf/app.routes
- conf/messages
- conf/test.routes
- it/connectors/IncorpIdConnectorISpec.scala
- it/controllers/HonestyDeclarationControllerISpec.scala
- it/controllers/registration/applicant/IncorpIdControllerISpec.scala
- it/fixtures/ApplicantDetailsFixture.scala
- it/fixtures/ITRegistrationFixtures.scala
- test/controllers/HonestyDeclarationControllerSpec.scala
- test/controllers/TradingNameResolverControllerSpec.scala
- test/controllers/registration/applicant/IncorpIdControllerSpec.scala
- test/controllers/registration/applicant/SoleTraderIdentificationControllerSpec.scala
- test/fixtures/ApplicantDetailsFixtures.scala
- test/services/mocks/IncorpIdServiceMock.scala
- test/viewmodels/checkyouranswers/SummaryCheckYourAnswersBuilderSpec.scala
> SAR-7923 Added charitable org journey

- app/controllers/FlatRateController.scala
- app/views/apply_for_eori.scala.html
- app/views/frs_register_for.scala.html
- conf/messages
- test/controllers/FlatRateControllerSpec.scala
- test/views/FrsRegisterForViewSpec.scala
> SAR-7948: Updated view to new components and added viewspec

- app/config/FrontendAppConfig.scala
- app/connectors/PartnershipIdConnector.scala
- app/controllers/HonestyDeclarationController.scala
- app/controllers/TradingNameResolverController.scala
- app/controllers/WelcomeController.scala
- app/controllers/registration/applicant/PartnershipIdController.scala
- app/controllers/registration/applicant/SoleTraderIdentificationController.scala
- app/controllers/registration/business/MandatoryTradingNameController.scala
- app/controllers/test/PartnershipIdentificationStubController.scala
- app/models/external/BusinessEntity.scala
- app/services/ApplicantDetailsService.scala
- app/services/PartnershipIdService.scala
- app/viewmodels/SummaryCheckYourAnswersBuilder.scala
- app/views/soletrader_name.scala.html
- conf/app.routes
- conf/test.routes
- it/connectors/PartnershipIdConnectorISpec.scala
- it/controllers/HonestyDeclarationControllerISpec.scala
- it/controllers/TradingNameResolverControllerISpec.scala
- it/controllers/registration/applicant/PartnershipIdControllerISpec.scala
- test/connectors/PartnershipIDConnectorSpec.scala
- test/controllers/TradingNameResolverControllerSpec.scala
- test/controllers/registration/applicant/SoleTraderIdentificationControllerSpec.scala
- test/controllers/registration/business/MandatoryTradingNameControllerSpec.scala
- test/fixtures/ApplicantDetailsFixtures.scala
> SAR-7929 added Trust journey

- app/config/FrontendAppConfig.scala
- app/controllers/IndividualAffinityKickOutController.scala
- app/views/pages/error/IndividualAffinityKickOut.scala.html
- conf/app.routes
- conf/messages
- test/controllers/IndividualAffinityKickOutControllerSpec.scala
- test/views/IndividualAffinityKickOutViewSpec.scala
> SAR-8008: Individual Affinity page links updated

- app/views/annual_costs_inclusive.scala.html
- app/views/enter_company_bank_account_details.scala.html
- app/views/error_template.scala.html
- app/views/frs_join.scala.html
- app/views/has_company_bank_account.scala.html
- app/views/returns/claim_refunds_view.scala.html
- conf/messages
> SAR-8108: Updated views/error_template to use new components + formatting

- app/config/FrontendGlobal.scala
- app/views/honesty_declaration.scala.html
- app/views/pages/error/error_template.scala.html
> SAR-8116: Updated error/error_template view to use new components

- app/featureswitch/frontend/controllers/FeatureSwitchFrontendController.scala
- app/featureswitch/frontend/services/FeatureSwitchRetrievalService.scala
> Simplify feature switching code

- app/config/FrontendAppConfig.scala
- app/connectors/SoleTraderIdentificationConnector.scala
- app/controllers/HonestyDeclarationController.scala
- app/controllers/registration/applicant/SoleTraderIdentificationController.scala
- app/controllers/test/SoleTraderIdentificationStubController.scala
- app/models/TransactorDetails.scala
- app/models/api/PartyType.scala
- app/models/external/BusinessEntity.scala
- app/services/ApplicantDetailsService.scala
- app/services/SoleTraderIdentificationService.scala
- app/viewmodels/SummaryCheckYourAnswersBuilder.scala
- conf/test.routes
- it/connectors/BusinessIdConnectorISpec.scala
- it/connectors/IncorpIdConnectorISpec.scala
- it/connectors/NonRepudiationConnectorISpec.scala
- it/connectors/PartnershipIdConnectorISpec.scala
- it/connectors/PersonalDetailsValidationConnectorISpec.scala
- it/connectors/SoleTraderIdentificationConnectorISpec.scala
- it/connectors/UpscanConnectorISpec.scala
- it/controllers/HonestyDeclarationControllerISpec.scala
- it/fixtures/ApplicantDetailsFixture.scala
- it/fixtures/ITRegistrationFixtures.scala
- it/itutil/ControllerISpec.scala
- test/connectors/SoleTraderIdentificationConnectorSpec.scala
- test/connectors/mocks/MockSoleTraderIdConnector.scala
- test/controllers/registration/applicant/SoleTraderIdentificationControllerSpec.scala
- test/fixtures/ApplicantDetailsFixtures.scala
- test/services/SoleTraderIdentificationServiceSpec.scala
- test/services/mocks/MockSoleTraderIdService.scala
> SAR-8089: Add optional TRN to STI model

- app/config/FrontendAppConfig.scala
- app/controllers/registration/returns/DispatchFromWarehouseController.scala
- app/forms/DispatchFromWarehouseForm.scala
- app/models/api/returns/Returns.scala
- app/views/returns/DispatchFromWarehouseView.scala.html
- conf/app.routes
- conf/messages
- it/controllers/registration/returns/DispatchFromWarehouseControllerISpec.scala
- test/views/returns/DispatchFromWarehouseViewSpec.scala
> SAR-8158 Added Dispatch from warehouse page

- app/controllers/registration/returns/StoringGoodsController.scala
- app/forms/StoringGoodsForm.scala
- app/views/StoringGoods.scala.html
- conf/app.routes
- conf/messages
- it/controllers/registration/returns/StoringGoodsControllerISpec.scala
- test/forms/StoringGoodsFormSpec.scala
- test/views/StoringGoodsViewSpec.scala
> SAR-8157: Storing goods for dispatch page

- app/controllers/registration/returns/SendEUGoodsController.scala
- app/forms/ReturnsForms.scala
- app/forms/SendEuGoodsForm.scala
- app/views/returns/SendEUGoodsView.scala.html
- conf/app.routes
- conf/messages
- it/controllers/registration/returns/SendEUGoodsControllerISpec.scala
- test/views/returns/SendEUGoodsViewSpec.scala
> SAR-8154 Added SendEUGoods NETP page

- app/controllers/registration/returns/StoringGoodsController.scala
- app/controllers/registration/returns/WarehouseNumberController.scala
- app/forms/WarehouseNumberForm.scala
- app/views/returns/WarehouseNumberView.scala.html
- conf/app.routes
- conf/messages
- it/controllers/registration/returns/DispatchFromWarehouseControllerISpec.scala
- it/controllers/registration/returns/StoringGoodsControllerISpec.scala
- it/controllers/registration/returns/WarehouseNumberControllerISpec.scala
- test/views/returns/WarehouseNumberViewSpec.scala
> SAR-8161 Added warehouse number page and fixed some redirects

- app/controllers/registration/returns/SendGoodsOverseasController.scala
- app/forms/SendGoodsOverseasForm.scala
- app/views/returns/SendGoodsOverseasView.scala.html
- conf/app.routes
- conf/messages
- it/controllers/registration/returns/SendGoodsOverseasControllerISpec.scala
- test/views/returns/SendGoodsOverseasViewSpec.scala
> SAR-8153: Send Goods Overseas page

- app/controllers/registration/bankdetails/HasBankAccountController.scala
- app/controllers/registration/returns/ReturnsController.scala
- app/models/OverseasBankDetails.scala
- app/viewmodels/SummaryCheckYourAnswersBuilder.scala
- it/controllers/registration/bankdetails/HasBankAccountControllerISpec.scala
- test/controllers/ReturnsControllerSpec.scala
> SAR-8168 update hasBankAccount redirect and CYA

- app/controllers/registration/returns/DispatchFromWarehouseController.scala
- app/controllers/registration/returns/SendGoodsOverseasController.scala
- app/controllers/registration/returns/StoringGoodsController.scala
- app/controllers/registration/returns/WarehouseNameController.scala
- app/controllers/registration/returns/WarehouseNumberController.scala
- app/forms/WarehouseNameForm.scala
- app/models/api/returns/Returns.scala
- app/viewmodels/SummaryCheckYourAnswersBuilder.scala
- app/views/returns/WarehouseNameView.scala.html
- conf/app.routes
- conf/messages
- it/controllers/SummaryControllerISpec.scala
- it/controllers/registration/returns/WarehouseNameControllerISpec.scala
- it/fixtures/ITRegistrationFixtures.scala
- test/views/returns/WarehouseNameViewSpec.scala
> SAR-8166 Added warehouse name page and added answers to CYA

- app/models/api/Threshold.scala
- app/services/ReturnsService.scala
- it/controllers/registration/flatratescheme/StartDateControllerISpec.scala
- test/services/ReturnsServiceSpec.scala
> SAR-8217 updated frontend to handle the overseas threshold date

- app/controllers/FlatRateController.scala
- app/controllers/registration/attachments/DocumentsPostController.scala
- app/controllers/registration/attachments/DocumentsRequiredController.scala
- app/controllers/registration/flatratescheme/JoinFlatRateSchemeController.scala
- app/controllers/registration/flatratescheme/StartDateController.scala
- app/services/AttachmentsService.scala
- app/views/DocumentsPost.scala.html
- app/views/DocumentsRequired.scala.html
- app/views/components/button.scala.html
- app/views/components/link.scala.html
- app/views/components/saveProgressButton.scala.html
- conf/app.routes
- conf/messages
- it/controllers/registration/attachments/DocumentsPostControllerISpec.scala
- it/controllers/registration/attachments/DocumentsRequiredControllerISpec.scala
- it/controllers/registration/flatratescheme/JoinFlatRateSchemeControllerISpec.scala
- it/controllers/registration/flatratescheme/StartDateControllerISpec.scala
- test/controllers/FlatRateControllerSpec.scala
- test/controllers/registration/flatratescheme/JoinFlatRateSchemeControllerSpec.scala
- test/controllers/registration/flatratescheme/StartDateControllerSpec.scala
- test/views/attachments/DocumentsPostViewSpec.scala
- test/views/attachments/DocumentsRequiredViewSpec.scala
> SAR-8222 Added an attachment check into the flow

- app/models/TransactorDetails.scala
- it/connectors/PersonalDetailsValidationConnectorISpec.scala
- it/connectors/SoleTraderIdentificationConnectorISpec.scala
- it/fixtures/ApplicantDetailsFixture.scala
- it/fixtures/ITRegistrationFixtures.scala
- test/fixtures/ApplicantDetailsFixtures.scala
- test/models/view/ApplicantDetailsSpec.scala
> SAR-8306 Transactor details update to handle trn

- app/controllers/test/SoleTraderIdentificationStubController.scala
> Fixed sole trader id stub for netp

- app/connectors/AttachmentsConnector.scala
- app/controllers/ApplicationSubmissionController.scala
- app/controllers/registration/attachments/DocumentsRequiredController.scala
- app/models/api/Attachments.scala
- app/services/AttachmentsService.scala
- it/connectors/AttachmentsConnectorISpec.scala
- it/controllers/registration/attachments/DocumentsRequiredControllerISpec.scala
- test/connectors/AttachmentsConnectorSpec.scala
- test/controllers/ApplicationSubmissionControllerSpec.scala
> SAR-8363 Connect to new Attachments API

- app/controllers/ApplicationSubmissionController.scala
- app/controllers/registration/attachments/EmailCoverSheetController.scala
- app/views/EmailCoverSheet.scala.html
- app/views/PostalCoverSheet.scala.html
- app/views/components/print.scala.html
- app/views/pages/application_submission_confirmation.scala.html
- conf/app.routes
- conf/messages
- it/controllers/EmailCoverSheetControllerISpec.scala
- test/controllers/ApplicationSubmissionControllerSpec.scala
- test/views/ApplicationSubmissionConfirmationViewSpec.scala
- test/views/EmailCoverSheetViewSpec.scala
SAR 8243 Created new cover letter for email cover letter
Added an email cover letter page, as well as updating the submission confirmation page to allow for email submission and adding a link the the email cover letter
> SAR 8243 Created new cover letter for email cover letter

- app/services/ReturnsService.scala
- test/services/ReturnsServiceSpec.scala
> SAR-8587: Added NonUkNonEstablished case to Returns Service

- app/models/api/EligibilitySubmissionData.scala
- app/services/ReturnsService.scala
- it/fixtures/ITRegistrationFixtures.scala
- test/fixtures/VatRegistrationFixture.scala
> SAR-8470 Updated eligibility submission data to contain the transactor flag

- app/controllers/registration/transactor/TransactorIdentificationController.scala
- app/models/TransactorDetails.scala
- app/services/TransactorDetailsService.scala
- app/services/VatRegistrationService.scala
- conf/app.routes
- it/controllers/registration/transactor/TransactorIdentificationControllerISpec.scala
- test/controllers/HonestyDeclarationControllerSpec.scala
- test/services/TransactorDetailsServiceSpec.scala
- test/services/mocks/MockVatRegistrationService.scala
> SAR-8474 set up the start of the transactor journey and TransactorDetails service

- app/controllers/registration/applicant/CaptureRoleInTheBusinessController.scala
- app/controllers/registration/transactor/DeclarationCapacityController.scala
- app/forms/DeclarationCapacityForm.scala
- app/forms/RoleInTheBusinessForm.scala
- app/models/BusinessRoles.scala
- app/models/TransactorDetails.scala
- app/services/TransactorDetailsService.scala
- app/views/DeclarationCapacityView.scala.html
- conf/app.routes
- conf/messages
- it/controllers/registration/transactor/DeclarationCapacityControllerISpec.scala
- test/fixtures/VatRegistrationFixture.scala
- test/models/TransactorDetailsSpec.scala
- test/services/TransactorDetailsServiceSpec.scala
- test/views/DeclarationCapacityViewSpec.scala
> SAR-8602 Added transactor declaration capacity page

- app/controllers/registration/transactor/OrganisationNameController.scala
- app/forms/OrganisationNameForm.scala
- app/views/OrganisationName.scala.html
- conf/app.routes
- conf/messages
- it/controllers/registration/transactor/OrganisationNameControllerISpec.scala
- test/views/OrganisationNameViewSpec.scala
> SAR-8601: Organisation name page added

- app/config/FrontendAppConfig.scala
- app/controllers/registration/transactor/TransactorHomeAddressController.scala
- app/controllers/registration/transactor/TransactorIdentificationController.scala
- app/controllers/registration/transactor/TransactorInternationalAddressController.scala
- conf/app.routes
- it/controllers/registration/transactor/TransactorHomeAddressControllerISpec.scala
- it/controllers/registration/transactor/TransactorIdentificationControllerISpec.scala
- it/controllers/registration/transactor/TransactorInternationalAddressControllerISpec.scala
Added two controllers for each address page in the transactor flow, modified identification controller for routing and appended ISpecs as appropriate
> SAR-8603 Routing And Controllers For Transactor Address Pages

- app/controllers/registration/transactor/TelephoneNumberController.scala
- app/controllers/registration/transactor/TransactorHomeAddressController.scala
- app/controllers/registration/transactor/TransactorInternationalAddressController.scala
- app/forms/OrganisationNameForm.scala
- app/forms/TransactorTelephoneForm.scala
- app/services/ApplicantDetailsService.scala
- app/views/transactor/TelephoneNumber.scala.html
- conf/app.routes
- conf/messages
- it/controllers/registration/attachments/AttachmentMethodControllerISpec.scala
- it/controllers/registration/transactor/TelephoneNumberControllerISpec.scala
- it/controllers/registration/transactor/TransactorHomeAddressControllerISpec.scala
- it/controllers/registration/transactor/TransactorInternationalAddressControllerISpec.scala
- test/forms/TransactorTelephoneFormSpec.scala
- test/views/transactor/TelephoneNumberViewSpec.scala
> SAR-8686: Telephone number page added

- app/config/FrontendAppConfig.scala
**Update**
general-partnership -> general-partnership-journey
> SAR-8694 Updated General Partnership Journey URL

- it/connectors/PartnershipIdConnectorISpec.scala
- it/controllers/registration/applicant/PartnershipIdControllerISpec.scala
> SAR-8694 ISpecs Fix

- app/config/FrontendAppConfig.scala
- app/connectors/MinorEntityIdConnector.scala
- conf/application.conf
- it/connectors/MinorEntityIdConnectorISpec.scala
- it/controllers/registration/applicant/MinorEntityIdControllerISpec.scala
> SAR-8691: Update minor entity endpoints

- app/controllers/registration/applicant/CaptureEmailPasscodeController.scala
- app/controllers/registration/errors/EmailPasscodeNotFoundController.scala
- app/controllers/registration/errors/EmailPasscodesMaxAttemptsExceededController.scala
- app/controllers/registration/transactor/TransactorCaptureEmailPasscodeController.scala
- app/views/pages/error/maxPasscodeAttemptsExceeded.scala.html
- app/views/pages/error/passcode_not_found.scala.html
- conf/app.routes
- it/controllers/registration/applicant/CaptureEmailPasscodeControllerISpec.scala
- it/controllers/registration/errors/EmailPasscodeNotFoundControllerISpec.scala
- it/controllers/registration/errors/EmailPasscodesMaxAttemptsExceededControllerISpec.scala
- it/controllers/registration/transactor/TransactorCaptureEmailPasscodeControllerISpec.scala
- test/views/MaxPasscodeAttemptsExceededViewSpec.scala
- test/views/PasscodeNotFoundViewSpec.scala
> SAR-8713 Updated email verification errors

- app/controllers/TradingNameResolverController.scala
- app/controllers/registration/business/ShortOrgNameController.scala
- app/featureswitch/core/config/FeatureSwitchingModule.scala
- app/forms/ShortOrgNameForm.scala
- app/models/TradingDetails.scala
- app/services/TradingDetailsService.scala
- app/viewmodels/SummaryCheckYourAnswersBuilder.scala
- app/views/ShortOrgName.scala.html
- conf/app.routes
- conf/messages
- it/controllers/TradingNameResolverControllerISpec.scala
- it/controllers/registration/business/ShortOrgNameControllerISpec.scala
- test/views/ShortOrgNameViewSpec.scala
> SAR-8728 Added new short org name page and feature switch

- app/config/FrontendAppConfig.scala
- app/controllers/registration/attachments/DocumentsRequiredController.scala
- app/controllers/registration/attachments/Vat2RequiredController.scala
- app/views/Vat2Required.scala.html
- conf/app.routes
- conf/messages
- it/controllers/registration/attachments/DocumentsRequiredControllerISpec.scala
- it/controllers/registration/attachments/Vat2RequiredControllerISpec.scala
- test/views/attachments/Vat2RequiredViewSpec.scala
Created VAT2 Required page and controller as well as appropriate test for controller and spec for page view.
> SAR-8756 Created new page for when VAT2 is required

- app/connectors/VatRegistrationConnector.scala
- app/controllers/WelcomeController.scala
- app/models/api/VatSchemeHeader.scala
- app/services/VatRegistrationService.scala
- it/connectors/VatRegistrationConnectorISpec.scala
- it/controllers/WelcomeControllerISpec.scala
> SAR-8809 simplified welcome controller logic and fixed issues with users with past journeys

- app/connectors/VatRegistrationConnector.scala
- app/controllers/WelcomeController.scala
- app/services/VatRegistrationService.scala
- test/services/VatRegistrationServiceSpec.scala
> SAR-8815 fixed error for users with old unparsable data

- app/models/api/VatScheme.scala
- it/connectors/VatRegistrationConnectorISpec.scala
- it/fixtures/ITRegistrationFixtures.scala
- it/support/StubUtils.scala
- test/connectors/VatRegistrationConnectorSpec.scala
- test/fixtures/VatRegistrationFixture.scala
> SAR-8814: Add optional createdDate field to the VatScheme model

- app/config/FrontendAppConfig.scala
- app/connectors/PartnershipIdConnector.scala
- app/controllers/test/PartnershipIdentificationStubController.scala
- it/connectors/PartnershipIdConnectorISpec.scala
- test/forms/MandatoryDateFormSpec.scala
SAR-8779: Add integrations for remaining partnership journeys on partnership ID
Add partnership journey urls in connector for Limited Partnership, Scottish Partnership, Scottish Limited Partnership and Limited Liability Partnership.
> SAR-8735/SAR-8779 add integrations for all the partnership types on partnership ID

- app/controllers/registration/applicant/LeadPartnerEntityController.scala
- app/views/lead_partner_entity_type.scala.html
- it/controllers/registration/applicant/LeadPartnerEntityControllerISpec.scala
- test/controllers/registration/applicant/LeadPartnerEntityControllerSpec.scala
- test/views/LeadPartnerEntityTypeViewSpec.scala
> SAR-8778: Updated lead partner entity to support NETP flow

- app/controllers/registration/business/ScottishPartnershipNameController.scala
- app/forms/ScottishPartnershipNameForm.scala
- app/views/ScottishPartnershipName.scala.html
- conf/app.routes
- conf/messages
- it/controllers/registration/business/ScottishPartnershipNameControllerISpec.scala
- test/views/ScottishPartnershipNameViewSpec.scala
Added a new page to capture scottish partnership company name and store it in the session, as well as corresponding tests
> SAR-8781 Added new page to capture scottish partnership

- app/config/FrontendAppConfig.scala
- app/connectors/PartnershipIdConnector.scala
- app/controllers/registration/applicant/LeadPartnerEntityController.scala
- app/controllers/registration/applicant/PartnershipIdController.scala
- app/controllers/registration/business/ScottishPartnershipNameController.scala
- app/models/external/BusinessEntity.scala
- app/services/ApplicantDetailsService.scala
- app/services/SessionService.scala
- conf/app.routes
- it/connectors/PartnershipIdConnectorISpec.scala
- it/controllers/registration/applicant/LeadPartnerEntityControllerISpec.scala
- it/controllers/registration/applicant/PartnershipIdControllerISpec.scala
- it/controllers/registration/business/ScottishPartnershipNameControllerISpec.scala
- it/fixtures/ApplicantDetailsFixture.scala
> SAR-8782 Allowed partnership lead partners and updated the partnershipId model

- test/forms/VoluntaryDateFormIncorpSpec.scala
* [ X ] I've included appropriate tests with any code I've added
* [ X ] I've added my code using logical, atomic commits, squashing as appropriate - including the Jira issue number in the commit message
> Date range test data updated

- app/controllers/BusinessIdentificationResolverController.scala
- app/controllers/TradingNameResolverController.scala
- app/controllers/registration/applicant/PartnershipIdController.scala
- it/controllers/BusinessIdentificationResolverControllerISpec.scala
- test/controllers/TradingNameResolverControllerSpec.scala
> SAR-8858: Limited partnership and Scottish limited partnership routes

- app/controllers/BusinessIdentificationResolverController.scala
- app/controllers/TradingNameResolverController.scala
- app/controllers/registration/applicant/IndividualIdentificationController.scala
- app/controllers/registration/applicant/PartnershipIdController.scala
- it/controllers/BusinessIdentificationResolverControllerISpec.scala
- it/controllers/registration/applicant/PartnershipIdControllerISpec.scala
- test/controllers/TradingNameResolverControllerSpec.scala
> SAR-8861: LtdLiabilityPartnership routes added

- app/config/FrontendAppConfig.scala
- app/controllers/WelcomeController.scala
- conf/app.routes
- it/controllers/WelcomeControllerISpec.scala
- it/support/RegistrationsApiStubs.scala
> SAR-8921: Init journey endpoint

- app/models/RegistrationReason.scala
- app/models/api/EligibilitySubmissionData.scala
- app/services/ReturnsService.scala
- app/services/VatRegistrationService.scala
- it/controllers/registration/errors/EmailPasscodesMaxAttemptsExceededControllerISpec.scala
- it/controllers/registration/returns/ReturnsControllerISpec.scala
- it/controllers/registration/sicandcompliance/WorkersControllerISpec.scala
- it/fixtures/ITRegistrationFixtures.scala
- test/fixtures/VatRegistrationFixture.scala
Also removed some unused imports to speed up compilation
> SAR-8944: Add RegistrationReason to EligibilitySubmissionData model

- app/controllers/registration/flatratescheme/JoinFlatRateSchemeController.scala
- app/controllers/registration/returns/ReturnsController.scala
- app/services/ReturnsService.scala
- it/controllers/registration/flatratescheme/JoinFlatRateSchemeControllerISpec.scala
- test/controllers/ReturnsControllerSpec.scala
- test/controllers/registration/flatratescheme/JoinFlatRateSchemeControllerSpec.scala
- test/services/ReturnsServiceSpec.scala
> SAR-8945 Updated the journey to properly support VAT Groups

- app/config/FrontendAppConfig.scala
- app/controllers/registration/attachments/DocumentsRequiredController.scala
- app/controllers/registration/attachments/MultipleDocumentsRequiredController.scala
- app/controllers/registration/attachments/Vat51RequiredController.scala
- app/views/MultipleDocumentsRequired.scala.html
- app/views/Vat51Required.scala.html
- conf/app.routes
- conf/messages
> SAR-8948 Added VAT51 attachments support

- app/controllers/registration/applicant/CaptureEmailAddressController.scala
- it/controllers/registration/applicant/CaptureEmailAddressControllerISpec.scala
> SAR-8951 updated applicants email adress page to skip verification for transactors

- app/connectors/VatRegistrationConnector.scala
- app/controllers/ApplicationReferenceController.scala
- app/controllers/HonestyDeclarationController.scala
- app/controllers/WelcomeController.scala
- app/featureswitch/core/config/FeatureSwitchingModule.scala
- app/forms/ApplicationReferenceForm.scala
- app/models/api/VatScheme.scala
- app/models/api/VatSchemeHeader.scala
- app/services/VatRegistrationService.scala
- app/views/ApplicationReference.scala.html
- conf/app.routes
- conf/messages
- it/connectors/VatRegistrationConnectorISpec.scala
- it/controllers/ApplicationReferenceControllerISpec.scala
- it/controllers/HonestyDeclarationControllerISpec.scala
- it/controllers/SummaryControllerISpec.scala
- it/controllers/WelcomeControllerISpec.scala
- it/controllers/registration/flatratescheme/StartDateControllerISpec.scala
- it/controllers/registration/returns/ZeroRatedSuppliesResolverControllerISpec.scala
- it/itutil/ControllerISpec.scala
- it/support/RegistrationsApiStubs.scala
- it/support/StubUtils.scala
- test/connectors/VatRegistrationConnectorSpec.scala
- test/controllers/HonestyDeclarationControllerSpec.scala
- test/forms/ApplicationReferenceFormSpec.scala
- test/views/ApplicationReferenceViewSpec.scala
> SAR-8985: Application reference page & journey changes

- app/common/enums/VatRegStatus.scala
- app/connectors/VatRegistrationConnector.scala
- app/controllers/SubmissionInProgressController.scala
- app/controllers/SummaryController.scala
- app/services/SessionProfile.scala
- app/views/pages/SubmissionInProgress.scala.html
- conf/app.routes
- conf/messages
- it/controllers/SubmissionInProgressControllerISpec.scala
- it/controllers/SummaryControllerISpec.scala
- it/controllers/WelcomeControllerISpec.scala
- it/support/StubUtils.scala
- test/controllers/SummaryControllerSpec.scala
- test/utils/SessionProfileSpec.scala
- test/views/SubmissionInProgressViewSpec.scala
> SAR-8956 Added SubmissionInProgress page and refactored application status logic

- app/controllers/registration/applicant/IncorpIdController.scala
- app/models/external/soletraderid/SoleTraderIdJourneyConfig.scala
- it/controllers/registration/applicant/IncorpIdControllerISpec.scala
- test/controllers/registration/applicant/IncorpIdControllerSpec.scala
added new field to SoleTraderJourneyConfig and adjusted routing in IncorpIdController and it's ISpec
> SAR-8953 Updated SoleTraderIdJourneyConfig and IncorpIdController

- app/common/enums/AddressLookupJourneyIdentifier.scala
- app/controllers/registration/applicant/HomeAddressController.scala
- app/controllers/registration/applicant/PreviousAddressController.scala
- conf/app.routes
- conf/messages
- it/controllers/registration/applicant/HomeAddressControllerISpec.scala
- test/controllers/registration/applicant/HomeAddressControllerSpec.scala
- test/controllers/registration/applicant/PreviousAddressControllerSpec.scala
SAR-8994 [VRS-FE] Set up dynamic content for ALF according to spreadsheet
Set up dynamic content in AddressLookupFrontend for transactor
> SAR-8994 Set up dynamic content in AddressLookupFrontend for transactor

- app/controllers/ApplicationReferenceController.scala
- app/controllers/ManageRegistrationsController.scala
- app/controllers/WelcomeController.scala
- app/models/api/VatSchemeHeader.scala
- app/viewmodels/ManageRegistrationsBuilder.scala
- app/views/ManageRegistrations.scala.html
- conf/app.routes
- conf/messages
- it/connectors/VatRegistrationConnectorISpec.scala
- it/controllers/ManageRegistrationsControllerISpec.scala
- it/controllers/WelcomeControllerISpec.scala
- it/support/StubUtils.scala
- test/views/ManageRegistrationsViewSpec.scala
> SAR-9005: Manage registrations page

- app/controllers/registration/attachments/EmailCoverSheetController.scala
- app/controllers/registration/attachments/MultipleDocumentsRequiredController.scala
- app/controllers/registration/attachments/PostalCoverSheetController.scala
- app/controllers/registration/attachments/TransactorIdentityEvidenceRequiredController.scala
- app/views/attachments/EmailCoverSheet.scala.html
- app/views/attachments/MultipleDocumentsRequired.scala.html
- app/views/attachments/PostalCoverSheet.scala.html
- conf/messages
- it/controllers/registration/attachments/EmailCoverSheetControllerISpec.scala
- it/controllers/registration/attachments/MultipleDocumentsRequiredControllerISpec.scala
- it/controllers/registration/attachments/PostalCoverSheetControllerISpec.scala
- test/views/attachments/EmailCoverSheetViewSpec.scala
- test/views/attachments/MultipleDocumentsRequiredViewSpec.scala
- test/views/attachments/PostalCoverSheetViewSpec.scala
- test/views/attachments/TransactorIdentityEvidenceRequiredViewSpec.scala
> SAR-9024 Updated dynamic attachment pages to support transactor flow

- app/config/FrontendAppConfig.scala
- app/controllers/ContactPreferenceController.scala
- app/controllers/registration/sicandcompliance/LandAndPropertyController.scala
- app/featureswitch/core/config/FeatureSwitchingModule.scala
- app/forms/LandAndPropertyForm.scala
- app/models/SicAndCompliance.scala
- app/services/SicAndComplianceService.scala
- app/viewmodels/SummaryCheckYourAnswersBuilder.scala
- app/views/LandAndProperty.scala.html
- conf/app.routes
- conf/messages
- it/controllers/registration/sicandcompliance/LandAndPropertyControllerISpec.scala
- test/views/ApplicationSubmissionConfirmationViewSpec.scala
- test/views/BaseSelectors.scala
- test/views/IndividualAffinityKickOutViewSpec.scala
- test/views/LandAndPropertyViewSpec.scala
- test/views/VatRegViewSpec.scala
- test/views/returns/ZeroRatedSuppliesViewSpec.scala
> SAR-8958 Added land and property page

- app/controllers/registration/applicant/IndividualIdentificationController.scala
- conf/messages
- it/controllers/registration/applicant/IndividualIdentificationControllerISpec.scala
Optional field is added to config if user is transactor
> SAR-8954 Updated IndividualIdentificationController to add optional header to the journey config

- app/views/annual_costs_inclusive.scala.html
- app/views/apply_for_eori.scala.html
- app/views/contact_preference.scala.html
- app/views/frs_join.scala.html
- app/views/returns/aas_payment_method.scala.html
- app/views/returns/claim_refunds_view.scala.html
- app/views/returns/payment_frequency.scala.html
- app/views/returns/return_frequency_view.scala.html
- conf/messages
- test/views/AnnualCostsInclusiveViewSpec.scala
- test/views/ApplyForEoriViewSpec.scala
- test/views/ContactPreferenceViewSpec.scala
- test/views/JoinFrsViewSpec.scala
- test/views/returns/ClaimRefundsViewSpec.scala
- test/views/returns/LastMonthOfAccountingYearViewSpec.scala
- test/views/returns/PaymentFrequencyPageSpec.scala
- test/views/returns/PaymentMethodViewSpec.scala
- test/views/returns/ReturnFrequencyViewSpec.scala
SAR-8993 Update main journey page content for transactor
> SAR-8993 Update main journey page content for transactor

- app/controllers/registration/attachments/DocumentsRequiredController.scala
- app/controllers/registration/attachments/Vat5LRequiredController.scala
- app/views/attachments/Vat5LRequired.scala.html
- conf/app.routes
- conf/messages
- it/controllers/registration/attachments/DocumentsRequiredControllerISpec.scala
- it/controllers/registration/attachments/Vat5LRequiredControllerISpec.scala
- test/views/attachments/Vat5LRequiredViewSpec.scala
> SAR-9030 Added VAt5l attachment page

- app/views/annual_costs_inclusive.scala.html
- app/views/apply_for_eori.scala.html
- app/views/contact_preference.scala.html
- app/views/frs_join.scala.html
- app/views/returns/aas_payment_method.scala.html
- app/views/returns/claim_refunds_view.scala.html
- app/views/returns/payment_frequency.scala.html
- app/views/returns/return_frequency_view.scala.html
- conf/messages
- test/views/AnnualCostsInclusiveViewSpec.scala
- test/views/ApplyForEoriViewSpec.scala
- test/views/ContactPreferenceViewSpec.scala
- test/views/JoinFrsViewSpec.scala
- test/views/returns/ClaimRefundsViewSpec.scala
- test/views/returns/PaymentFrequencyPageSpec.scala
- test/views/returns/PaymentMethodViewSpec.scala
- test/views/returns/ReturnFrequencyViewSpec.scala
SAR-8993 [VRS-FE] Update main journey page content according to spreadsheet
**Bug fix** (delete as appropriate)
Remove the subheadings that were mistakenly added.
> SAR-8993 rollback mistakenly added subheadings

- app/controllers/registration/applicant/SoleTraderIdentificationController.scala
- it/controllers/registration/applicant/SoleTraderIdentificationControllerISpec.scala
- test/controllers/registration/applicant/SoleTraderIdentificationControllerSpec.scala
**New feature** 
Updated controller as well as unit test and integration test appropriately
> SAR-8955 Updated IndividualIdentificationController to check if the user is a transactor and if true add optional header

- a11y/fixtures/BaseA11yFixtures.scala
- a11y/helpers/A11ySpec.scala
- a11y/pages/ApplicationReferenceA11ySpec.scala
- a11y/pages/ManageRegistrationsA11ySpec.scala
- app/assets/javascripts/backLink.js
- app/views/layouts/layout.scala.html
- it/itutil/IntegrationSpecBase.scala
- project/AppDependencies.scala
- project/plugins.sbt
- test/common/MaskedStringConverterSpec.scala
- test/forms/ApplicantFormsSpec.scala
- test/forms/CompanyContactDetailsFormSpec.scala
- test/forms/EmailAddressFormSpec.scala
- test/forms/EmailPasscodeFormSpec.scala
- test/forms/TelephoneNumberFormSpec.scala
- test/forms/TransactorTelephoneFormSpec.scala
- test/forms/ZeroRatedSuppliesFormSpec.scala
- test/forms/validation/FormValidationSpec.scala
- test/helpers/FormInspectors.scala
- test/services/DateServiceSpec.scala
- test/testHelpers/FormInspectors.scala
> A11y plugin integration

- app/controllers/registration/returns/ClaimRefundsController.scala
- app/controllers/registration/returns/ReceiveGoodsNipController.scala
- it/controllers/registration/returns/ClaimRefundsControllerISpec.scala
- it/controllers/registration/returns/ReceiveGoodsNipControllerISpec.scala
- test/controllers/registration/returns/ClaimRefundsControllerSpec.scala
SAR-9097 [VRS-FE] Skip reg date page for TOGC/COLE
> SAR-9097 Skip reg date page for TOGC/COLE

- app/models/api/Address.scala
- test/models/api/AddressSpec.scala
> SAR-9192 Updated the ALF address guard to allow addresses with only one line

- app/views/ManageRegistrations.scala.html
- app/views/components/link.scala.html
- app/views/layouts/layout.scala.html
> Missing autocomplete styles

- app/config/FrontendAppConfig.scala
- app/connectors/UpscanConnector.scala
- app/services/UpscanService.scala
- conf/application.conf
- it/connectors/UpscanConnectorISpec.scala
- test/connectors/mocks/MockUpscanConnector.scala
- test/services/UpscanServiceSpec.scala
SAR-9234 update absolute redirect url in Upscan call
> SAR-9234 update absolute redirect url in Upscan call

- app/viewmodels/TransactorDetailsBlockBuilder.scala
- conf/messages
- test/viewmodels/TransactorDetailsBlockBuilderSpec.scala
> SAR-9240 Added TransactorDetailsBlockBuilder

- app/config/FrontendAppConfig.scala
- app/connectors/VatRegistrationConnector.scala
- app/controllers/ErrorController.scala
- app/services/VatRegistrationService.scala
- app/views/pages/error/SubmissionFailed.scala.html
- conf/app.routes
- conf/messages
- test/connectors/VatRegistrationConnectorSpec.scala
- test/controllers/ErrorControllerSpec.scala
- test/utils/SessionProfileSpec.scala
- test/views/pages/error/SubmissionFailedViewSpec.scala
> SAR-9300 Updated the BAD REQUEST submission failure page

- app/viewmodels/GrsSummaryBuilder.scala
- conf/messages
- test/fixtures/ApplicantDetailsFixtures.scala
- test/viewmodels/GrsSummaryBuilderSpec.scala
> SAR-9274: Added GRS Details Summary Block

- app/viewmodels/RegistrationDetailsBuilder.scala
- conf/messages
- test/fixtures/VatRegistrationFixture.scala
- test/viewmodels/RegistrationDetailsBuilderSpec.scala
> SAR-9277: Added Registration Details Summary list

- app/connectors/RegistrationApiConnector.scala
- it/connectors/RegistrationApiConnectorISpec.scala
- it/controllers/JourneyControllerISpec.scala
- it/support/StubUtils.scala
- test/connectors/mocks/MockRegistrationApiConnector.scala
- test/services/VatRegistrationServiceSpec.scala
[SAR-9315] [VRS-FE] Set up connector for new API
> SAR-9315 Set up connector for new registration collection API

- app/controllers/registration/returns/ReturnsController.scala
- app/models/external/BusinessEntity.scala
- app/services/ApplicantDetailsService.scala
- app/viewmodels/RegistrationDetailsSummaryBuilder.scala
- app/views/returns/mandatory_start_date_incorp_view.scala.html
- conf/messages
- test/controllers/ReturnsControllerSpec.scala
> SAR-9363 Updated how the calculated date option on regdate page works to fix cya and frs date selection

- app/controllers/registration/applicant/InternationalHomeAddressController.scala
- app/controllers/registration/sicandcompliance/SupplyWorkersController.scala
- app/controllers/registration/sicandcompliance/SupplyWorkersIntermediaryController.scala
- app/controllers/registration/sicandcompliance/WorkersController.scala
- app/forms/LabourComplianceForms.scala
- app/views/CaptureInternationalAddress.scala.html
- app/views/labour/intermediary_supply.scala.html
- app/views/labour/supply_workers.scala.html
- app/views/labour/workers.scala.html
- conf/messages
- it/controllers/SicAndComplianceControllerISpec.scala
- it/controllers/registration/sicandcompliance/SupplyWorkersControllerISpec.scala
- it/controllers/registration/sicandcompliance/SupplyWorkersIntermediaryControllerISpec.scala
- it/controllers/registration/sicandcompliance/WorkersControllerISpec.scala
- test/controllers/registration/sicandcompliance/SupplyWorkersControllerSpec.scala
- test/controllers/registration/sicandcompliance/SupplyWorkersIntermediaryControllerSpec.scala
- test/controllers/registration/sicandcompliance/WorkersControllerSpec.scala
- test/views/CaptureInternationalAddressViewSpec.scala
- test/views/IntermediarySupplyViewSpec.scala
- test/views/StoringGoodsViewSpec.scala
- test/views/SupplyWorkersViewSpec.scala
- test/views/WorkersViewSpec.scala
- test/views/returns/SendEUGoodsViewSpec.scala
Headings and errors have been updated to reflect whether or not the user is a third party transactor
> SAR-9316 Updated Headings And Errors With Dynamic Third Party Transactor Content

- conf/messages
- test/views/StoringGoodsViewSpec.scala
**Bug fix**
Slight correction to the wording of the heading on the storing goods for dispatch view
> SAR-9316 Storing Goods Page Wording Adjustment

- app/controllers/registration/otherbusinessinvolvements/ObiIndexValidation.scala
- app/controllers/registration/otherbusinessinvolvements/OtherBusinessNameController.scala
- app/forms/otherbusinessinvolvements/OtherBusinessNameForm.scala
- app/models/OtherBusinessInvolvement.scala
- app/services/OtherBusinessInvolvementsService.scala
- app/views/otherbusinessinvolvements/OtherBusinessName.scala.html
- conf/app.routes
- conf/messages
- it/controllers/registration/otherbusinessinvolvements/OtherBusinessNameControllerISpec.scala
- it/fixtures/ITRegistrationFixtures.scala
- it/support/StubUtils.scala
- test/connectors/mocks/MockRegistrationApiConnector.scala
- test/forms/otherbusinessinvolvements/OtherBusinessNameFormSpec.scala
- test/services/OtherBusinessInvolvementsServiceSpec.scala
- test/views/otherbusinessinvolvements/BusinessNameViewSpec.scala
> SAR-9382 Added OtherBusinessInvolvementsService and other business name page

- app/models/FlatRateModel.scala
- app/services/FlatRateService.scala
- test/controllers/registration/flatratescheme/JoinFlatRateSchemeControllerSpec.scala
- test/services/FlatRateServiceSpec.scala
> SAR-9379: Fix FRS exception

- app/controllers/registration/otherbusinessinvolvements/CaptureVrnController.scala
- app/forms/constraints/VrnConstraints.scala
- app/forms/otherbusinessinvolvements/CaptureVrnForm.scala
- app/views/otherbusinessinvolvements/CaptureVrn.scala.html
- conf/app.routes
- conf/messages
- it/controllers/registration/otherbusinessinvolvements/CaptureVrnControllerISpec.scala
- test/forms/otherbusinessinvolvements/CaptureVrnFormSpec.scala
- test/views/otherbusinessinvolvements/CaptureVrnViewSpec.scala
- test/views/otherbusinessinvolvements/OtherBusinessNameViewSpec.scala
> SAR-9405 Added Capture Other Business VRN page

- app/controllers/registration/otherbusinessinvolvements/CaptureVrnController.scala
- app/controllers/registration/otherbusinessinvolvements/OtherBusinessActivelyTradingController.scala
- app/forms/otherbusinessinvolvements/OtherBusinessActivelyTradingForm.scala
- app/views/otherbusinessinvolvements/OtherBusinessActivelyTradingView.scala.html
- conf/app.routes
- conf/messages
- it/controllers/registration/otherbusinessinvolvements/OtherBusinessActivelyTradingControllerISpec.scala
- test/views/otherbusinessinvolvements/OtherBusinessActivelyTradingViewSpec.scala
> SAR-9384: Added Other Business Actively Trading page and tests

- app/controllers/registration/otherbusinessinvolvements/HaveVatNumberController.scala
- app/forms/otherbusinessinvolvements/HaveVatNumberForm.scala
- app/views/otherbusinessinvolvements/HaveVatNumber.scala.html
- conf/app.routes
- conf/messages
- it/controllers/registration/otherbusinessinvolvements/HaveVatNumberControllerISpec.scala
- it/fixtures/ITRegistrationFixtures.scala
- test/forms/otherbusinessinvolvements/HaveVatNumberFormSpec.scala
- test/forms/otherbusinessinvolvements/OtherBusinessNameFormSpec.scala
- test/views/otherbusinessinvolvements/HaveVatNumberViewSpec.scala
[SAR-9383][VRS-FE] Create new page `Do you have a VRN?` & store using new API
> SAR-9383 add new page 'Do you have VRN?' and store it's value

- app/controllers/registration/otherbusinessinvolvements/HaveVatNumberController.scala
- app/controllers/registration/otherbusinessinvolvements/OtherBusinessActivelyTradingController.scala
- app/controllers/registration/otherbusinessinvolvements/OtherBusinessCheckAnswersController.scala
- app/controllers/registration/otherbusinessinvolvements/OtherBusinessNameController.scala
- app/views/otherbusinessinvolvements/OtherBusinessCheckAnswers.scala.html
- conf/app.routes
- conf/messages
- it/controllers/registration/otherbusinessinvolvements/HaveVatNumberControllerISpec.scala
- it/controllers/registration/otherbusinessinvolvements/OtherBusinessActivelyTradingControllerISpec.scala
- it/controllers/registration/otherbusinessinvolvements/OtherBusinessCheckAnswersControllerISpec.scala
- it/controllers/registration/otherbusinessinvolvements/OtherBusinessNameControllerISpec.scala
- test/views/VatRegViewSpec.scala
- test/views/otherbusinessinvolvements/OtherBusinessCheckAnswersSpec.scala
> SAR-9385: OBI Check Answers page

- app/config/FrontendAppConfig.scala
- app/controllers/registration/otherbusinessinvolvements/CaptureUtrController.scala
- app/controllers/registration/otherbusinessinvolvements/HasUtrController.scala
- app/controllers/registration/otherbusinessinvolvements/OtherBusinessCheckAnswersController.scala
- app/forms/otherbusinessinvolvements/CaptureUtrForm.scala
- app/forms/otherbusinessinvolvements/HasUtrForm.scala
- app/services/OtherBusinessInvolvementsService.scala
- app/views/OtherBusinessInvolvement.scala.html
- app/views/otherbusinessinvolvements/CaptureUtr.scala.html
- app/views/otherbusinessinvolvements/HasUtr.scala.html
- app/views/otherbusinessinvolvements/OtherBusinessCheckAnswers.scala.html
- conf/app.routes
- conf/messages
- it/controllers/registration/otherbusinessinvolvements/CaptureUtrControllerISpec.scala
- it/controllers/registration/otherbusinessinvolvements/HasUtrControllerISpec.scala
- it/support/StubUtils.scala
- test/forms/otherbusinessinvolvements/CaptureUtrFormSpec.scala
- test/forms/otherbusinessinvolvements/HasUtrFormSpec.scala
- test/views/otherbusinessinvolvements/CaptureUtrViewSpec.scala
- test/views/otherbusinessinvolvements/HasUtrViewSpec.scala
- test/views/otherbusinessinvolvements/OtherBusinessCheckAnswersSpec.scala
> SAR-9446/SAR-9447 Added UTR pages and updated OBI Service to clean up invalid data

- app/connectors/UpscanConnector.scala
- app/controllers/test/FileUploadController.scala
- app/models/api/AttachmentType.scala
- app/services/UpscanService.scala
- it/connectors/UpscanConnectorISpec.scala
- test/connectors/mocks/MockUpscanConnector.scala
- test/services/UpscanServiceSpec.scala
> SAR-9494 Updated the store upscan reference api

- app/models/api/VatScheme.scala
- app/models/view/Summary.scala
- app/viewmodels/AboutTheBusinessSummaryBuilder.scala
- app/viewmodels/ApplicantDetailsSummaryBuilder.scala
- app/viewmodels/EligibilitySummaryBuilder.scala
- app/viewmodels/GrsSummaryBuilder.scala
- app/viewmodels/RegistrationDetailsSummaryBuilder.scala
- app/viewmodels/SummaryCheckYourAnswersBuilder.scala
- app/viewmodels/TransactorDetailsSummaryBuilder.scala
- conf/messages
- test/viewmodels/AboutTheBusinessSummaryBuilderSpec.scala
- test/viewmodels/ApplicantDetailsSummaryBuilderSpec.scala
- test/viewmodels/EligibilitySummaryBuilderSpec.scala
- test/viewmodels/GrsSummaryBuilderSpec.scala
- test/viewmodels/RegistrationDetailsSummaryBuilderSpec.scala
- test/viewmodels/SummaryCheckYourAnswersBuilderSpec.scala
- test/viewmodels/TransactorDetailsSummaryBuilderSpec.scala
> SAR-9461: Add OBI to CYA

- app/views/business/PartnershipName.scala.html
**Bug fix**
Update partnership controller form to address the accessibility failure
> SAR-9520|Update partnership controller label to address accessibility failure

- app/config/AddressLookupConfiguration.scala
- app/controllers/business/PpobAddressController.scala
- app/services/AddressLookupService.scala
- it/connectors/AddressLookupConnectorISpec.scala
- test/controllers/applicant/HomeAddressControllerSpec.scala
- test/controllers/applicant/PreviousAddressControllerSpec.scala
- test/controllers/business/PpobAddressControllerSpec.scala
- test/models/external/addresslookup/AddressLookupInitializationModelSpec.scala
- test/services/AddressLookupServiceSpec.scala
> SAR-9533: Send UK mode flag as TRUE for PPOB address

- app/config/FrontendAppConfig.scala
- app/connectors/AttachmentsConnector.scala
- app/connectors/UpscanConnector.scala
- app/controllers/fileupload/DocumentUploadSummaryController.scala
- app/controllers/fileupload/RemoveUploadedDocumentController.scala
- app/forms/RemoveUploadedDocumentForm.scala
- app/services/AttachmentsService.scala
- app/services/UpscanService.scala
- app/viewmodels/DocumentUploadSummaryRow.scala
- app/views/components/DocumentUploadSummaryTable.scala.html
- app/views/fileUpload/DocumentUploadSummary.scala.html
- app/views/fileUpload/RemoveUploadedDocument.scala.html
- conf/app.routes
- conf/messages
- it/connectors/UpscanConnectorISpec.scala
- it/controllers/fileupload/DocumentUploadSummaryControllerSpec.scala
- it/controllers/fileupload/RemoveUploadedDocumentControllerSpec.scala
- it/support/StubUtils.scala
- test/connectors/AttachmentsConnectorSpec.scala
- test/connectors/mocks/MockAttachmentsConnector.scala
- test/connectors/mocks/MockUpscanConnector.scala
- test/services/AttachmentsServiceSpec.scala
- test/services/UpscanServiceSpec.scala
- test/views/fileupload/DocumentUploadSummaryViewSpec.scala
- test/views/fileupload/RemoveUploadedDocumentViewSpec.scala
[[SAR-9490](https://jira.tools.tax.service.gov.uk/browse/SAR-9490)] New page to show upload summary page
> SAR-9490|Add file upload summary page

- app/assets/javascripts/uploadingDocument.js
- app/assets/stylesheets/application.scss
- app/config/FrontendAppConfig.scala
- app/controllers/fileupload/UploadingDocumentController.scala
- app/services/UpscanService.scala
- app/views/fileUpload/UploadingDocument.scala.html
- conf/app.routes
- conf/messages
- it/controllers/applicant/EmailVerifiedControllerISpec.scala
- it/controllers/fileupload/UploadingDocumentControllerISpec.scala
- it/support/AppAndStubs.scala
- it/support/SessionCookieBaker.scala
- test/services/UpscanServiceSpec.scala
- test/views/attachments/UploadingDocumentViewSpec.scala
[SAR-9489][VRS-FE] Add checking file page
> SAR-9489 add uploading document page

- app/forms/TelephoneNumberForm.scala
- app/forms/TransactorTelephoneForm.scala
- test/forms/TransactorTelephoneFormSpec.scala
[SAR-9539][VRS-FE] Update how trimming is applied in the form, potentially investigate if there are forms with an identical issue
**Bug fix**
> SAR-9539 remove spaces from telephone number

- app/config/FrontendAppConfig.scala
- app/connectors/UpscanConnector.scala
- app/controllers/attachments/AttachmentMethodController.scala
- app/controllers/test/UpscanStubController.scala
- app/featureswitch/core/config/FeatureSwitchingModule.scala
- app/forms/AttachmentMethodForm.scala
- app/services/UpscanService.scala
- app/views/attachments/ChooseAttachmentMethod.scala.html
- app/views/bankdetails/no_uk_bank_account.scala.html
- conf/messages
- it/connectors/UpscanConnectorISpec.scala
- it/controllers/attachments/AttachmentMethodControllerISpec.scala
- it/support/StubUtils.scala
- test/connectors/mocks/MockUpscanConnector.scala
- test/forms/AttachmentMethodFormSpec.scala
- test/services/UpscanServiceSpec.scala
- test/views/attachments/ChooseAttachmentMethodViewSpec.scala
> SAR-9487: Added Upload Documents FS and tests

- app/assets/javascripts/uploadingDocument.js
- app/connectors/UpscanConnector.scala
- app/controllers/fileupload/DocumentUploadErrorController.scala
- app/controllers/fileupload/UploadDocumentController.scala
- app/controllers/fileupload/UploadingDocumentController.scala
- app/views/fileupload/UploadDocument.scala.html
- app/views/fileupload/UploadDocumentError.scala.html
- conf/app.routes
- conf/messages
- it/connectors/UpscanConnectorISpec.scala
- it/controllers/fileupload/UploadDocumentControllerISpec.scala
- it/controllers/fileupload/UploadingDocumentControllerISpec.scala
- test/views/fileupload/UploadDocumentViewSpec.scala
Add error handling for upscan attachments
> SAR-9588 | Add error handling for digital attachments

- app/models/BusinessContact.scala
- app/models/CompanyContactDetails.scala
- app/services/BusinessContactService.scala
- app/viewmodels/AboutTheBusinessSummaryBuilder.scala
- it/controllers/business/BusinessContactDetailsControllerISpec.scala
- it/fixtures/ITRegistrationFixtures.scala
- test/fixtures/VatRegistrationFixture.scala
- test/forms/CompanyContactDetailsFormSpec.scala
- test/models/BusinessContactSpec.scala
- test/models/CompanyContactDetailsSpec.scala
- test/services/BusinessContactServiceSpec.scala
[SAR-9620] [VRS-FE] Update BusinessContact model and service
Add email, telephone number, has website and website address to business contact model.
> SAR-9620 Update BusinessContact model and service

- app/viewmodels/AboutTheBusinessSummaryBuilder.scala
- test/controllers/business/BusinessContactControllerSpec.scala
- test/fixtures/VatRegistrationFixture.scala
- test/viewmodels/AboutTheBusinessSummaryBuilderSpec.scala
[SAR-9622](https://jira.tools.tax.service.gov.uk/browse/SAR-9622)
Update check your answers, summary, page to use both old and new business contact model.
> SAR-9622| Update summary page to use new business contact model

- app/assets/javascripts/uploadingDocument.js
- app/controllers/fileupload/DocumentUploadTypeErrorController.scala
- app/controllers/fileupload/UploadingDocumentController.scala
- app/models/external/upscan/UpscanDetails.scala
- app/services/UpscanService.scala
- app/views/fileupload/UploadDocumentTypeError.scala.html
- conf/app.routes
- conf/messages
- it/controllers/fileupload/DocumentUploadErrorControllerISpec.scala
- it/controllers/fileupload/DocumentUploadTypeErrorControllerISpec.scala
- it/controllers/fileupload/UploadingDocumentControllerISpec.scala
- test/services/UpscanServiceSpec.scala
- test/views/fileupload/DocumentUploadErrorViewSpec.scala
- test/views/fileupload/DocumentUploadTypeErrorViewSpec.scala
> SAR-9657 Added async error page for wrong filetype, updated generic async error page

- app/controllers/otherbusinessinvolvements/OtherBusinessInvolvementController.scala
- app/services/OtherBusinessInvolvementsService.scala
- it/controllers/otherbusinessinvolvements/RemoveOtherBusinessControllerISpec.scala
- it/controllers/sicandcompliance/OtherBusinessInvolvementControllerISpec.scala
- it/support/StubUtils.scala
- test/connectors/mocks/MockRegistrationApiConnector.scala
- test/services/OtherBusinessInvolvementsServiceSpec.scala
> Remove OBI list if user changes obi answer to No

- app/controllers/business/HasWebsiteController.scala
- app/forms/HasWebsiteForm.scala
- app/services/BusinessContactService.scala
- app/viewmodels/AboutTheBusinessSummaryBuilder.scala
- app/views/business/HasWebsite.scala.html
- conf/app.routes
- conf/messages
- it/controllers/business/HasWebsiteControllerISpec.scala
- test/fixtures/VatRegistrationFixture.scala
- test/services/BusinessContactServiceSpec.scala
- test/viewmodels/AboutTheBusinessSummaryBuilderSpec.scala
- test/views/business/HasWebsiteViewSpec.scala
SAR-9661 Add have website page + CYA
Added the Have Website page to check if the user's business has a website before proceeding to the website capture page + added the data to check your answers section
> SAR-9661 Add have website page + CYA

- app/config/AddressLookupConfiguration.scala
- app/models/external/addresslookup/AddressLookupLanguageModel.scala
- app/models/external/addresslookup/messages/AddressMessagesModel.scala
- app/models/external/addresslookup/messages/InternationalAddressMessagesModel.scala
- conf/messages
- test/fixtures/AddressLookupConstants.scala
- test/models/external/addresslookup/AddressLookupInitializationModelSpec.scala
[SAR-9652](https://jira.tools.tax.service.gov.uk/browse/SAR-9613)
> SAR-9652 | custom content for ALF non UK pages with international key

- app/controllers/business/BusinessWebsiteAddressController.scala
- app/forms/BusinessWebsiteAddressForm.scala
- app/views/business/BusinessWebsiteAddress.scala.html
- conf/app.routes
- conf/messages
- it/controllers/business/BusinessWebsiteAddressControllerISpec.scala
- test/forms/BusinessWebsiteAddressFormSpec.scala
- test/views/business/BusinessEmailViewSpec.scala
- test/views/business/BusinessWebsiteAddressViewSpec.scala
Also made a slight change to BusinessEmail for consistency
> SAR-9663 Business Website Address page added

- app/controllers/applicant/PreviousAddressController.scala
- app/forms/OfficerForms.scala
- conf/messages
- test/forms/ApplicantFormsSpec.scala
- test/views/applicant/PreviousAddressViewSpec.scala
- test/views/errors/SubmissionRetryableViewSpec.scala
- test/views/returns/PaymentFrequencyPageSpec.scala
- test/views/returns/PaymentMethodViewSpec.scala
> SAR-9674: Updated messages for 3rd party

- app/forms/TelephoneNumberForm.scala
- app/forms/TransactorTelephoneForm.scala
- app/forms/constraints/TransactorTelephoneNumberConstraints.scala
- app/views/applicant/capture_telephone_number.scala.html
- app/views/transactor/TelephoneNumber.scala.html
- app/views/transactor/TransactorCaptureEmailAddress.scala.html
- conf/messages
- test/forms/TelephoneNumberFormSpec.scala
- test/forms/TransactorTelephoneFormSpec.scala
> SAR-9611: Updated error validation content, regex and tests for Transactor & Applicant Telephone Number forms

- app/forms/BusinessWebsiteAddressForm.scala
- conf/messages
- test/forms/BusinessWebsiteAddressFormSpec.scala
[SAR-9715] Update Business Website Address maximum length
> SAR-9715 update website address validation with max char constraint

- app/connectors/VatRegistrationConnector.scala
- app/controllers/returns/VatRegStartDateResolverController.scala
- app/models/RegistrationReason.scala
- app/services/ReturnsService.scala
- app/services/VatRegistrationService.scala
- it/controllers/returns/VatRegStartDateResolverControllerISpec.scala
- test/connectors/VatRegistrationConnectorSpec.scala
- test/controllers/returns/ReturnsControllerSpec.scala
- test/services/ReturnsServiceSpec.scala
> SAR-9737 Updated reg reason to support intending trader, cleaned up some old code

- app/services/BankAccountDetailsService.scala
- test/services/BankAccountDetailsServiceSpec.scala
[SAR-9754](https://jira.tools.tax.service.gov.uk/browse/SAR-9754)
**Bug fix**
Fix for CYA edit business details flow to pre-populate user reason for no bank details available during reg.
> SAR-9754 | Fix no-bankaccount pre-pop with CYA edit journey flow

- app/controllers/TradingNameResolverController.scala
- app/featureswitch/core/config/FeatureSwitchingModule.scala
- it/controllers/TradingNameResolverControllerISpec.scala
Remove shortOrgName feature switch
> SAR-9773 | Remove shortOrgName feature switch

- a11y/pages/applicant/CaptureEmailAddressA11ySpec.scala
- a11y/pages/applicant/CaptureEmailPasscodeA11ySpec.scala
- a11y/pages/applicant/CaptureTelephoneNumberA11ySpec.scala
- a11y/pages/applicant/EmailVerifiedA11ySpec.scala
- a11y/pages/applicant/FormerNameA11ySpec.scala
- a11y/pages/applicant/FormerNameCaptureA11ySpec.scala
- a11y/pages/applicant/FormerNameDateA11ySpec.scala
- a11y/pages/applicant/LeadPartnerEntityTypeA11ySpec.scala
- a11y/pages/applicant/PreviousAddressA11ySpec.scala
- a11y/pages/applicant/RoleInTheBusinessA11ySpec.scala
- it/controllers/applicant/InternationalHomeAddressControllerISpec.scala
- it/controllers/attachments/AttachmentMethodControllerISpec.scala
- it/controllers/attachments/DocumentsRequiredControllerISpec.scala
- it/controllers/attachments/TransactorIdentityEvidenceRequiredControllerISpec.scala
- it/controllers/attachments/Vat51RequiredControllerISpec.scala
- it/controllers/fileupload/UploadingDocumentControllerISpec.scala
- it/controllers/flatratescheme/JoinFlatRateSchemeControllerISpec.scala
- it/controllers/otherbusinessinvolvements/ObiSummaryControllerISpec.scala
- it/controllers/returns/ClaimRefundsControllerISpec.scala
- it/controllers/transactor/TransactorIdentificationControllerISpec.scala
- it/fixtures/ITRegistrationFixtures.scala
[SAR-9799](https://jira.tools.tax.service.gov.uk/browse/SAR-9799)
**Tech debt**
- Add a11y test coverage to applicant details views
- Additional controller specs to improve controllers coverage
> SAR-9799 | A11y specs for applicant details views

- app/controllers/bankdetails/NoUKBankAccountController.scala
- app/controllers/bankdetails/UkBankAccountDetailsController.scala
- app/controllers/returns/ClaimRefundsController.scala
- app/controllers/returns/PaymentMethodController.scala
- app/controllers/returns/ReturnsController.scala
- app/controllers/returns/VatExemptionController.scala
- app/viewmodels/RegistrationDetailsSummaryBuilder.scala
- it/controllers/bankdetails/NoUKBankAccountControllerISpec.scala
- it/controllers/bankdetails/UKBankAccountDetailsControllerISpec.scala
- it/controllers/returns/ClaimRefundsControllerISpec.scala
- it/controllers/returns/PaymentMethodControllerISpec.scala
- it/controllers/returns/VatExemptionControllerISpec.scala
- test/controllers/returns/ReturnsControllerSpec.scala
- test/viewmodels/RegistrationDetailsSummaryBuilderSpec.scala
SAR-9794 move bank account capture after repayments/exemption question
> SAR-9794 move bank account capture after repayments/exemption question

- app/services/BusinessService.scala
- app/services/S4LService.scala
- test/services/BusinessServiceSpec.scala
[SAR-9926](https://jira.tools.tax.service.gov.uk/browse/SAR-9926)
This reverts commit 42fceb8307897e1e699865e1b7ebdcc6fa9aeb53. (tmp handler to manage business from old to new models during release)
> Revert "temporary change to handle intermediate state change during release"

- app/controllers/ApplicationReferenceController.scala
- it/controllers/ApplicationReferenceControllerISpec.scala
> SAR-9867-VSR: Fix to app ref page to support mongo migration

- app/config/FrontendAppConfig.scala
- app/controllers/attachments/DocumentsRequiredController.scala
- app/controllers/attachments/Vat1TRRequiredController.scala
- app/viewmodels/UploadDocumentHintBuilder.scala
- app/views/attachments/EmailCoverSheet.scala.html
- app/views/attachments/MultipleDocumentsRequired.scala.html
- app/views/attachments/PostalCoverSheet.scala.html
- app/views/attachments/Vat1TRRequired.scala.html
- conf/app.routes
- conf/messages
- it/controllers/attachments/DocumentsRequiredControllerISpec.scala
- it/controllers/attachments/Vat1TRRequiredControllerISpec.scala
- test/viewmodels/UploadDocumentHintBuilderSpec.scala
- test/views/attachments/EmailCoverSheetViewSpec.scala
- test/views/attachments/MultipleDocumentsRequiredViewSpec.scala
- test/views/attachments/PostalCoverSheetViewSpec.scala
- test/views/attachments/Vat1TRRequiredViewSpec.scala
- test/views/attachments/Vat5LRequiredViewSpec.scala
Add support for VAT1TR attachment and updates to relevant pages
> SAR-9871 Relevant form changes for VAT1TR attachment.

- app/controllers/JourneyController.scala
- app/controllers/TaskListController.scala
- app/controllers/applicant/IncorpIdController.scala
- app/controllers/applicant/MinorEntityIdController.scala
- app/controllers/applicant/PartnershipIdController.scala
- app/controllers/applicant/SoleTraderIdentificationController.scala
- app/models/api/VatScheme.scala
- app/viewmodels/ManageRegistrationsBuilder.scala
- app/viewmodels/tasklist/RegistrationReasonTaskList.scala
- app/viewmodels/tasklist/TaskListRowBuilder.scala
- app/viewmodels/tasklist/VerifyBusinessTaskList.scala
- app/views/components/TaskListRow.scala.html
- conf/messages
- it/controllers/JourneyControllerISpec.scala
- it/controllers/TaskListControllerISpec.scala
- it/controllers/applicant/IncorpIdControllerISpec.scala
- it/controllers/applicant/MinorEntityIdControllerISpec.scala
- it/controllers/applicant/PartnershipIdControllerISpec.scala
- it/controllers/applicant/PersonalDetailsValidationControllerISpec.scala
- it/controllers/applicant/SoleTraderIdentificationControllerISpec.scala
- test/viewmodels/taslkist/TaskListRowBuilderSpec.scala
- test/viewmodels/taslkist/VerifyBusinessTaskListSpec.scala
> SAR-9876: Add verify business section and business info row to Task List

- app/forms/BusinessWebsiteAddressForm.scala
- app/services/VatApplicationService.scala
- test/services/VatApplicationServiceSpec.scala
> SAR-9957 Removed fallback S4L handling for vatApplication, fixed website regex

- app/controllers/TaskListController.scala
- app/controllers/applicant/PartnershipIdController.scala
- app/viewmodels/tasklist/AboutYouTaskList.scala
- conf/messages
- it/controllers/TaskListControllerISpec.scala
- it/controllers/applicant/PartnershipIdControllerISpec.scala
- test/viewmodels/taslkist/AboutYouTaskListSpec.scala
[SAR-9967](https://jira.tools.tax.service.gov.uk/browse/SAR-9967)
Add new "About you" task list section and include row for  "Lead partner details"
> SAR-9967 | Lead partner details row in About you task list section

- a11y/pages/applicant/CaptureEmailPasscodeA11ySpec.scala
- app/connectors/RequestEmailVerificationPasscodeConnector.scala
- app/controllers/applicant/CaptureEmailPasscodeController.scala
- app/controllers/transactor/TransactorCaptureEmailPasscodeController.scala
- app/models/external/RequestEmailPasscodeResult.scala
- app/views/applicant/capture_email_passcode.scala.html
- conf/app.routes
- conf/messages
- it/controllers/applicant/CaptureEmailPasscodeControllerISpec.scala
- it/controllers/transactor/TransactorCaptureEmailPasscodeControllerISpec.scala
- test/views/applicant/CaptureEmailPasscodeViewSpec.scala
> SAR-9976 Updated email passcode page with extra content and links

- app/controllers/applicant/CaptureTelephoneNumberController.scala
- app/controllers/transactor/TransactorEmailAddressVerifiedController.scala
- app/viewmodels/tasklist/AboutYouTaskList.scala
- app/viewmodels/tasklist/AboutYouTransactorTaskList.scala
- conf/messages
- it/controllers/TaskListControllerISpec.scala
- it/controllers/applicant/CaptureTelephoneNumberControllerISpec.scala
- it/controllers/transactor/TransactorEmailAddressVerifiedControllerISpec.scala
- test/viewmodels/taslkist/AboutYouTaskListSpec.scala
- test/viewmodels/taslkist/AboutYouTransactorTaskListSpec.scala
[SAR-9978](https://jira.tools.tax.service.gov.uk/browse/SAR-9978) 
Add applicant/transactor contact details to AboutYou/AboutTheBusinessContact section of tasklist
> SAR-9978 | Include Contact details in AboutYou section of tasklist

- app/controllers/TaskListController.scala
- app/controllers/business/ContactPreferenceController.scala
- app/viewmodels/tasklist/AboutTheBusinessTaskList.scala
- conf/messages
- it/controllers/business/ContactPreferenceControllerISpec.scala
- test/viewmodels/taslkist/AboutTheBusinessTaskListSpec.scala
> SAR-9979 Added first about the business tasklist row

- app/controllers/business/SupplyWorkersIntermediaryController.scala
- app/controllers/business/WorkersController.scala
- app/services/BusinessService.scala
- app/viewmodels/tasklist/AboutTheBusinessTaskList.scala
- app/viewmodels/tasklist/AboutYouTaskList.scala
- conf/messages
- it/controllers/TaskListControllerISpec.scala
- it/controllers/business/SupplyWorkersIntermediaryControllerISpec.scala
- it/controllers/business/WorkersControllerISpec.scala
- test/viewmodels/taslkist/AboutTheBusinessTaskListSpec.scala
- test/viewmodels/taslkist/AboutYouTaskListSpec.scala
- test/viewmodels/taslkist/AboutYouTransactorTaskListSpec.scala
[SAR-9980](https://jira.tools.tax.service.gov.uk/browse/SAR-9980)
- Add BusinessActivities row to AboutTheBusiness tasklist section
> SAR-9980 | Business Activities section row in About the business tasklist

- app/controllers/business/SicController.scala
- app/controllers/test/SicStubController.scala
- app/viewmodels/tasklist/AboutYouTaskList.scala
- it/controllers/SicControllerISpec.scala
[SAR-10041](https://jira.tools.tax.service.gov.uk/browse/SAR-10041)
Fix business activities flow for non-compliance SIC code to redirect to TaskList rather than OBI
> SAR-10041 | Fix business activities tasklist flow for non-compliance SIC code selection

- app/controllers/otherbusinessinvolvements/ObiSummaryController.scala
- app/controllers/otherbusinessinvolvements/OtherBusinessInvolvementController.scala
- app/viewmodels/tasklist/AboutTheBusinessTaskList.scala
- conf/messages
- it/controllers/TaskListControllerISpec.scala
- it/controllers/business/OtherBusinessInvolvementControllerISpec.scala
- it/controllers/otherbusinessinvolvements/ObiSummaryControllerISpec.scala
- test/connectors/FlatRateSchemeConnectorSpec.scala
- test/fixtures/VatRegistrationFixture.scala
- test/viewmodels/tasklist/AboutTheBusinessTaskListSpec.scala
- test/viewmodels/tasklist/AboutYouTaskListSpec.scala
- test/viewmodels/tasklist/AboutYouTransactorTaskListSpec.scala
- test/viewmodels/tasklist/VerifyBusinessTaskListSpec.scala
SAR-9924 Create 'Other business involvements' task list row in 'About the business' section
> SAR-9924 Create 'Other business involvements' task list row in 'About the business' section

- app/controllers/TradingNameResolverController.scala
- app/controllers/applicant/CaptureTelephoneNumberController.scala
- app/controllers/business/SicController.scala
- app/controllers/business/SupplyWorkersIntermediaryController.scala
- app/controllers/business/WorkersController.scala
- app/controllers/otherbusinessinvolvements/ObiSummaryController.scala
- app/controllers/otherbusinessinvolvements/OtherBusinessInvolvementController.scala
- app/controllers/test/SicStubController.scala
- app/viewmodels/tasklist/AboutTheBusinessTaskList.scala
- conf/app.routes
- it/controllers/SicControllerISpec.scala
- it/controllers/TradingNameResolverControllerISpec.scala
- it/controllers/applicant/CaptureTelephoneNumberControllerISpec.scala
- it/controllers/business/OtherBusinessInvolvementControllerISpec.scala
- it/controllers/business/SupplyWorkersIntermediaryControllerISpec.scala
- it/controllers/business/WorkersControllerISpec.scala
- it/controllers/otherbusinessinvolvements/ObiSummaryControllerISpec.scala
- test/controllers/TradingNameResolverControllerSpec.scala
- test/controllers/applicant/CaptureTelephoneNumberControllerSpec.scala
- test/controllers/business/SicControllerSpec.scala
- test/controllers/business/SupplyWorkersIntermediaryControllerSpec.scala
- test/controllers/business/WorkersControllerSpec.scala
- test/viewmodels/tasklist/AboutTheBusinessTaskListSpec.scala
> SAR-9971 Removed extra redirect handling for Trading name

- app/viewmodels/tasklist/AboutTheBusinessTaskList.scala
- test/viewmodels/tasklist/AboutTheBusinessTaskListSpec.scala
SAR-10059 Redirect to BOI summary page when one or more obi entries exist
> SAR-10059 Redirect to BOI summary page when one or more obi entries exist

- app/controllers/TaskListController.scala
- app/controllers/vatapplication/ClaimRefundsController.scala
- app/controllers/vatapplication/DispatchFromWarehouseController.scala
- app/controllers/vatapplication/StoringGoodsController.scala
- app/controllers/vatapplication/VatExemptionController.scala
- app/controllers/vatapplication/WarehouseNameController.scala
- app/viewmodels/tasklist/VatRegistrationTaskList.scala
- conf/messages
- it/controllers/TaskListControllerISpec.scala
- it/controllers/vatapplication/DispatchFromWarehouseControllerISpec.scala
- it/controllers/vatapplication/StoringGoodsControllerISpec.scala
- test/viewmodels/tasklist/VatRegistrationTaskListSpec.scala
[SAR-10040](https://jira.tools.tax.service.gov.uk/browse/SAR-10040)
Add new task list section for "VAT registration" and include first row for "Goods and services"
> SAR-10040 | New VAT registration section with Goods and services row

- app/views/vatapplication/apply_for_eori.scala.html
- conf/messages
- test/views/vatapplication/ApplyForEoriViewSpec.scala
[SAR-10056](https://jira.tools.tax.service.gov.uk/browse/SAR-10056)
Update EORI page content
> SAR-10056 | Update EORI page content

- app/controllers/TaskListController.scala
- app/controllers/bankdetails/NoUKBankAccountController.scala
- app/controllers/bankdetails/UkBankAccountDetailsController.scala
- app/viewmodels/tasklist/VatRegistrationTaskList.scala
- conf/messages
- it/controllers/TaskListControllerISpec.scala
- it/controllers/bankdetails/NoUKBankAccountControllerISpec.scala
- it/controllers/bankdetails/UKBankAccountDetailsControllerISpec.scala
- test/fixtures/VatRegistrationFixture.scala
- test/viewmodels/tasklist/VatRegistrationTaskListSpec.scala
> SAR-10042: Added Bank Account Details row to Task List and updated tests

- app/connectors/AttachmentsConnector.scala
- it/connectors/AttachmentsConnectorISpec.scala
[SAR-10107](https://jira.tools.tax.service.gov.uk/browse/SAR-10107)
> SAR-10107 | Clean up task for attachment list lookup

- app/controllers/applicant/CaptureEmailAddressController.scala
- app/controllers/applicant/CaptureEmailPasscodeController.scala
- app/controllers/errors/EmailConfirmationCodeMaxAttemptsExceededController.scala
- app/controllers/transactor/TransactorCaptureEmailAddressController.scala
- app/controllers/transactor/TransactorCaptureEmailPasscodeController.scala
- app/views/errors/maxConfirmationCodeAttemptsExceeded.scala.html
- conf/app.routes
- conf/messages
- it/controllers/applicant/CaptureEmailAddressControllerISpec.scala
- it/controllers/errors/EmailConfirmationCodeMaxAttemptsExceededControllerISpec.scala
- it/controllers/transactor/TransactorCaptureEmailAddressControllerISpec.scala
SAR-10073 Add new page & error handling for the email confirmation code max attempts exceeded
> SAR-10073 Add new page & error handling for the email confirmation code max attempts exceeded

- app/controllers/vatapplication/ReturnsController.scala
- app/controllers/vatapplication/VoluntaryStartDateNoChoiceController.scala
- app/viewmodels/tasklist/VatRegistrationTaskList.scala
- conf/messages
- it/controllers/TaskListControllerISpec.scala
- it/controllers/vatapplication/ReturnsControllerISpec.scala
- it/controllers/vatapplication/VoluntaryStartDateNoChoiceControllerISpec.scala
- test/viewmodels/tasklist/VatRegistrationTaskListSpec.scala
[SAR-10047](https://jira.tools.tax.service.gov.uk/browse/SAR-10047)
Add registration date to vat registration tasklist section
> SAR-10047 | Add registration date to vat registration tasklist section

- app/controllers/vatapplication/PaymentMethodController.scala
- app/controllers/vatapplication/ReturnsController.scala
- app/controllers/vatapplication/TaxRepController.scala
- app/viewmodels/tasklist/VatRegistrationTaskList.scala
- conf/messages
- it/controllers/TaskListControllerISpec.scala
- it/controllers/vatapplication/PaymentMethodControllerISpec.scala
- it/controllers/vatapplication/TaxRepControllerISpec.scala
- test/testHelpers/ControllerSpec.scala
- test/viewmodels/tasklist/VatRegistrationTaskListSpec.scala
[SAR-10075](https://jira.tools.tax.service.gov.uk/browse/SAR-10075)
Add vat returns row to vat registration tasklist section
> SAR-10075 | Add vat returns row to vat registration tasklist section

- app/controllers/TaskListController.scala
- app/controllers/flatratescheme/FlatRateController.scala
- app/controllers/flatratescheme/JoinFlatRateSchemeController.scala
- app/controllers/flatratescheme/StartDateController.scala
- app/viewmodels/tasklist/VatRegistrationTaskList.scala
- conf/messages
- it/controllers/TaskListControllerISpec.scala
- test/controllers/flatratescheme/FlatRateControllerSpec.scala
- test/controllers/flatratescheme/StartDateControllerSpec.scala
- test/fixtures/FlatRateFixtures.scala
- test/viewmodels/tasklist/VatRegistrationTaskListSpec.scala
SAR-10074 add 'Flat Rate Scheme' section to task list
> SAR-10074 add 'Flat Rate Scheme' section to task list

- app/models/external/BusinessVerificationStatus.scala
[SAR-10193](https://jira.tools.tax.service.gov.uk/browse/SAR-10193) New business verification status to handle users with SA enrolment.
> SAR-10193 | New business verification status

- app/controllers/TaskListController.scala
- app/controllers/attachments/DocumentsRequiredController.scala
- app/controllers/fileupload/UploadDocumentController.scala
- app/models/Business.scala
- app/models/api/VatScheme.scala
- app/viewmodels/tasklist/AttachmentsTaskList.scala
- app/views/attachments/DocumentsPost.scala.html
- app/views/attachments/EmailDocuments.scala.html
- conf/messages
- it/controllers/TaskListControllerISpec.scala
- it/controllers/attachments/DocumentsRequiredControllerISpec.scala
- it/controllers/fileupload/UploadDocumentControllerISpec.scala
- test/viewmodels/tasklist/AttachmentsTaskListSpec.scala
SAR-10222 Add optional 'Attachments' section to task list
> SAR-10222 Add optional 'Attachments' section to task list

- app/controllers/TaskListController.scala
- app/controllers/vatapplication/MandatoryStartDateController.scala
- app/viewmodels/tasklist/SummaryTaskList.scala
- conf/messages
- it/controllers/TaskListControllerISpec.scala
- test/viewmodels/tasklist/SummaryTaskListSpec.scala
[SAR-10223](https://jira.tools.tax.service.gov.uk/browse/SAR-10223)
- Add new tasklist section for CYA summary
- Tidy up TaskList IT spec
> SAR-10223|Add tasklist section for CYA summary

- a11y/pages/attachments/ChooseAttachmentMethodA11ySpec.scala
- a11y/pages/attachments/DocumentsPostA11ySpec.scala
- a11y/pages/attachments/EmailCoverSheetA11ySpec.scala
- a11y/pages/attachments/EmailDocumentsA11ySpec.scala
- a11y/pages/attachments/IdentityEvidenceRequiredA11ySpec.scala
- a11y/pages/attachments/MultipleDocumentsRequiredA11ySpec.scala
- a11y/pages/attachments/PostalCoverSheetA11ySpec.scala
- a11y/pages/attachments/TaxRepresentativeA11ySpec.scala
- a11y/pages/attachments/TransactorIdentityEvidenceRequiredA11ySpec.scala
- a11y/pages/attachments/Vat1TRRequiredA11ySpec.scala
- a11y/pages/attachments/Vat2RequiredA11ySpec.scala
- a11y/pages/attachments/Vat5LRequiredA11ySpec.scala
SAR-10275 Write a11y specs for the 'attachments' package
> SAR-10275 Write a11y specs for the 'attachments' package

- app/controllers/sicandcompliance/BusinessActivitiesResolverController.scala
- test/controllers/sicandcompliance/BusinessActivitiesResolverControllerSpec.scala
**Bug fix**
There was a bug introduced as part of [SAR-10233](https://jira.tools.tax.service.gov.uk/browse/SAR-10233) that caused main business activity submission flow to be stuck in a loop. This was due to how SIC codes guard was handled by the new resolver controller.
Fix is to handle the main business activity flow in resolver to be conditional on both sic codes size and the referer not being main business activity submission flow.
> SAR-10233 | Fix redirect issue in business activity resolver

- app/controllers/JourneyController.scala
- app/services/VatApplicationService.scala
- app/viewmodels/tasklist/VerifyBusinessTaskList.scala
- it/controllers/JourneyControllerISpec.scala
- test/services/VatApplicationServiceSpec.scala
- test/viewmodels/tasklist/VerifyBusinessTaskListSpec.scala
[SAR-10292](https://jira.tools.tax.service.gov.uk/browse/SAR-10292)
**Bug fix**
- Fix errors resulting from absence of applicationReference/honestDeclaration when navigating to task list, by navigating user back to application-reference page
- When multiple applications in progress and redirected to applicationReference page for above case, pass in the registrationId of the selected application. 
- Fix TaskList navigation, `Business Information` row for transactor flow
> SAR-10292 | Redirect to application reference page if appRef or honestDeclaration missing

- app/connectors/BankAccountReputationConnector.scala
- app/viewmodels/tasklist/SummaryTaskList.scala
- test/viewmodels/tasklist/SummaryTaskListSpec.scala
[SAR-10324](https://jira.tools.tax.service.gov.uk/browse/SAR-10324)
**Bug fix**
Update status for submission tasklist row when prerequisites are met
> SAR-10335 | Mark submission tasklist as NotStarted when all prerequisites are met

- app/controllers/vatapplication/ClaimRefundsController.scala
- app/controllers/vatapplication/VatExemptionController.scala
- app/viewmodels/tasklist/VatRegistrationTaskList.scala
- test/viewmodels/tasklist/VatRegistrationTaskListSpec.scala
> SAR-10369 fix overseas TOGC journeys

- app/controllers/flatratescheme/FlatRateController.scala
- app/forms/FlatRateForms.scala
- app/forms/FormValidation.scala
- app/forms/ReceiveGoodsNipForm.scala
- app/forms/SellOrMoveNipForm.scala
- app/forms/SicAndComplianceForms.scala
- app/forms/TurnoverEstimateForm.scala
- app/forms/ZeroRatedSuppliesForm.scala
- app/models/FlatRateModel.scala
- app/services/FlatRateService.scala
- app/viewmodels/Formatters.scala
- app/viewmodels/RegistrationDetailsSummaryBuilder.scala
- app/views/flatratescheme/annual_costs_limited.scala.html
- app/views/flatratescheme/estimate_total_sales.scala.html
- app/views/vatapplication/ReceiveGoodsNip.scala.html
- app/views/vatapplication/SellOrMoveNip.scala.html
- app/views/vatapplication/zero_rated_supplies.scala.html
- conf/messages
- it/controllers/vatapplication/TurnoverEstimateControllerISpec.scala
- test/controllers/flatratescheme/FlatRateControllerSpec.scala
- test/forms/ReceiveGoodsNipFormSpec.scala
- test/forms/SellOrMoveNipFormSpec.scala
- test/forms/TurnoverEstimateFormSpec.scala
- test/forms/ZeroRatedSuppliesFormSpec.scala
- test/viewmodels/RegistrationDetailsSummaryBuilderSpec.scala
- test/views/flatratescheme/AnnualCostsLimitedViewSpec.scala
- test/views/flatratescheme/EstimateTotalSalesViewSpec.scala
- test/views/vatapplication/ZeroRatedSuppliesViewSpec.scala
SAR-10340 validate input value for turnover, zero rated turnover, NIP
> SAR-10340 validate input value for turnover, zero rated turnover, NIP

- app/controllers/vatapplication/CurrentlyTradingController.scala
- app/controllers/vatapplication/VoluntaryStartDateController.scala
- app/controllers/vatapplication/VoluntaryStartDateNoChoiceController.scala
- app/forms/vatapplication/CurrentlyTradingForm.scala
- app/models/api/vatapplication/VatApplication.scala
- app/services/VatApplicationService.scala
- app/viewmodels/RegistrationDetailsSummaryBuilder.scala
- app/views/components/yesNoRadio.scala.html
- app/views/vatapplication/CurrentlyTradingView.scala.html
- conf/app.routes
- conf/messages
- it/controllers/vatapplication/CurrentlyTradingControllerISpec.scala
- it/controllers/vatapplication/VoluntaryStartDateControllerISpec.scala
- it/controllers/vatapplication/VoluntaryStartDateNoChoiceControllerISpec.scala
- test/controllers/vatapplication/VoluntaryStartDateControllerSpec.scala
- test/viewmodels/RegistrationDetailsSummaryBuilderSpec.scala
- test/views/attachments/CurrentlyTradingViewSpec.scala
[SAR-10343](https://jira.tools.tax.service.gov.uk/browse/SAR-10343)
As part of porting intending trader question to VRS-FE, from VRS-EL-FE
- add new page to determine intending trader
- routing to new page
- add page to registration date tasklist section
- update CYA with an entry to registration details to highlight the answer for intending trader question (**TBD** - Waiting on Ali's confirmation with update to content doc)
> SAR-10343 | Add current trading page

- app/config/FrontendAppConfig.scala
- app/controllers/BaseController.scala
- app/controllers/applicant/IncorpIdController.scala
- app/controllers/applicant/IndividualIdentificationController.scala
- app/controllers/applicant/MinorEntityIdController.scala
- app/controllers/applicant/PartnershipIdController.scala
- app/controllers/applicant/SoleTraderIdentificationController.scala
- app/controllers/transactor/TransactorIdentificationController.scala
- app/featureswitch/core/config/FeatureSwitchingModule.scala
- app/models/external/incorporatedentityid/IncorpIdJourneyConfig.scala
- app/models/external/minorentityid/MinorEntityIdJourneyConfig.scala
- app/models/external/partnershipid/PartnershipIdJourneyConfig.scala
- app/models/external/soletraderid/SoleTraderIdJourneyConfig.scala
- app/views/layouts/layout.scala.html
- conf/application.conf
- conf/messages
- conf/messages.cy
- it/controllers/BaseControllerISpec.scala
- test/controllers/applicant/IncorpIdControllerSpec.scala
- test/controllers/applicant/SoleTraderIdentificationControllerSpec.scala
- test/models/external/addresslookup/AddressLookupInitializationModelSpec.scala
- test/viewmodels/RegistrationDetailsSummaryBuilderSpec.scala
- test/views/errors/PasscodeNotFoundViewSpec.scala
> SAR-10350 Added welsh support and translation

- app/connectors/VatRegistrationConnector.scala
- app/services/VatRegistrationService.scala
- it/connectors/VatRegistrationConnectorISpec.scala
- it/service/VatRegistrationServiceISpec.scala
- test/connectors/VatRegistrationConnectorSpec.scala
- test/controllers/SummaryControllerSpec.scala
- test/services/VatRegistrationServiceSpec.scala
> SAR-10402 Updated Submission to send language to BE

- app/controllers/sicandcompliance/SicController.scala
- app/services/ICLService.scala
- test/controllers/sicandcompliance/SicControllerSpec.scala
- test/services/ICLServiceSpec.scala
[SAR-10399](https://jira.tools.tax.service.gov.uk/browse/SAR-10399)
Update content, include welsh content alongside english, passed to ICL connector.
> SAR-10399 | Update content to ICL connector

- app/forms/ReceiveGoodsNipForm.scala
- app/forms/SellOrMoveNipForm.scala
- app/forms/TurnoverEstimateForm.scala
- app/forms/ZeroRatedSuppliesForm.scala
This reverts commit b8cbffc421fe3311f5b0abc558201b94ef1cf78d.
> Revert "SAR-10340 | Fix regex to valide numbers first and revert order"

- app/forms/ReceiveGoodsNipForm.scala
- app/forms/SellOrMoveNipForm.scala
- app/forms/TurnoverEstimateForm.scala
- app/forms/ZeroRatedSuppliesForm.scala
Fix missing value error handling
**Bug fix**
> SAR-10340 | Fix regex to valide numbers first and revert order

- app/controllers/otherbusinessinvolvements/ObiSummaryController.scala
- app/views/otherbusinessinvolvements/ObiSummary.scala.html
- conf/app.routes
- it/controllers/otherbusinessinvolvements/ObiSummaryControllerISpec.scala
- test/views/otherbusinessinvolvements/ObiSummaryViewSpec.scala
[SAR-10424](https://jira.tools.tax.service.gov.uk/browse/SAR-10424)
Remove the option to submit additional OBIs if max limit of 10 already submitted.
> SAR-10424 | Remove option to add OBIs if limit reached

- conf/countries-en.json
[SAR-10423](https://jira.tools.tax.service.gov.uk/browse/SAR-10423)
Update country list to match ALF
> SAR-10423 | Update country list to match ALF

- app/controllers/fileupload/DocumentUploadSummaryController.scala
- app/controllers/fileupload/SupplySupportingDocumentsController.scala
- app/controllers/fileupload/UploadDocumentController.scala
- app/controllers/fileupload/UploadSupportingDocumentController.scala
- app/forms/DocumentUploadSummaryForm.scala
- app/forms/FlatRateForms.scala
- app/views/fileupload/DocumentUploadSummary.scala.html
- app/views/fileupload/UploadDocument.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/fileupload/DocumentUploadSummaryControllerISpec.scala
- it/controllers/fileupload/SupplySupportingDocumentsControllerISpec.scala
- it/controllers/fileupload/UploadSupportingDocumentControllerISpec.scala
- test/forms/DocumentUploadSummaryFormSpec.scala
- test/views/fileupload/DocumentUploadSummaryViewSpec.scala
- test/views/fileupload/UploadDocumentViewSpec.scala
> SAR-10430 Added upload supporting documents flow

- app/forms/OfficerForms.scala
- app/forms/VatExemptionForm.scala
- conf/messages
- conf/messages.cy
- it/controllers/applicant/PreviousAddressControllerISpec.scala
- test/controllers/applicant/PreviousAddressControllerSpec.scala
- test/forms/ApplicantFormsSpec.scala
- test/forms/VatExemptionFormSpec.scala
- test/views/applicant/PreviousAddressViewSpec.scala
> SAR-10451: Fixed bug errors on Previous Address and VAT Exemption pages

- app/controllers/fileupload/Supply1614AController.scala
- app/controllers/fileupload/Supply1614HController.scala
- app/controllers/fileupload/UploadOptionToTaxDocumentController.scala
- app/viewmodels/UploadDocumentHintBuilder.scala
- app/views/fileupload/UploadDocument.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/fileupload/Supply1614AControllerISpec.scala
- it/controllers/fileupload/Supply1614HControllerISpec.scala
- it/controllers/fileupload/UploadOptionToTaxDocumentControllerISpec.scala
> SAR-10429 Added upload 1614a and 1614h flows

- conf/messages.cy
> SAR-10468: Added missing welsh content

- app/viewmodels/tasklist/SummaryTaskList.scala
- test/viewmodels/tasklist/SummaryTaskListSpec.scala
[SAR-10496](https://jira.tools.tax.service.gov.uk/browse/SAR-10496)
**Bug fix**
TaskList summary fix for flow with no attachments and no FRS
> SAR-10497 | Fix TaskList summary row to handle no attachments and no FRS flow

- app/controllers/fileupload/UploadingDocumentController.scala
- app/views/attachments/ChooseAttachmentMethod.scala.html
- app/views/attachments/DocumentsPost.scala.html
- app/views/attachments/EmailDocuments.scala.html
- app/views/attachments/IdentityEvidenceRequired.scala.html
- app/views/attachments/MultipleDocumentsRequired.scala.html
- app/views/attachments/TransactorIdentityEvidenceRequired.scala.html
- app/views/attachments/Vat1TRRequired.scala.html
- app/views/attachments/Vat2Required.scala.html
- app/views/attachments/Vat51Required.scala.html
- app/views/attachments/Vat5LRequired.scala.html
- app/views/fileupload/DocumentUploadSummary.scala.html
- app/views/fileupload/UploadingDocument.scala.html
- conf/messages
- conf/messages.cy
- it/controllers/fileupload/UploadingDocumentControllerISpec.scala
- test/views/attachments/ChooseAttachmentMethodViewSpec.scala
- test/views/attachments/DocumentsPostViewSpec.scala
- test/views/attachments/EmailDocumentsViewSpec.scala
- test/views/attachments/IdentityEvidenceRequiredViewSpec.scala
- test/views/attachments/MultipleDocumentsRequiredViewSpec.scala
- test/views/attachments/TransactorIdentityEvidenceRequiredViewSpec.scala
- test/views/attachments/Vat1TRRequiredViewSpec.scala
- test/views/attachments/Vat2RequiredViewSpec.scala
- test/views/attachments/Vat5LRequiredViewSpec.scala
- test/views/fileupload/UploadingDocumentViewSpec.scala
> SAR-10495 OTT related content changes

- app/views/business/trading_name.scala.html
- app/views/flatratescheme/frs_your_flat_rate.scala.html
- test/views/business/TradingNameViewSpec.scala
- test/views/flatratescheme/FrsYourFlatRateViewSpec.scala
SAR-10548 pass the parameter to label to make it descriptive
**Bug fix**
> SAR-10548 pass the parameter to label to make it descriptive

- app/connectors/ConfigConnector.scala
- app/controllers/flatratescheme/ChooseBusinessTypeController.scala
- app/controllers/flatratescheme/ConfirmBusinessTypeController.scala
- app/controllers/flatratescheme/FlatRateController.scala
- app/models/FrsBusinessType.scala
- app/services/FlatRateService.scala
- app/viewmodels/RegistrationDetailsSummaryBuilder.scala
- app/views/flatratescheme/choose_business_type.scala.html
- conf/frs-business-types-cy.json
- test/connectors/ConfigConnectorSpec.scala
- test/controllers/flatratescheme/ChooseBusinessTypeControllerSpec.scala
- test/controllers/flatratescheme/ConfirmBusinessTypeControllerSpec.scala
- test/controllers/flatratescheme/FlatRateControllerSpec.scala
- test/controllers/flatratescheme/StartDateControllerSpec.scala
- test/fixtures/FlatRateFixtures.scala
- test/services/FlatRateServiceSpec.scala
- test/viewmodels/RegistrationDetailsSummaryBuilderSpec.scala
- test/views/flatratescheme/ChooseBusinessTypeViewSpec.scala
- test/views/flatratescheme/ConfirmBusinessTypeViewSpec.scala
> SAR-10552 set up welsh functionality for FRS business types

- app/views/flatratescheme/choose_business_type.scala.html
> SAR-10566 Fixed radios voiceover and selection on business type page

- app/viewmodels/tasklist/VatRegistrationTaskList.scala
> Quick fix to add proper fallback case to match statement

- app/viewmodels/ApplicantDetailsSummaryBuilder.scala
- app/viewmodels/tasklist/AboutTheBusinessTaskList.scala
- test/viewmodels/tasklist/AboutTheBusinessTaskListSpec.scala
> SAR-10600 Updated business details row to check for company name for unincorp businesses, CYA fix for lead partner

- app/controllers/transactor/TransactorInternationalAddressController.scala
[SAR-10599](https://jira.tools.tax.service.gov.uk/browse/SAR-10599)
**Bug fix**
International address transactor journey, postcode validation was showing wrong error message (`Error:Enter a {0} postcode`) when no postcode submitted for a country that requires postcode. Update to user form results handler addresses the issue.
> SAR-10599 | Fix transactor intl address submit to use form results handler for validation

- app/controllers/applicant/BusinessLeadPartnerEntityController.scala
- app/controllers/applicant/LeadPartnerEntityController.scala
- app/forms/LeadPartnerForm.scala
- app/models/api/PartyType.scala
- app/views/applicant/lead_partner_entity_type.scala.html
- app/views/applicant/partnership_business_entity_type.scala.html
- app/views/vatapplication/return_frequency_view.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/applicant/BusinessLeadPartnerEntityControllerISpec.scala
- it/controllers/applicant/LeadPartnerEntityControllerISpec.scala
- test/controllers/applicant/LeadPartnerEntityControllerSpec.scala
- test/forms/LeadPartnerFormSpec.scala
- test/views/applicant/BusinessLeadPartnerEntityTypeViewSpec.scala
[SAR-10606](https://jira.tools.tax.service.gov.uk/browse/SAR-10606)
- Change current lead partner selection to be restricted to individual/business users
- New page for business lead partner entity type selection
> SAR-10606 | Separate lead partner selection for business entities

- app/controllers/grs/PartnerIncorpIdController.scala
- app/controllers/grs/PartnerPartnershipIdController.scala
- app/controllers/grs/PartnerSoleTraderIdController.scala
- app/models/Entity.scala
- app/services/EntityService.scala
- it/controllers/TaskListControllerISpec.scala
- it/controllers/applicant/BusinessLeadPartnerEntityControllerISpec.scala
- it/controllers/applicant/LeadPartnerEntityControllerISpec.scala
- it/controllers/business/ScottishPartnershipNameControllerISpec.scala
- it/controllers/grs/PartnerIncorpIdControllerISpec.scala
- it/controllers/grs/PartnerPartnershipIdControllerISpec.scala
- it/controllers/grs/PartnerSoleTraderIdControllerISpec.scala
- it/controllers/partners/PartnerIndexValidationISpec.scala
- it/controllers/partners/PartnerScottishPartnershipNameControllerISpec.scala
- test/controllers/applicant/LeadPartnerEntityControllerSpec.scala
- test/services/EntityServiceSpec.scala
- test/viewmodels/ApplicantDetailsSummaryBuilderSpec.scala
- test/viewmodels/tasklist/AboutTheBusinessTaskListSpec.scala
- test/viewmodels/tasklist/AboutYouTaskListSpec.scala
**New feature** (delete as appropriate)
> SAR-10622 Updated entity model to store partner info

- app/controllers/applicant/CaptureRoleInTheBusinessController.scala
- app/forms/RoleInTheBusinessForm.scala
- app/views/applicant/role_in_the_business.scala.html
- conf/messages
- conf/messages.cy
- it/controllers/applicant/CaptureRoleInTheBusinessControllerISpec.scala
- test/views/applicant/RoleInTheBusinessViewSpec.scala
SAR-10673 Update role in business for trust
> SAR-10673 Update role in business for trust

- app/common/enums/AddressLookupJourneyIdentifier.scala
- app/config/AddressLookupConfiguration.scala
- app/controllers/grs/PartnerIncorpIdController.scala
- app/controllers/grs/PartnerPartnershipIdController.scala
- app/controllers/grs/PartnerSoleTraderIdController.scala
- app/controllers/partners/PartnerAddressController.scala
- app/models/Entity.scala
- app/models/external/addresslookup/AddressLookupLanguageModel.scala
- app/models/external/addresslookup/messages/AddressMessagesModel.scala
- app/models/external/addresslookup/messages/InternationalAddressMessagesModel.scala
- app/services/AddressLookupService.scala
- app/services/EntityService.scala
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/grs/PartnerIncorpIdControllerISpec.scala
- it/controllers/grs/PartnerPartnershipIdControllerISpec.scala
- it/controllers/grs/PartnerSoleTraderIdControllerISpec.scala
- it/controllers/partners/BusinessPartnerEntityTypeControllerISpec.scala
- it/controllers/partners/PartnerAddressControllerISpec.scala
- it/controllers/partners/PartnerEntityTypeControllerISpec.scala
- it/controllers/partners/PartnerScottishPartnershipNameControllerISpec.scala
- test/controllers/applicant/HomeAddressControllerSpec.scala
- test/controllers/applicant/PreviousAddressControllerSpec.scala
- test/controllers/business/PpobAddressControllerSpec.scala
- test/services/AddressLookupServiceSpec.scala
> SAR-10623 Added partner alf setup and callback routes

- app/controllers/partners/PartnerAddressController.scala
- app/models/Entity.scala
- app/models/external/addresslookup/AddressLookupLanguageModel.scala
- app/models/external/addresslookup/messages/AddressMessagesModel.scala
- app/models/external/addresslookup/messages/InternationalAddressMessagesModel.scala
- conf/messages
- conf/messages.cy
- it/controllers/partners/PartnerAddressControllerISpec.scala
- test/models/external/addresslookup/AddressLookupInitializationModelSpec.scala
> SAR-10623 content fix for intl pages, refactored address controller

- app/controllers/grs/IncorpIdController.scala
- app/controllers/grs/IndividualIdController.scala
- app/controllers/grs/MinorEntityIdController.scala
- app/controllers/grs/PartnerIncorpIdController.scala
- app/controllers/grs/PartnerPartnershipIdController.scala
- app/controllers/grs/PartnerSoleTraderIdController.scala
- app/controllers/grs/PartnershipIdController.scala
- app/controllers/grs/SoleTraderIdController.scala
- app/controllers/grs/TransactorIdController.scala
- app/models/external/incorporatedentityid/IncorpIdJourneyConfig.scala
- app/models/external/minorentityid/MinorEntityIdJourneyConfig.scala
- app/models/external/partnershipid/PartnershipIdJourneyConfig.scala
- app/models/external/soletraderid/SoleTraderIdJourneyConfig.scala
- it/connectors/IncorpIdConnectorISpec.scala
- it/connectors/MinorEntityIdConnectorISpec.scala
- it/connectors/PartnershipIdConnectorISpec.scala
- it/connectors/SoleTraderIdentificationConnectorISpec.scala
- test/connectors/PartnershipIDConnectorSpec.scala
- test/connectors/SoleTraderIdentificationConnectorSpec.scala
- test/controllers/grs/IncorpIdControllerSpec.scala
- test/controllers/grs/SoleTraderIdControllerSpec.scala
- test/services/SoleTraderIdentificationServiceSpec.scala
> SAR-10617-fix updated the heading sent to STI to be dynamic, changed to new grs label config

- app/controllers/business/ScottishPartnershipNameController.scala
- app/controllers/partners/PartnerAddressController.scala
- app/controllers/partners/PartnerScottishPartnershipNameController.scala
- app/controllers/partners/PartnerTelephoneNumberController.scala
- app/forms/PartnerTelephoneForm.scala
- app/services/EntityService.scala
- app/views/partners/PartnerTelephoneNumber.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/partners/PartnerAddressControllerISpec.scala
- it/controllers/partners/PartnerTelephoneNumberControllerISpec.scala
- test/services/EntityServiceSpec.scala
- test/views/partners/PartnerTelephoneNumberViewSpec.scala
SAR-10625 capture partner's phone number
> SAR-10625 capture partner's phone number

- app/controllers/partners/PartnerCaptureEmailAddressController.scala
- app/forms/PartnerEmailAddressForm.scala
- app/services/EntityService.scala
- app/views/partners/PartnerCaptureEmailAddress.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/partners/BusinessPartnerEntityTypeControllerISpec.scala
- it/controllers/partners/PartnerCaptureEmailControllerISpec.scala
- it/controllers/partners/PartnerEntityTypeControllerISpec.scala
- it/controllers/partners/PartnerTelephoneNumberControllerISpec.scala
- test/views/partners/PartnerCaptureEmailAddressViewSpec.scala
- test/views/transactor/TransactorCaptureEmailAddressViewSpec.scala
> SAR-10626: Added Partner Capture Email Address page and tests

- app/config/FrontendAppConfig.scala
- app/controllers/ApplicationSubmissionController.scala
- app/views/ApplicationSubmissionConfirmation.scala.html
- conf/application.conf
- conf/messages
- conf/messages.cy
- test/controllers/ApplicationSubmissionControllerSpec.scala
- test/views/ApplicationSubmissionConfirmationViewSpec.scala
- test/views/BaseSelectors.scala
- test/views/VatRegViewSpec.scala
> SAR-10729 Updated application submission confirmation content, added 3pt content

- app/controllers/attachments/AttachmentMethodController.scala
- app/controllers/fileupload/DocumentUploadSummaryController.scala
- app/controllers/fileupload/UploadOptionToTaxDocumentController.scala
- app/controllers/fileupload/UploadSupportingDocumentController.scala
- app/controllers/partners/AdditionalPartnerEntityController.scala
- app/controllers/partners/PartnerCaptureEmailAddressController.scala
- app/controllers/partners/PartnerSummaryController.scala
- app/controllers/partners/RemovePartnerEntityController.scala
- app/forms/partners/PartnerSummaryForm.scala
- app/forms/partners/RemovePartnerEntityForm.scala
- app/models/api/Attachments.scala
- app/services/AttachmentsService.scala
- app/services/EntityService.scala
- app/viewmodels/PartnerSummaryRow.scala
- app/viewmodels/tasklist/AboutTheBusinessTaskList.scala
- app/views/components/PartnerSummaryTable.scala.html
- app/views/partners/AdditionalPartnersRequired.scala.html
- app/views/partners/PartnerSummary.scala.html
- app/views/partners/RemovePartnerEntity.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/partners/PartnerCaptureEmailControllerISpec.scala
- it/controllers/partners/PartnerSummaryControllerISpec.scala
- it/controllers/partners/RemovePartnerEntityControllerISpec.scala
- test/viewmodels/tasklist/AboutTheBusinessTaskListSpec.scala
- test/views/partners/PartnerSummaryViewSpec.scala
- test/views/partners/RemovePartnerEntityViewSpec.scala
[SAR-10692](https://jira.tools.tax.service.gov.uk/browse/SAR-10692)
- Partner summary page
- Send flag to BE if more than 10 partners required
> SAR-10692 | Partner summary page

- app/models/api/VatSchemeHeader.scala
- app/services/AttachmentsService.scala
- it/controllers/JourneyControllerISpec.scala
> SAR-10767 fixed attachment method page removing digital partner journey flag, updated vat scheme header to be more correct

- conf/messages
- conf/messages.cy
> SAR-10713: Added Welsh translations for Partnership

- app/connectors/ConfigConnector.scala
- app/models/api/SicCode.scala
- it/fixtures/ITRegistrationFixtures.scala
- test/connectors/ConfigConnectorSpec.scala
- test/models/BusinessSpec.scala
[SAR-10770](https://jira.tools.tax.service.gov.uk/browse/SAR-10770)
Add welsh language support for Sic codes
> SAR-10770 | Add welsh language support for sic codes

- app/controllers/vatapplication/CurrentlyTradingController.scala
- app/controllers/vatapplication/MandatoryStartDateController.scala
- app/controllers/vatapplication/VoluntaryStartDateController.scala
- app/controllers/vatapplication/VoluntaryStartDateNoChoiceController.scala
- app/forms/VoluntaryStartDateNoChoiceForm.scala
- app/forms/vatapplication/StartDateForms.scala
- app/models/MonthYearModel.scala
- app/models/view/Summary.scala
- app/utils/MessageDateFormat.scala
- app/viewmodels/ApplicantDetailsSummaryBuilder.scala
- app/viewmodels/ManageRegistrationsBuilder.scala
- app/viewmodels/RegistrationDetailsSummaryBuilder.scala
- app/viewmodels/TransactorDetailsSummaryBuilder.scala
- app/views/components/inputTextarea.scala.html
- test/fixtures/VatRegistrationFixture.scala
- test/forms/VoluntaryStartDateNoChoiceFormSpec.scala
- test/forms/vatapplication/MandatoryDateFormSpec.scala
- test/forms/vatapplication/VoluntaryDateFormIncorpSpec.scala
- test/forms/vatapplication/VoluntaryDateFormSpec.scala
- test/utils/MessageDateFormatSpec.scala
- test/viewmodels/EligibilitySummaryBuilderSpec.scala
- test/viewmodels/TransactorDetailsSummaryBuilderSpec.scala
[SAR-10816](https://jira.tools.tax.service.gov.uk/browse/SAR-10816)
- Welsh language support for date formatter
- Business description text-area character count message in welsh
> SAR-10816 | Welsh language support for dates

- app/controllers/vatapplication/AccountingPeriodController.scala
- app/controllers/vatapplication/PaymentMethodController.scala
- app/controllers/vatapplication/ReturnsFrequencyController.scala
- app/featureswitch/core/config/FeatureSwitchingModule.scala
- app/viewmodels/tasklist/VatRegistrationTaskList.scala
- it/controllers/vatapplication/PaymentMethodControllerISpec.scala
- test/controllers/vatapplication/AccountingPeriodControllerSpec.scala
- test/controllers/vatapplication/ReturnsFrequencyControllerSpec.scala
- test/viewmodels/tasklist/SummaryTaskListSpec.scala
- test/viewmodels/tasklist/VatRegistrationTaskListSpec.scala
[SAR-10843](https://jira.tools.tax.service.gov.uk/browse/SAR-10843)
- Remove TaxRep FS
- Make TaxRep specific to only non-uk journeys
> SAR-10843 | Make TaxRep mandatory for non-uk journeys and remove FS

- app/connectors/test/TestVatRegistrationConnector.scala
- app/controllers/flatratescheme/StartDateController.scala
- app/controllers/vatapplication/CurrentlyTradingController.scala
- app/forms/vatapplication/StartDateForms.scala
- app/models/FlatRateScheme.scala
- app/services/FlatRateService.scala
- it/controllers/flatratescheme/EstimateTotalSalesControllerISpec.scala
- it/controllers/flatratescheme/JoinFlatRateSchemeControllerISpec.scala
- it/controllers/flatratescheme/StartDateControllerISpec.scala
- test/services/FlatRateServiceSpec.scala
> SAR-10846 Removed all FRS S4L callouts

- app/views/otherbusinessinvolvements/ObiSummary.scala.html
- conf/messages
- conf/messages.cy
- test/views/otherbusinessinvolvements/ObiSummaryViewSpec.scala
[SAR-10855](https://jira.tools.tax.service.gov.uk/browse/SAR-10855)
Add text to inform users of not requiring more than 10 business involvements.
> SAR-10855 | Add inform text on obi summary for max business involvements

- app/connectors/RegistrationApiConnector.scala
- app/controllers/partners/PartnerSummaryController.scala
- app/controllers/partners/RemovePartnerEntityController.scala
- app/services/EntityService.scala
- app/viewmodels/tasklist/AboutTheBusinessTaskList.scala
- app/views/components/PartnerSummaryTable.scala.html
- app/views/partners/PartnerSummary.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/partners/PartnerSummaryControllerISpec.scala
- it/support/StubUtils.scala
- test/views/partners/PartnerSummaryViewSpec.scala
> SAR-10848 Updated partner summary page to handle incomplete partners and single partner case, updated tasklist for partners

- app/controllers/JourneyController.scala
- app/featureswitch/core/config/FeatureSwitchingModule.scala
- app/services/TransactorDetailsService.scala
- app/viewmodels/tasklist/AboutYouTransactorTaskList.scala
- app/views/flatratescheme/annual_costs_inclusive.scala.html
- conf/messages
- conf/messages.cy
- it/controllers/JourneyControllerISpec.scala
- test/services/TransactorDetailsServiceSpec.scala
- test/viewmodels/tasklist/AboutYouTransactorTaskListSpec.scala
- test/views/flatratescheme/AnnualCostsInclusiveViewSpec.scala
> SAR-10874 Fixed completeness check/data storage for transactors, removed Agent flow and Multiple Reg feature switches, removed invalid content in frs

- app/viewmodels/ApplicantDetailsSummaryBuilder.scala
- conf/messages
- conf/messages.cy
- test/fixtures/VatRegistrationFixture.scala
- test/viewmodels/ApplicantDetailsSummaryBuilderSpec.scala
[SAR-10891](https://jira.tools.tax.service.gov.uk/browse/SAR-10891)
Add lead partner details to CYA `applicant` section
> SAR-10891 | Add lead partner details to CYA

- app/connectors/test/TestVatRegistrationConnector.scala
- app/controllers/JourneyController.scala
- app/featureswitch/core/config/FeatureSwitchingModule.scala
- app/forms/OfficerForms.scala
- app/views/attachments/DocumentsPost.scala.html
- app/views/attachments/EmailDocuments.scala.html
- app/views/attachments/IdentityEvidenceRequired.scala.html
- app/views/components/button.scala.html
- it/controllers/JourneyControllerISpec.scala
- it/controllers/flatratescheme/EstimateTotalSalesControllerISpec.scala
- test/views/ApplicationSubmissionConfirmationViewSpec.scala
- test/views/HonestyDeclarationViewSpec.scala
- test/views/VatRegViewSpec.scala
- test/views/applicant/BusinessPartnerEntityTypeViewSpec.scala
- test/views/applicant/CaptureEmailAddressViewSpec.scala
- test/views/applicant/CaptureEmailPasscodeViewSpec.scala
- test/views/applicant/CaptureTelephoneNumberViewSpec.scala
- test/views/applicant/EmailVerifiedViewSpec.scala
- test/views/applicant/PartnerEntityTypeViewSpec.scala
- test/views/applicant/RoleInTheBusinessViewSpec.scala
- test/views/bankdetails/CompanyBankDetailsViewSpec.scala
- test/views/bankdetails/NoUKBankAccountViewSpec.scala
- test/views/business/ContactPreferenceViewSpec.scala
- test/views/fileupload/UploadDocumentViewSpec.scala
- test/views/flatratescheme/JoinFrsViewSpec.scala
- test/views/partners/PartnerCaptureEmailAddressViewSpec.scala
- test/views/vatapplication/ImportsOrExportsViewSpec.scala
- test/views/vatapplication/LastMonthOfAccountingYearViewSpec.scala
- test/views/vatapplication/VoluntaryStartDateNoChoiceViewSpec.scala
> Remove Save & Continue FS

- app/controllers/otherbusinessinvolvements/OtherBusinessInvolvementController.scala
- app/views/otherbusinessinvolvements/ObiSummary.scala.html
- app/views/otherbusinessinvolvements/OtherBusinessInvolvement.scala.html
- conf/messages
- it/controllers/otherbusinessinvolvements/OtherBusinessInvolvementControllerISpec.scala
- test/views/otherbusinessinvolvements/OtherBusinessCheckAnswersSpec.scala
- test/views/otherbusinessinvolvements/OtherBusinessInvolvementViewSpec.scala
SAR-10908 Update main OBI question with new content, update CYA row
> SAR-10908 Update main OBI question with new content, update CYA row

- conf/messages
- it/controllers/transactor/TransactorEmailAddressVerifiedControllerISpec.scala
- test/viewmodels/TransactorDetailsSummaryBuilderSpec.scala
SAR-10923 Update main OBI question with new content, update CYA row
> SAR-10923 Update main OBI question with new content, update CYA row

- app/controllers/transactor/TransactorCaptureEmailPasscodeController.scala
- app/services/TransactorDetailsService.scala
- app/viewmodels/tasklist/AboutYouTransactorTaskList.scala
- it/controllers/grs/TransactorIdControllerISpec.scala
- it/controllers/transactor/AgentNameControllerISpec.scala
- it/controllers/transactor/DeclarationCapacityControllerISpec.scala
- it/controllers/transactor/OrganisationNameControllerISpec.scala
- it/controllers/transactor/PartOfOrganisationControllerISpec.scala
- it/controllers/transactor/TelephoneNumberControllerISpec.scala
- it/controllers/transactor/TransactorCaptureEmailAddressControllerISpec.scala
- it/controllers/transactor/TransactorCaptureEmailPasscodeControllerISpec.scala
- it/controllers/transactor/TransactorEmailAddressVerifiedControllerISpec.scala
- it/controllers/transactor/TransactorHomeAddressControllerISpec.scala
- it/controllers/transactor/TransactorInternationalAddressControllerISpec.scala
- test/services/TransactorDetailsServiceSpec.scala
- test/viewmodels/tasklist/AboutYouTransactorTaskListSpec.scala
> SAR-10947 Removed S4L store for TransactorDetails, kept S4L get for current journeys

- app/viewmodels/GrsSummaryBuilder.scala
- conf/messages
- conf/messages.cy
- test/viewmodels/GrsSummaryBuilderSpec.scala
> SAR-10924: Updated CYA for GRS - Verify Your Business section

- app/models/TransactorDetails.scala
- app/services/TransactorDetailsService.scala
- it/controllers/errors/EmailConfirmationCodeMaxAttemptsExceededControllerISpec.scala
- it/controllers/grs/TransactorIdControllerISpec.scala
- it/controllers/transactor/AgentNameControllerISpec.scala
- it/controllers/transactor/DeclarationCapacityControllerISpec.scala
- it/controllers/transactor/OrganisationNameControllerISpec.scala
- it/controllers/transactor/PartOfOrganisationControllerISpec.scala
- it/controllers/transactor/TelephoneNumberControllerISpec.scala
- it/controllers/transactor/TransactorCaptureEmailAddressControllerISpec.scala
- it/controllers/transactor/TransactorCaptureEmailPasscodeControllerISpec.scala
- it/controllers/transactor/TransactorHomeAddressControllerISpec.scala
- it/controllers/transactor/TransactorInternationalAddressControllerISpec.scala
- test/services/TransactorDetailsServiceSpec.scala
> SAR-10947 removed s4l for transactor block

- conf/messages
- test/viewmodels/ApplicantDetailsSummaryBuilderSpec.scala
- test/viewmodels/GrsSummaryBuilderSpec.scala
SAR-11001 update Lead Partner's fields in 'About the business contact' (about you for applicant) CYA block
**Bug fix**
> SAR-11001 update Lead Partner's fields in 'About the business contact' (about you for applicant) CYA block

- app/config/FrontendAppConfig.scala
- app/views/otherbusinessinvolvements/ObiSummary.scala.html
- conf/application.conf
- conf/frs-business-types.json
- conf/messages
- conf/messages.cy
- test/views/applicant/FormerNameViewSpec.scala
> SAR-10985: Added remaining Welsh content

- app/controllers/otherbusinessinvolvements/ObiSummaryController.scala
- app/models/OtherBusinessInvolvement.scala
- app/services/OtherBusinessInvolvementsService.scala
- app/viewmodels/tasklist/AboutTheBusinessTaskList.scala
- it/controllers/otherbusinessinvolvements/CaptureUtrControllerISpec.scala
- it/controllers/otherbusinessinvolvements/CaptureVrnControllerISpec.scala
- it/controllers/otherbusinessinvolvements/HasUtrControllerISpec.scala
- it/controllers/otherbusinessinvolvements/HaveVatNumberControllerISpec.scala
- it/controllers/otherbusinessinvolvements/OtherBusinessActivelyTradingControllerISpec.scala
- it/controllers/otherbusinessinvolvements/OtherBusinessNameControllerISpec.scala
- test/fixtures/VatRegistrationFixture.scala
- test/services/OtherBusinessInvolvementsServiceSpec.scala
> SAR-11034 removed S4L store for OBI, updated tasklist and obi summary to handle partial models

- app/controllers/otherbusinessinvolvements/ObiIndexValidation.scala
- app/controllers/otherbusinessinvolvements/OtherBusinessInvolvementController.scala
- app/models/OtherBusinessInvolvement.scala
- app/services/OtherBusinessInvolvementsService.scala
- it/controllers/otherbusinessinvolvements/CaptureUtrControllerISpec.scala
- it/controllers/otherbusinessinvolvements/CaptureVrnControllerISpec.scala
- it/controllers/otherbusinessinvolvements/HasUtrControllerISpec.scala
- it/controllers/otherbusinessinvolvements/HaveVatNumberControllerISpec.scala
- it/controllers/otherbusinessinvolvements/OtherBusinessActivelyTradingControllerISpec.scala
- it/controllers/otherbusinessinvolvements/OtherBusinessCheckAnswersControllerISpec.scala
- it/controllers/otherbusinessinvolvements/OtherBusinessInvolvementControllerISpec.scala
- it/controllers/otherbusinessinvolvements/OtherBusinessNameControllerISpec.scala
- it/controllers/otherbusinessinvolvements/RemoveOtherBusinessControllerISpec.scala
- test/services/OtherBusinessInvolvementsServiceSpec.scala
- test/services/S4LServiceSpec.scala
> SAR-11035 removed S4L entirely for the OBI block

- app/viewmodels/ManageRegistrationsBuilder.scala
- conf/messages
- conf/messages.cy
> SAR-11057: Added welsh translation for Manage Registrations statuses

- conf/messages.cy
> SAR-11057b: Updated welsh

- app/controllers/ApplicationSubmissionController.scala
- app/controllers/BaseController.scala
- app/controllers/JourneyController.scala
- app/controllers/TaskListController.scala
- app/controllers/attachments/EmailCoverSheetController.scala
- app/controllers/attachments/PostalCoverSheetController.scala
- app/models/api/VatScheme.scala
- app/models/api/VatSchemeHeader.scala
- app/services/SessionProfile.scala
- app/viewmodels/tasklist/AboutYouTaskList.scala
- app/viewmodels/tasklist/VatRegistrationTaskList.scala
- it/connectors/VatRegistrationConnectorISpec.scala
- it/controllers/JourneyControllerISpec.scala
- it/controllers/TaskListControllerISpec.scala
- it/controllers/attachments/EmailCoverSheetControllerISpec.scala
- it/controllers/attachments/PostalCoverSheetControllerISpec.scala
- test/controllers/ApplicationSubmissionControllerSpec.scala
- test/viewmodels/tasklist/AboutYouTaskListSpec.scala
- test/viewmodels/tasklist/VatRegistrationTaskListSpec.scala
> SAR-11101 Updated post submission and tasklist routing to better deal with page hopping

- conf/messages.cy
[SAR-11104](https://jira.tools.tax.service.gov.uk/browse/SAR-11104)
Update welsh translations with updated content
> SAR-11104 | Update welsh content

- a11y/pages/flatratescheme/AnnualCostsInclusiveA11ySpec.scala
- a11y/pages/flatratescheme/AnnualCostsLimitedA11ySpec.scala
- a11y/pages/flatratescheme/ChooseBusinessTypeA11ySpec.scala
- a11y/pages/flatratescheme/EstimateTotalSalesA11ySpec.scala
- a11y/pages/flatratescheme/FrsConfirmBusinessSectorA11ySpec.scala
- a11y/pages/flatratescheme/FrsJoinA11ySpec.scala
- a11y/pages/flatratescheme/FrsRegisterForA11ySpec.scala
- a11y/pages/flatratescheme/FrsStartDateA11ySpec.scala
- a11y/pages/flatratescheme/FrsYourFlatRateA11ySpec.scala
SAR-11106 add a11y specs for the 'flatratescheme' package
> SAR-11106 add a11y specs for the 'flatratescheme' package

- a11y/pages/otherbusinessinvolvements/CaptureUtrA11ySpec.scala
- a11y/pages/otherbusinessinvolvements/CaptureVrnA11ySpec.scala
- a11y/pages/otherbusinessinvolvements/HasUtrA11ySpec.scala
- a11y/pages/otherbusinessinvolvements/HaveVatNumberA11ySpec.scala
- a11y/pages/otherbusinessinvolvements/ObiSummaryA11ySpec.scala
- a11y/pages/otherbusinessinvolvements/OtherBusinessActivelyTradingA11ySpec.scala
- a11y/pages/otherbusinessinvolvements/OtherBusinessCheckAnswersA11ySpec.scala
- a11y/pages/otherbusinessinvolvements/OtherBusinessInvolvementA11ySpec.scala
- a11y/pages/otherbusinessinvolvements/OtherBusinessNameA11ySpec.scala
- a11y/pages/otherbusinessinvolvements/RemoveOtherBusinessA11ySpec.scala
- app/controllers/otherbusinessinvolvements/OtherBusinessInvolvementController.scala
- app/forms/otherbusinessinvolvements/OtherBusinessInvolvementForm.scala
- test/views/otherbusinessinvolvements/OtherBusinessCheckAnswersViewSpec.scala
- test/views/otherbusinessinvolvements/OtherBusinessInvolvementViewSpec.scala
> SAR-11099: Added A11y specs for Other Business Involvements package

- a11y/pages/applicant/RoleInTheBusinessA11ySpec.scala
- app/config/frontendWiring.scala
- app/controllers/JourneyController.scala
- app/controllers/applicant/CaptureEmailAddressController.scala
- app/controllers/applicant/CaptureRoleInTheBusinessController.scala
- app/controllers/applicant/CaptureTelephoneNumberController.scala
- app/controllers/applicant/FormerNameCaptureController.scala
- app/controllers/applicant/FormerNameController.scala
- app/controllers/applicant/FormerNameDateController.scala
- app/controllers/applicant/InternationalHomeAddressController.scala
- app/controllers/applicant/PreviousAddressController.scala
- app/controllers/grs/PartnershipIdController.scala
- app/controllers/partners/PartnerSummaryController.scala
- app/controllers/sicandcompliance/BusinessActivitiesResolverController.scala
- app/controllers/vatapplication/ApplyForEoriController.scala
- app/forms/RoleInTheBusinessForm.scala
- app/models/ApplicantDetails.scala
- app/services/ApplicantDetailsService.scala
- app/viewmodels/AboutTheBusinessSummaryBuilder.scala
- app/viewmodels/ApplicantDetailsSummaryBuilder.scala
- app/views/applicant/role_in_the_business.scala.html
- conf/messages
- conf/messages.cy
- it/controllers/applicant/CaptureRoleInTheBusinessControllerISpec.scala
- test/controllers/business/SupplyWorkersIntermediaryControllerSpec.scala
- test/forms/RoleInTheBusinessFormSpec.scala
- test/services/ApplicantDetailsServiceSpec.scala
- test/services/mocks/MockApplicantDetailsService.scala
- test/views/applicant/RoleInTheBusinessViewSpec.scala
> SAR-11103 Added extra roles to the role in the business page

- a11y/pages/vatapplication/AasPaymentMethodA11ySpec.scala
- a11y/pages/vatapplication/AccountingPeriodA11ySpec.scala
- a11y/pages/vatapplication/ApplyForEoriA11ySpec.scala
- a11y/pages/vatapplication/ClaimRefundsA11ySpec.scala
- a11y/pages/vatapplication/CurrentlyTradingA11ySpec.scala
- a11y/pages/vatapplication/DispatchFromWarehouseA11ySpec.scala
- a11y/pages/vatapplication/ImportsOrExportsA11ySpec.scala
- a11y/pages/vatapplication/LastMonthOfAccountingYearA11ySpec.scala
- a11y/pages/vatapplication/MandatoryStartDateIncorpA11ySpec.scala
- a11y/pages/vatapplication/MandatoryStartDateNoChoiceA11ySpec.scala
- a11y/pages/vatapplication/OverseasApplyForEoriA11ySpec.scala
- a11y/pages/vatapplication/PaymentFrequencyA11ySpec.scala
- a11y/pages/vatapplication/ReceiveGoodsNipA11ySpec.scala
- a11y/pages/vatapplication/ReturnFrequencyA11ySpec.scala
- a11y/pages/vatapplication/SellOrMoveNipA11ySpec.scala
- a11y/pages/vatapplication/SendEUGoodsA11ySpec.scala
- a11y/pages/vatapplication/SendGoodsOverseasA11ySpec.scala
- a11y/pages/vatapplication/StartDateIncorpA11ySpec.scala
- a11y/pages/vatapplication/StoringGoodsA11ySpec.scala
- a11y/pages/vatapplication/TaxRepresentativeA11ySpec.scala
- a11y/pages/vatapplication/TurnoverEstimateA11ySpec.scala
- a11y/pages/vatapplication/VatExemptionA11ySpec.scala
- a11y/pages/vatapplication/VoluntaryStartDateNoChoiceA11ySpec.scala
- a11y/pages/vatapplication/WarehouseNameA11ySpec.scala
- a11y/pages/vatapplication/WarehouseNumberA11ySpec.scala
- a11y/pages/vatapplication/ZeroRatedSuppliesA11ySpec.scala
[SAR-11107](https://jira.tools.tax.service.gov.uk/browse/SAR-11107)
a11y specs for `vatapplication` package
> SAR-11107 | Add a11y specs for vatapplication package

- app/controllers/ApplicationSubmissionController.scala
- app/views/ApplicationSubmissionConfirmation.scala.html
- conf/messages
- conf/messages.cy
- test/controllers/ApplicationSubmissionControllerSpec.scala
- test/views/ApplicationSubmissionConfirmationViewSpec.scala
[SAR-10662](https://jira.tools.tax.service.gov.uk/browse/SAR-10662)
Update submission confirmation page content for VatGroup/TOGC/COLE users.
> SAR-10662 | Custom submission confirmation messages for vat-group/togc

- app/controllers/fileupload/DocumentUploadSummaryController.scala
- app/featureswitch/core/config/FeatureSwitchingModule.scala
- app/views/attachments/EmailCoverSheet.scala.html
- app/views/attachments/MultipleDocumentsRequired.scala.html
- app/views/attachments/PostalCoverSheet.scala.html
- app/views/attachments/Vat5LRequired.scala.html
- it/controllers/fileupload/DocumentUploadSummaryControllerISpec.scala
- test/views/attachments/EmailCoverSheetViewSpec.scala
- test/views/attachments/MultipleDocumentsRequiredViewSpec.scala
- test/views/attachments/PostalCoverSheetViewSpec.scala
- test/views/attachments/Vat5LRequiredViewSpec.scala
> SAR-11147: Removed Option to Tax feature switch and updated tests

- app/controllers/attachments/AttachmentMethodController.scala
- app/featureswitch/core/config/FeatureSwitchingModule.scala
- app/views/attachments/ChooseAttachmentMethod.scala.html
- it/controllers/attachments/AttachmentMethodControllerISpec.scala
- test/views/attachments/ChooseAttachmentMethodViewSpec.scala
> SAR-11150: Removed Upload Attachments feature switch and updated tests

- a11y/pages/partners/AdditionalPartnersRequiredA11ySpec.scala
- a11y/pages/partners/PartnerCaptureEmailAddressA11ySpec.scala
- a11y/pages/partners/PartnerScottishPartnershipNameA11ySpec.scala
- a11y/pages/partners/PartnerSummaryA11ySpec.scala
- a11y/pages/partners/PartnerTelephoneNumberA11ySpec.scala
- a11y/pages/partners/RemovePartnerEntityA11ySpec.scala
- app/controllers/partners/PartnerSummaryController.scala
- app/views/partners/PartnerSummary.scala.html
- test/views/partners/PartnerSummaryViewSpec.scala
[SAR-11149](https://jira.tools.tax.service.gov.uk/browse/SAR-11149)
- Add a11y specs for `partners` package
- Small tidyup of partner summary view to remove partner list size parameter
> SAR-11149 | a11y specs for partners package

- conf/messages.cy
- project/plugins.sbt
[SAR-11161](https://jira.tools.tax.service.gov.uk/browse/SAR-11161)
- Update welsh submission messages to reflect change in SLA to 40 days
> SAR-11161 | Update welsh content for SLA change to 40 days

- app/controllers/otherbusinessinvolvements/ObiIndexValidation.scala
- app/controllers/otherbusinessinvolvements/ObiSummaryController.scala
- app/controllers/otherbusinessinvolvements/RemoveOtherBusinessController.scala
- it/controllers/otherbusinessinvolvements/ObiSummaryControllerISpec.scala
- it/controllers/otherbusinessinvolvements/RemoveOtherBusinessControllerISpec.scala
> Fixed remove OBI page failing when attempting to remove missing obi

- README.md
> SAR-11184: Updated README file

- app/views/layouts/layout.scala.html
> SAR-11206: Remove beta banner

- test/views/partners/AdditionalPartnersRequiredViewSpec.scala
[SAR-11200](https://jira.tools.tax.service.gov.uk/browse/SAR-11200)
Add missing test for AdditionalPartnersRequired view
> SAR-11200 | Add missing test for AdditionalPartnersRequired view

- a11y/pages/sicandcompliance/WorkersA11ySpec.scala
- app/connectors/UpscanConnector.scala
- app/controllers/business/WorkersController.scala
- app/services/UpscanService.scala
- it/controllers/business/WorkersControllerISpec.scala
- test/controllers/business/WorkersControllerSpec.scala
- test/views/sicandcompliance/WorkersViewSpec.scala
> [DL-9810] add additional logging around upscan logic

- conf/bank-holidays.json
> DL-BankHolidayUpdate - update the bank holiday

- app/controllers/vatapplication/VoluntaryStartDateNoChoiceController.scala
- app/utils/MessageDateFormat.scala
- test/utils/MessageDateFormatSpec.scala
> DL-10502 - changed date format for hint text

- app/connectors/VerifyEmailVerificationPasscodeConnector.scala
- app/utils/LoggingUtil.scala
> [EmailVeriLogs] add extra logging around email verification

- app/controllers/attachments/AttachmentMethodController.scala
- app/controllers/attachments/DocumentsPostErrorController.scala
- app/controllers/attachments/MultipleDocumentsRequiredController.scala
- app/featuretoggle/FeatureSwitch.scala
- app/views/attachments/ChooseAttachmentMethodNewJourney.scala.html
- app/views/attachments/DocumentsPostError.scala.html
- conf/app.routes
- conf/messages
- it/controllers/attachments/AttachmentMethodControllerISpec.scala
> Attachment method page

- app/connectors/VerifyEmailVerificationPasscodeConnector.scala
- app/controllers/applicant/CaptureEmailPasscodeController.scala
- app/models/external/VerifyEmailPasscodeResult.scala
- it/connectors/VerifyEmailVerificationPasscodeConnectorISpec.scala
- it/controllers/applicant/CaptureEmailPasscodeControllerISpec.scala
> [EmailVeriLogs2] move email verification logs to controller

- app/controllers/attachments/AttachmentMethodController.scala
- app/controllers/attachments/PostalConfirmationController.scala
- app/controllers/fileupload/DocumentUploadSummaryController.scala
- app/controllers/fileupload/UploadOptionToTaxDocumentController.scala
- app/controllers/fileupload/UploadSupportingDocumentController.scala
- app/featuretoggle/FeatureSwitch.scala
- app/featuretoggle/FeatureToggleSupport.scala
- app/forms/AttachmentMethodForm.scala
- app/forms/PostalConfirmationPageForm.scala
- app/models/api/Attachments.scala
- app/viewmodels/tasklist/AttachmentsTaskList.scala
- app/views/attachments/AdditionalDocuments.scala.html
- app/views/attachments/PostalConfirmation.scala.html
- conf/app.routes
- conf/messages
- it/connectors/AttachmentsConnectorISpec.scala
- it/controllers/JourneyControllerISpec.scala
- it/controllers/attachments/AttachmentMethodControllerISpec.scala
- it/controllers/attachments/PostalConfirmationControllerISpec.scala
- it/controllers/fileupload/DocumentUploadSummaryControllerISpec.scala
- it/controllers/fileupload/UploadOptionToTaxDocumentControllerISpec.scala
- it/controllers/fileupload/UploadSupportingDocumentControllerISpec.scala
- it/controllers/partners/PartnerSummaryControllerISpec.scala
- it/controllers/partners/RemovePartnerEntityControllerISpec.scala
- test/controllers/ApplicationSubmissionControllerSpec.scala
- test/forms/AttachmentMethodFormSpec.scala
- test/viewmodels/tasklist/AttachmentsTaskListSpec.scala
- test/viewmodels/tasklist/SummaryTaskListSpec.scala
> DL-10905 Postal confirmation page

- conf/messages
- conf/messages.cy
> DL-11645 - change the text around

- app/controllers/attachments/AttachmentMethodController.scala
- app/controllers/attachments/PostalConfirmationController.scala
- app/viewmodels/TransactorDetailsSummaryBuilder.scala
> add catch all for declaration capacity answer

- app/controllers/attachments/AttachmentMethodController.scala
- app/controllers/attachments/PostalConfirmationController.scala
- app/forms/PostalConfirmationPageForm.scala
- app/views/attachments/PostalConfirmation.scala.html
- conf/messages
- test/forms/PostalConfirmationFormSpec.scala
(cherry picked from commit 849c6643c067794602c87e744f32ab3159b3d7d9)
> DL-10905: Add more logging and test for form

- app/controllers/SummaryController.scala
> DL-10867 - added logs

- app/views/components/warningText.scala.html
- app/views/layouts/layout.scala.html
- project/AppDependencies.scala
- project/plugins.sbt
> [DL-13104] upgrade play-frontend-hmrc

- app/config/FrontendAppConfig.scala
> Update the eligibility url config

- app/repositories/SessionRepository.scala
- test/forms/vatapplication/VoluntaryDateFormIncorpSpec.scala
> DL-15459: added new id index

- app/repositories/SessionRepository.scala
> DL-15459: Reverted index change

- app/featuretoggle/FeatureSwitch.scala
- conf/application.conf
> DL-15562 : added tt featureswitch

- app/config/FrontendAppConfig.scala
- app/controllers/vatapplication/ApplyForEoriController.scala
- app/controllers/vatapplication/ImportsOrExportsController.scala
- app/controllers/vatapplication/TwentyRatedSuppliesController.scala
- app/forms/FormValidation.scala
- app/forms/TwentyRatedSuppliesForm.scala
- app/models/api/vatapplication/VatApplication.scala
- app/services/VatApplicationService.scala
- app/views/vatapplication/ImportsOrExports.scala.html
- app/views/vatapplication/TwentyRatedSupplies.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/test/controllers/vatapplication/ImportsOrExportsControllerISpec.scala
- it/test/controllers/vatapplication/TwentyRatedSuppliesControllerISpec.scala
- test/forms/TwentyRatedSuppliesFormSpec.scala
- test/views/VatRegViewSpec.scala
- test/views/vatapplication/TwentyRatedSuppliesViewSpec.scala
> DL-15563 : Added the twenty rated page

- app/controllers/vatapplication/FiveRatedTurnoverController.scala
- app/forms/FiveRatedTurnoverForm.scala
- app/models/api/vatapplication/VatApplication.scala
- app/services/VatApplicationService.scala
- app/views/vatapplication/FiveRatedTurnover.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/test/controllers/vatapplication/FiveRatedTurnoverControllerISpec.scala
- test/forms/FiveRatedTurnoverFormSpec.scala
- test/views/vatapplication/FiveRatedTurnoverViewSpec.scala
> DL-15564: Added 5% TT Page

- conf/app.routes
> Update the routing url

- app/featuretoggle/FeatureSwitch.scala
- conf/application.conf
> add new featureflag for tt banners

- app/views/ApplicationProgressSaved.scala.html
- app/views/ManageRegistrations.scala.html
- conf/messages
- conf/messages.cy
- test/views/ApplicationProgressSavedViewSpec.scala
- test/views/ManageRegistrationsViewSpec.scala
> DL-15900 Content updates for VRS deadline

- app/config/FrontendAppConfig.scala
- app/views/ApplicationReference.scala.html
- app/views/TaskList.scala.html
- conf/logback.xml
- conf/messages
- conf/messages.cy
- test/forms/validation/FormValidationSpec.scala
- test/helpers/FormInspectors.scala
- test/views/ApplicationReferenceViewSpec.scala
- test/views/BaseSelectors.scala
- test/views/VatRegViewSpec.scala
> DL-15896 : Add Banners for VAT reg completion deadline

- test/views/ApplicationReferenceViewSpec.scala
- test/views/TaskListViewSpec.scala
> add more UTs for banners for TT journey May

- app/controllers/vatapplication/ZeroRatedSuppliesController.scala
- app/forms/ZeroRatedSuppliesNewJourneyForm.scala
- app/views/vatapplication/ZeroRatedSuppliesNewJourney.scala.html
- conf/messages
- conf/messages.cy
- test/controllers/vatapplication/ZeroRatedSuppliesControllerSpec.scala
- test/forms/ZeroRatedSuppliesNewJourneyFormSpec.scala
- test/views/vatapplication/ZeroRatedSuppliesViewNewJourneySpec.scala
> DL-15577: Update the 0% VAT Taxable Turnover Page

- app/controllers/vatapplication/ReducedRateSuppliesController.scala
- app/controllers/vatapplication/StandardRateSuppliesController.scala
- app/viewmodels/RegistrationDetailsSummaryBuilder.scala
- conf/messages
- conf/messages.cy
- test/controllers/vatapplication/ReducedRateSuppliesControllerSpec.scala
- test/controllers/vatapplication/StandardRateSuppliesControllerSpec.scala
- test/viewmodels/RegistrationDetailsSummaryBuilderSpec.scala
> DL-15744 Update Check Your Answers Page for Taxable Turnover

- app/controllers/vatapplication/TotalTaxTurnoverEstimateController.scala
- app/viewmodels/RegistrationDetailsSummaryBuilder.scala
- it/test/controllers/vatapplication/TotalTaxTurnoverEstimateControllerISpec.scala
- test/viewmodels/RegistrationDetailsSummaryBuilderSpec.scala
> DL-15578-2 : Fix the pence display

- it/test/controllers/vatapplication/ApplyForEoriControllerISpec.scala
- it/test/controllers/vatapplication/ImportsOrExportsControllerISpec.scala
**New feature - Test addition** (delete as appropriate)
> adding some UTs for TT part 2

- app/assets/javascripts/backLink.js
- app/views/layouts/layout.scala.html
**Bug fix ** 
[DL-16238](https://jira.tools.tax.service.gov.uk/browse/DL-16238)
> fix for DL-16238

- conf/messages
- test/views/vatapplication/ZeroRatedSuppliesViewNewJourneySpec.scala
> DL-16375 : heading changes in zero rate turnover page

- app/forms/StandardRateSuppliesForm.scala
- test/forms/StandardRateSuppliesFormSpec.scala
> DL-16444 : bugfix on whitespace char

- app/forms/ZeroRatedSuppliesNewJourneyForm.scala
- test/forms/ZeroRatedSuppliesNewJourneyFormSpec.scala
> DL-16451 : Fix regex

- app/assets/javascripts/backLink.js
> fixing back button issue DL-16238

- conf/messages.cy
> DL-16936: Welsh update

- app/connectors/BankAccountReputationConnector.scala
> Improve error logging when calling BankAccountReputation - validateBankDetails

- app/controllers/applicant/PreviousAddressController.scala
- app/controllers/bankdetails/HasBankAccountController.scala
- app/controllers/business/AddressCharacterLimitGuideController.scala
- app/controllers/vatapplication/AccountingPeriodController.scala
- app/viewmodels/AboutTheBusinessSummaryBuilder.scala
- app/viewmodels/ApplicantDetailsSummaryBuilder.scala
- app/viewmodels/RegistrationDetailsSummaryBuilder.scala
- app/viewmodels/TransactorDetailsSummaryBuilder.scala
- app/viewmodels/tasklist/AboutYouTaskList.scala
- app/viewmodels/tasklist/VatRegistrationTaskList.scala
- it/test/controllers/applicant/PreviousAddressControllerISpec.scala
- it/test/controllers/bankdetails/HasBankAccountControllerISpec.scala
- it/test/itFixtures/ITRegistrationFixtures.scala
- test/controllers/business/AddressCharacterLimitGuideControllerSpec.scala
- test/controllers/vatapplication/AccountingPeriodControllerSpec.scala
- test/viewmodels/ApplicantDetailsSummaryBuilderSpec.scala
- test/viewmodels/RegistrationDetailsSummaryBuilderSpec.scala
- test/viewmodels/TransactorDetailsSummaryBuilderSpec.scala
- test/viewmodels/tasklist/VatRegistrationTaskListSpec.scala
> DL-15895 Non-Established Taxable Person (NETP) entity type changes
